### ISSUE TITLE
Possible to create new certs with same alias while waiting for next block

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin#107]
I created a cert using MCA alias. I was able to create another cert immediately after using the same alias, even though I got an error message saying the attempt was unsuccesful. I then created 3 more certs within seconds of each other.

![sys_cert_bug_01](https://cloud.githubusercontent.com/assets/15713199/18412411/ab114a96-7785-11e6-9682-84c79d45ed80.jpg)

All 5 certs show up in my certs list, but only the first one is recognised by the system. ie. when I tried to edit one of the last four certs I got the attached error.

![sys_cert_bug_02](https://cloud.githubusercontent.com/assets/15713199/18412412/b1104ab4-7785-11e6-9bfd-0d49cb0543a4.jpg)

Here's what the transactions look like:

![image](https://cloud.githubusercontent.com/assets/15713199/18412476/28ab04d2-7787-11e6-8354-7cb25ec2a135.png)

**Comment by sidhujag** [comment]
please try again with latest binary

**Comment by sidhujag** [comment]
bump

**Comment by doublesharp** [comment]
Closing as this functionality was removed from QT.
