### ISSUE TITLE
My Escrow not showing when using Multisig Arbiters

### ISSUE THREAD

**Issue by Keyare** [syscoin/syscoin#114]
1) Created a 1 of X multisig alias "syscoin"
2) Assigned 2 additional aliases to the Alias, 'willy' and 'sebastien' making it a 1 of 3 alias
3) Purchased an item using Escrow with "syscoin" as arbiter
The offer does not show up under "My Escrows" on either 'willy' or 'sebastien' making it impossible for anyone except the main "syscoin" alias to manage escrow in this use-case.

**Comment by sidhujag** [comment]
retest
