### ISSUE TITLE
Purchasing Alias after expiry doesn't properly assign ownership

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#116]
1. Create alias as UserA, let it expire
2. As UserB purchase the alias
3. Note UserB pays for alias activation, UserA also sees an alias activation transaction. UserB doesn't get alias / doesn't show in alias list, aliasinfo.ismine=false. UserA see alias in non-expired list again, can edit, etc.

Expected: Alias is owned by UserB. UserA sees no transaction. UserA cannot edit alias.

**Comment by sidhujag** [comment]
retest
