### ISSUE TITLE
Original seller does not see who reseller is in affiliate transaction

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#124]
Image below is the original seller's view after a reseller sold his product. There is no indication of who is actually the reseller which is quite important depending on the type of transaction.

![image](https://cloud.githubusercontent.com/assets/7034589/21129530/09751a5c-c0d0-11e6-8c5d-e7ad8032b93a.png)

**Comment by sidhujag** [comment]
if you goto info on that you can see the offer id of the reseller

**Comment by sebastien1234** [comment]
do you mean the offerID in Other information under "details"? because the offerID is the original one, not the resellers.

![image](https://cloud.githubusercontent.com/assets/7034589/21169088/1b36b630-c187-11e6-87e9-f8a1ddf6f12d.png)

**Comment by sidhujag** [comment]
Ahh there isnt enough context to know its a resellers offer there... because the accept is same as resellers... i guess you would need to look at whitelist and see others offer accepts to see if one matches...

**Comment by sebastien1234** [comment]
Will BM be able to do that? If so, I'll remove the bug tag and keep as enhancement
