### ISSUE TITLE
Once you select an affiliate and he starts selling, there's no way to stop him from selling

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#125]
Attempt was made by reselling a cert offer

On a cert sale, there is no way to change the offer to 0

If for some reason, you could no longer sell the cert and wanted to stop a reseller from selling it, it's not possible.

Removing affiliate from "manage affiliates" list, does not stop an active resale

Changing the original offer to private only delists the original offer, not the latter.

There should be a way for the original merchant to stop the reseller from selling.

**Comment by sidhujag** [comment]
are you saying that after removing affiliate that someone was able to accept the offer from the reseller?

**Comment by sidhujag** [comment]
looked at the code, heres what a buyer should see:

"SYSCOIN_OFFER_CONSENSUS_ERROR: ERRCODE: 1101 - " + _("Linked offer alias does not exist on the root offer affiliate list");

**Comment by sebastien1234** [comment]
actually buyer sees a different error, but you are right, he's not able to purchase, error makes no sense:

![image](https://cloud.githubusercontent.com/assets/7034589/21168573/07728f06-c183-11e6-9420-336b5bccd216.png)

**Comment by sidhujag** [comment]
you should write down the steps for this.. this i think happens only because you have a negative discount offer

**Comment by sidhujag** [comment]
please retest in RC9
