### ISSUE TITLE
Price pegged direct transactions

### ISSUE THREAD

**Issue by einalex** [syscoin/syscoin#140]
Hi!
Here is the idea:
Implement the sending/receiving UI (especially on mobile) in a way that allows the user to specify their currency of choice (for pegging).
The transaction would of course still transfer sys, but the amount of sys could be derived from a price peg.

Alice can then easily send or receive 3.1415 $/€/£/ZEC/BTC/... worth of sys to/from Bob.
This would abstract the conversion rate and enable user friendly transactions.

**Comment by sidhujag** [comment]
2 parts to this, the sending should allow selection of rate amounts and the display of new payments should show the rate that was sent, so sending and recv portions. For the recv part to work the alias payment needs to include the rates peg used and the currency selected to be able to know what the payment was for and how much it was expected to be.
