### ISSUE TITLE
Systray icon is invisible (Windows 10)

### ISSUE THREAD

**Issue by ProkhorZ** [syscoin/syscoin#147]
The Syscoin icon is invisible in my Windows system tray. Syscoin does occupy a slot; you can right-click on it to open the context menu. The icon is visible on the wallet's title bar and in Windows Explorer. But when you minimize the wallet to the system tray, it's easy to forget that Syscoin is running. That's a security risk.

![syscoin systray](https://user-images.githubusercontent.com/22837744/28486755-188707da-6e86-11e7-8d5e-29c39ec186a3.png)

By the way, if the icon was displayed, it would still be hard to notice against a dark background.

Release: 2.1.4 
Build: Syscoin Core version v0.13.2.0-71e929b (64-bit)
Operating system: 64-bit Windows 10 Pro Creators Update

![syscoin systray full](https://user-images.githubusercontent.com/22837744/28491209-44d2ba16-6eed-11e7-9939-f91ae7458ef3.png)

Update: tested in Windows 7; systray icon was visible there.

**Comment by cydg** [comment]
Some other icons are missing too:
send tab / end of 'Pay to:' line all three icons not showing

Shouldn't the wallet show the HD / nonHD , connections and synced icons in the lower right corner?
