### ISSUE TITLE
Wallet crash when clicking New Public Key in Aliases

### ISSUE THREAD

**Issue by stoepjeslikker** [syscoin/syscoin#148]
Happens everytime I click the button

Version 2.1.4.

**Comment by sidhujag** [comment]
You sure your on 2.1.4? Type getinfo in console to verify please

**Comment by stoepjeslikker** [comment]
Like mentioned on Slack:
"sysversion": "2.1.4", 

"I already read the ticket from januari (2.1.3. bug), but I've got 2.1.4. like mentioned above and have this problem"

**Comment by sidhujag** [comment]
Ok will give it a try. Jfyi with blockmarket all of the qt services will be removed so this button will be gone soon

**Comment by willyko** [comment]
We on version 3.0.1 now.  Closing this as too old
