### ISSUE TITLE
Add additional currencies to price peg

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#16]
The price pegging option should also have the options of the three following currencies, if not more:

Chinese Yuan
Japanese Yen
South Korean Won

Danosphere's comment: These can be added through the SYS_RATES alias at any time, what we have in there right now is just what we use for testing, I can update it with more currencies or new rates for the current currencies. @sidhujag can you confirm that the UI elements in the wallet pull from the alias to populate things like the currency dropdown? If so we can close this...

moved from /syscoin issue 104.

**Comment by sebastien1234** [comment]
@sidhujag issue still current on 6/18 build, can you confirm what @dwasyluk was asking as we can close this if so: @dwasyluk comment: These can be added through the SYS_RATES alias at any time, what we have in there right now is just what we use for testing, I can update it with more currencies or new rates for the current currencies. @sidhujag can you confirm that the UI elements in the wallet pull from the alias to populate things like the currency dropdown? If so we can close this...

**Comment by sebastien1234** [comment]
Should def have CNY since we now are connected with our Chinese community.

**Comment by willyko** [comment]
Please reopen this issue at [https://github.com/syscoin/pricepeg](url)
