### ISSUE TITLE
can not start masternode in TOR network - "Inavali IP address" 

### ISSUE THREAD

**Issue by ID453543435** [syscoin/syscoin#161]
can not start masternode in TOR network, get error "Inavali IP address"

**Comment by ID453543435** [comment]
why? it fixed?

**Comment by sidhujag** [comment]
I do not know if ipv6 is supported from dash codebase id have to check.

try this https://www.dash.org/forum/threads/tor-masternode-guide.4094/

it would be great if you took initiative to figure it out and stand up the onion seeds and let us know here if you figure it out. Thanks!

**Comment by sidhujag** [comment]
theres this one too which seems to claim it works:

https://kore.life/masternode-guide/

**Comment by ID453543435** [comment]
remove the irevalent

**Comment by sidhujag** [comment]
sorry remove what from where??

**Comment by Duality-CDOO** [comment]
ipv6 is not supported in Dash codebase.

**Comment by ID453543435** [comment]
tor adress it like djknvhsuisdorhgdfsdsfg.onion

**Comment by Keyare** [comment]
Closed. Deprecated version.
