### ISSUE TITLE
Error in case of a wallet unlock

### ISSUE THREAD

**Issue by ghost** [syscoin/syscoin#176]
When I try to unlock a wallet, I receive such error (((
![screen shot 2018-05-02 at 07 52 51 am](https://user-images.githubusercontent.com/18265958/39505896-04707d20-4dde-11e8-8823-08ee4d9bb1d4.png)

**Comment by willyko** [comment]
Ok we got a work around for this issue.
Please head to http://syscoin.org/downloads-fix/Syscoin-Passphrase-Fix-Unstable.zip 
This patch will bypass the error so at least you can unlock your wallet.
Please follow this guide after to upgrade to 3.0.1 wallet
https://medium.com/@BlockchainFoundry/important-instructions-for-upgrading-to-syscoin-3-syscoin-3-0-1-release-d0708d146315

**Comment by ghost** [comment]
in version 3.0.1 the bug is corrected? I now have a purse without password

**Comment by sidhujag** [comment]
Yup.. just encrypt it after importing wallet.
