### ISSUE TITLE
CRITICAL!!! you use Dash coin code 5 from bip44, please change to 57 - not compatible with coinomi wallet

### ISSUE THREAD

**Issue by skironDotNet** [syscoin/syscoin#177]
the picture shows it all, please use https://coinomi.com/recovery-phrase-tool.html to see syscoin code and bip44 reservation for SYS is 57 https://github.com/satoshilabs/slips/blob/master/slip-0044.md

![sys-wrong-code](https://user-images.githubusercontent.com/2981715/39532724-00167800-4df3-11e8-8eb7-b6482ea6d0c7.png)

**Comment by sidhujag** [comment]
i can fix but hd support in syscoin 3 is intentionally disabled as it is incomplete and possibly insecure. Dash has this disabled for a reason too. Why are you using HD overriding default?

**Comment by skironDotNet** [comment]
because I want to use bip39 recovery from coinomi, unless coinomi will adjust to use DASH the problem is derivation path same address priv/pub will be used for DASH and Syscoin, so privacy issue, identification and so on, bip44 has been created for a reason. I discovered that when trying to import priv key from coinomi sys wallet

**Comment by skironDotNet** [comment]
Again this is not about HD, because I don't use any coin wallet, I use bip39 as master for all coins, but it makes no sense to be in Dash derivation path while syscoin has reserved 57. It's easy fix and will benefit all Coinomi users and. Also early fix is important before all people start using a new 3.0 wallet. Those who do use can simply transfer coins to fixed clinet/address generation
![bip44](https://user-images.githubusercontent.com/2981715/39533435-a9976c12-4df4-11e8-97ae-31c7f443a447.png)

**Comment by skironDotNet** [comment]
Can't import SYS address from Coinomi, obviously it expect Dash address format
![cant import sys address from bip39](https://user-images.githubusercontent.com/2981715/39533838-b4ed5bfc-4df5-11e8-855d-6e72a2ac713e.png)

**Comment by skironDotNet** [comment]
OK, neither Dash not SYS from Coinomi will import, so now I'm leaning towards Coinomi needs to adjust address format for SYS, 
I still stand about derivation path to use code 57 instead of 5

**Comment by skironDotNet** [comment]
Ok, BIP32 Root Key from Coinomi match rootkey HD from SYSCOIN 3.0 and and also priv key from bitcoin imports ok. I guess I will use bitcoin addresses for syscoin ...

**Comment by skironDotNet** [comment]
Coinomi SYSCOIN public address format is fine, just the private key is wrong... I crunch it for you :)

**Comment by skironDotNet** [comment]
Finally, seems like all good. I would still change HD generation to 57 but generally it was Coinomi fault to use wrong WIF number, you can see it here https://github.com/skironDotNet/bip39-passphrase/commit/665c59cbd6104edae1c3c915c303df50118789dc

I would still change HD generation to derivation path 57 for SYSCOIN wallet 3.0 (unless I'm wrong but appears as 5 as DASH just private key is encoded as syscoin, so DASH from Coinomi doesn't work due to different WIF number)

**Comment by sidhujag** [comment]
ok so hold on... syscoin base58 address prefix starts with "S" in syscoin 3... it will accept bitcoin address scheme but please don't do that if you don't have to. The private key format is the same for all coins based off of bitcoin mostly. I will def change the 57 to 5 thanks for that! Are you saying that if I change it to 5 then the WIF key format will somehow change to be able to importprivkey?

**Comment by skironDotNet** [comment]
No no the prefix starts with "S" in syscoin 3 is ok and was ok, and even ok with Coinomi bip39 tool as is (it just took me some time to figure things out, so my initial concerns/comment not quite valid). 

I found out the only reason I could not import private key from Coinomi bip39 tool was Coinomi has wrong WIF number for private key generation. 

You should just change to 57 for HD walled derivation so when you test this when "dumpwallet" you should have "hdkeypath=m/44'/57'/0'/0/0" no "hdkeypath=m/44'/5'/0'/0/0" that to be compatible with slip-0044 standard and thus with Coinomi wallet

**Comment by sidhujag** [comment]
ok thanks will do sir
