### ISSUE TITLE
Looks like linux masternodes are dying...

### ISSUE THREAD

**Issue by skironDotNet** [syscoin/syscoin#178]
My masternode was working for 4h+ and totally frozne didn't respond to syscoin-cli commands.
I checked the list of all masternodes in windows QT client, most of them show, expired, or new start needed, the longest MN was like 1 day and some hours.

Maybe there is some memory leak on Linux or whatever making Linux client froze, the process was showing ok in the process list bu unresponsive. Also it's not saving BC periodically, as I force killed the process, my BC started in previous start point.

It's first occurrence, so it's not conclusive but something to check, considering most MNs on the list looks strange

**Comment by sidhujag** [comment]
https://github.com/vii/libevent/commit/40ea13636b6da0f807963a75df4bc819a86f4cee

**Comment by sidhujag** [comment]
I think that may fix

**Comment by gaia** [comment]
Same here. Node starts, enables, then dies. If sentinel logged timestamps one could provide a better timeline of when it dies.
since RPC stops responding the only way to stop is to `kill - 9` the syscoind process

**Comment by sidhujag** [comment]
It would be nice to see how often sentinel touches rpc for syscoind

**Comment by ghost** [comment]
I have too most. I restart masternode each 3 hours, after restarting, almost payment ~ 26 SYS comes directly. Version 3.0.1
![screen shot 2018-05-03 at 07 02 07 am](https://user-images.githubusercontent.com/18265958/39591560-cc3eb96e-4f0c-11e8-9dd5-308f8e07272a.png)

**Comment by gaia** [comment]
I also got ~26 SYS once.

@sidhujag sentinel runs on cron, so whatever the cron setting is. the main guide recommends every 60 seconds.

**Comment by sidhujag** [comment]
No set it to 10 minutes 60 seconds is too quick even though that is not the problem.

**Comment by ghost** [comment]
@sidhujag 10 minutes its normal?

**Comment by longestline** [comment]
If it helps - this seems to affect syscoind that are running as masternode only. I have node running for almost 36 hours just as a seednode without issue.

But on a syscoind setup as masternodes it randomly occurs as described by OP a few times throughout the day.

**Comment by sidhujag** [comment]
If you follow dev-3.x branch we are trying to actively solve the problem there so try to pull on commits and test, once we are happy we will do a point release to master 3.0.2.

One thing I know is it is a mutex deadlocking issue so I'm targetting fixes for that case.

**Comment by longestline** [comment]
2 hour feedback on the dev-3x branch - no hangs or crashes so far across 3 daemons. This does not necessarily confirm it is fixed yet. However before there would have been at least 1 restart required in any 2 hour window looking back at the  past 24 hour period.

So this is looking promising.

**Comment by sidhujag** [comment]
yup lets give it atleast 6 more hrs

**Comment by skironDotNet** [comment]
Is the fix merged to master? or should I test dev-3.x ?

**Comment by willyko** [comment]
It's been merged to master branch tagged 3.0.2

**Comment by ghost** [comment]
When 3.0.2 release?

**Comment by willyko** [comment]
3.0.2 was released 10 hours ago

**Comment by skironDotNet** [comment]
so far 1 day and 12h didn't die, How long until first reward tho?

**Comment by ghost** [comment]
@skironDotNet the award comes about 3 times a day

**Comment by skironDotNet** [comment]
so what am I doing wrong, so far 0 rewards after 2.5 days. I ran MNs of some other coins, all works fine so I followed same setup, you could think of Dash, Pivx, Crown, Artax. Is anything special about sys. Or a chance I compiled wrong source? Firewall is open...
![sys3](https://user-images.githubusercontent.com/2981715/39726941-5e727486-5216-11e8-8c2e-c879d3e1702f.png)
![sys2](https://user-images.githubusercontent.com/2981715/39726942-5e8e74ce-5216-11e8-86ba-f6c23fce3162.png)
![sys1](https://user-images.githubusercontent.com/2981715/39726943-5eaa84f2-5216-11e8-9f06-d3bbe6f31dd8.png)

**Comment by locutus75** [comment]
Looks like an issue with your sentinel; check your sentinel config.

**Comment by skironDotNet** [comment]
After restart of both and activation (start allias), shows this 

![sys4](https://user-images.githubusercontent.com/2981715/39727797-ce1ecbc4-5219-11e8-867c-b5718f48f9a6.png)

Where is the sentinel config? what should be inside?

**Comment by skironDotNet** [comment]
ok I think I can cherry pick the installation commands from https://gist.githubusercontent.com/doublesharp/bacf7f9ac1ff15dccc1acffe49f989e9/raw/masternode.sh I can't use the script as is, my VPS runs multiple MNs

**Comment by johnp1954** [comment]
Should only be running 1 sys mn really

**Comment by locutus75** [comment]
Your VPS should not be running multiple masternodes.

**Comment by skironDotNet** [comment]
ha it must, already running 16 Crown systemnodes, As for SYS, yes only one... I'm almost there, so once I go thru, I'll close this, sorry for using as a support ticket, but it all started "there"

**Comment by sidhujag** [comment]
You may not run more than 1 instance of syscoind on a single OS especially linux as there are optimizations done in syscoind that set thread priority named after syscoin-pthread and it will not allow you to run multiple anyway, crown does not have this im sure.

**Comment by sidhujag** [comment]
for altruistic reason's you should not do this anyway, the whole reason for a masternode is to provide resources for network consumption in exchange for rewards, since in syscoin we will need as much network bandwidth and resources as possible from your server, sharing it with other resource intensive applications is a pretty bad thing and should be gaurded against.

**Comment by skironDotNet** [comment]
Ok, let's skip multiple MN thing, I can't afford more than one SYS anyway. Can you just help me investigate what /usr/local/bin/sentinel-ping should do? I did swap configuration to my paths, seems to be working but how can I tell it really does?

**Comment by skironDotNet** [comment]
it does write errors like "can't connect" ~/extra/sentinel/sentinel-cron.log but once I setup everything nothing got written there

**Comment by sidhujag** [comment]
As for your rewards, if you restarted your MNs you would have to wait about 27 hours before your rewards are scheduled, 2.6*# mn's * 60 seconds is the formula. sentinelping is an rpc command you can manually try using cli, sentinelping 1.1.0 will ping the network

**Comment by sidhujag** [comment]
check your debug.log with debug=1 enabled to ensure your pings are going through

**Comment by skironDotNet** [comment]
./syscoin-cli "sentinelping 1.1.0" returns true, but still not sure if the /usr/local/bin/sentinel-ping does it ok too. I don't know  this programming lang, so I don't know if it obtains correct rpcport since I'm using custom rpcport in syscoin.config, if port is hardcoded somewhere then it wouldn't work
![sys5](https://user-images.githubusercontent.com/2981715/39729727-115d028a-5223-11e8-818b-565661b4ce60.png)

from the other hand if it could not detected the port I would get all JSON rpc errors, but not getting them...

by "debug=1" you mean in syscoin.conf or  sentinel.conf ?

**Comment by sidhujag** [comment]
dont the other masternode coins use sentinel? its the same setup. debug=1 on syscoin.conf

**Comment by skironDotNet** [comment]
nope, I ran like MNB (total old client), Artax derivative of Dash I think, Crown, all configurations learned from Dash and PIVX as they are documented well,  and never heard of sentinel and all of them work :)

So using syscoin-cli I can see "ThreadRPCServer method=sentinelping" in debug file, but not when running /usr/local/bin/sentinel-ping

I'm thinking rpcport can you doublecheck, or confirm if you are sure? I couldn't find a reference in sentinel code to 'rpcport' other that one test stub
![sys6](https://user-images.githubusercontent.com/2981715/39730189-d01812b2-5225-11e8-912f-29793dabc07a.png)

**Comment by sidhujag** [comment]
They  must be really old then because sentinel came after the hardcoded ping protocol that was before dash 12... sentinel is on newer versions and is the basis for evolution and for us other governance activities.

That is a unit test look at the filename and where it is. Your port settings are in syscoin.conf

**Comment by skironDotNet** [comment]
Thank you for your help, I verified sentinel talks via RPC to syscoind. I'm closing this because many subscribed people here hate me now :) The point was nodes didn't die anymore. The rest is on me
