### ISSUE TITLE
Wrong version displayed on flash screen

### ISSUE THREAD

**Issue by NotTheFloor** [syscoin/syscoin#181]
Syscoin 3.0.1 Win64 release.

Flash screen on start up displays v3.0.0.0-7d11314 even though I have downloaded 3.0.1.

**Comment by p3yot3** [comment]
I also reported this, but dev closed the issue:

https://github.com/syscoin/syscoin/issues/180

**Comment by sidhujag** [comment]
will fix in 3.0.2
