### ISSUE TITLE
Fix strMessageMagic back to "Syscoin Signed Message:\n"

### ISSUE THREAD

**Issue by erasmospunk** [syscoin/syscoin#182]
In the latest master you have changed the strMessageMagic from "Syscoin" to "DarkCoin":
https://github.com/syscoin/syscoin/blob/f72c33ab7e77501f757375ae3901e9a11aaa0708/src/validation.cpp#L121

This was introduced in commit 953435c0a8ead0c32d0a0d05e68a3c9fbfde98a0

**Comment by doublesharp** [comment]
Thanks this has been fixed https://github.com/syscoin/syscoin/commit/347a11af9bf6c01780c42680c742228152ee768a
