### ISSUE TITLE
Debian 9 compile error

### ISSUE THREAD

**Issue by arisAlexis** [syscoin/syscoin#183]
i am running debian 9 with custom BerkeleyDB install. Syscoin 2.1.3 compiled well. New version fails with:

qt/paymentrequestplus.cpp: In member function ‘bool PaymentRequestPlus::getMerchant(X509_STORE*, QString&) const’:
qt/paymentrequestplus.cpp:166:20: error: aggregate ‘EVP_MD_CTX _ctx’ has incomplete type and cannot be defined
         EVP_MD_CTX _ctx;
                    ^~~~
Makefile:7768: recipe for target 'qt/qt_libsyscoinqt_a-paymentrequestplus.o' failed
make[2]: *** [qt/qt_libsyscoinqt_a-paymentrequestplus.o] Error 1
make[2]: Leaving directory '/home/user/syscoin-3.0.3/src'
Makefile:10440: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/syscoin-3.0.3/src'
Makefile:671: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by sidhujag** [comment]
I just did a fix for this in master can you try to pull and build?

**Comment by doublesharp** [comment]
I am able to compile on Debian 9 / Stretch with the following

```shell
# update
sudo apt update -y
 
# build tools
sudo apt install -y git build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3
 
# boost
sudo apt install -y libboost-all-dev
 
# berkeleydb 4.8 via syscoin contrib
source <(curl https://raw.githubusercontent.com/syscoin/syscoin/master/contrib/install_db4.sh) "$(pwd)"
export BDB_PREFIX="$(pwd)/db4"
 
# miniupnpc
sudo apt install -y libminiupnpc-dev
 
# zmq
sudo apt install -y libzmq-dev
  
# syscoin
git clone https://github.com/syscoin/syscoin.git && cd syscoin
./autogen.sh
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include"
make -j$(nproc) -pipe
sudo make install
```
