### ISSUE TITLE
aliasnew aliasupdate not realy work

### ISSUE THREAD

**Issue by ID453543435** [syscoin/syscoin#184]
aliasnew
aliasupdate
not realy work

**Comment by johnp1954** [comment]
A little more information might help

**Comment by sidhujag** [comment]
enable addressindex=1 in conf file

**Comment by ID453543435** [comment]
aliasnew just gives some wrong raw transaction
aliasupdate gives error "SYSCOIN_ALIAS_CONSENSUS_ERROR: ERRCODE: 5008 - Alias input to this transaction not found"

**Comment by ID453543435** [comment]
enable addressindex=1 in conf file <- have it

**Comment by sidhujag** [comment]
give exact steps to create alias

**Comment by ID453543435** [comment]
aliasnew newalias666 3 66666 "" "" "" ""

**Comment by sidhujag** [comment]
your missing 5 steps please follow procedure

**Comment by sidhujag** [comment]
example

https://github.com/syscoin/syscoin/blob/master/src/test/syscoin_alias_tests.cpp#L45

**Comment by ID453543435** [comment]
aliasnew newalias666 "public value" 3 66666 "" "" "" ""

**Comment by ID453543435** [comment]
SYSCOIN_ALIAS_RPC_ERROR: ERRCODE: 5502 - Insufficient funds inside the alias for this transaction (code -1)

**Comment by ID453543435** [comment]
SYSCOIN_ALIAS_RPC_ERROR: ERRCODE: 5502 - Insufficient funds inside the alias for this transaction (code -1)

**Comment by ID453543435** [comment]
aliasupdate gives
SYSCOIN_ALIAS_RPC_ERROR: ERRCODE: 5502 - Insufficient funds inside the alias for this transaction (code -1)
but funds have enought

**Comment by sidhujag** [comment]
please see the unit tests. marking this as a non-issue.
