### ISSUE TITLE
Syscoin 3 QT Masternodes Status Display

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syscoin#186]
There have now been multiple reports of the 'My Masternode' tab showing incorrect information, such as sentinel ping etc when in fact it is enabled when another user checks or you look on your server. This has not happened to me but it has to MCA and many others. There have been cases where users have pressed Restart thus resetting their validation time unnecessarily . I am running 3.0.3 on both QT and server.

**Comment by Thrash131** [comment]
I have a "New start required" but VPS says it OK and running
Active time is also freez from yesterday....

And only 1 payment from 2 MNs since yesterday evening(

**Comment by frozenfame** [comment]
This happens to me every time I go on QT. It will usually come around and read correctly but I've seen it take more then an hour even when everything is synced. The status I'm seeing is NEW_START_REQUIRED. Everything is good on MN server. I have mistakenly restarted a few times caused about 50hrs+ with no rewards. The other thing I noticed is that the number of masternodes and enabled nodes QT reports is different then in VPS using 
./syscoin-cli masternode count

My issue is occurring on Mac but has been reported on Windows as well. 

Version 3.0.2 for both QT and VPS

EDIT:
Upgraded both to 3.0.3 two days ago. Issue is still occurring.

**Comment by sysnodeinfo** [comment]
Receiving same issues, where NEW_START_REQUIRED is showing in QT, yet server side everything is okay. Display will switch back to ENABLED at random. Seems to be a display bug. Windows and Mac. Syscoin Core:3.0.2. Running Doublesharps 3.0.3

**Comment by sysmca** [comment]
Fixed an instance of this issue by upgrading my server daemon to 3.0.3. Qt was already 3.0.3.

![303302](https://user-images.githubusercontent.com/15713199/39921972-d9bcf0a2-5514-11e8-9248-d30950e88e69.png)

Win 10, 64bit Qt client

**Comment by benp1000** [comment]
Today I experienced QT reporting NEW_START_REQUIRED even though server was fine (Even received payment while showing that status). Running QT 3.0.3 on Win10. Running Syscoincore 3.0.3 on VPS (installed via doublesharps install script). Had been running these versions for about 4 days before I saw this issue. On previous version I had experienced this issue much more regularly.

EDIT:
btw I found on testnet that when I had qt not displaying properly that it would resolve if I did a rebuild index in wallet repair. But you have to wait a little bit after running it and then it corrects itself. Tried that today and it worked for me when my node showed new start required. Again had to wait a little bit after running it for the display to be corrected but it worked. I asked someone yesterday to try it and it worked for them too. No real practical reason to do it if you're not bothered by the display being wrong - but just reporting that for some reason that corrects it. But youd likely to have to keep doing that everytime the issues crops up

**Comment by blghdehaan** [comment]
Hi all,

Experiencing the same issue. Yesterday enabled, today for a short while the status “new_start_required”. After a few minutes it changed to “ENABLED” again. 

Version QT: 3.0.3.
Version syscoind: 3.0.3.0

**Comment by johnp1954** [comment]
Ok this has now happened on 1 of my MNs new start in Qt of on VPS

**Comment by alwoss** [comment]
Hi, I also had a problem with "NEW_START_REQUIRED" message today. I restarted both VPS and QT, everything was fine on the VPS (mn well synced) but I had the message "SENTINEL_PING_EXPIRED" for about 15-20 minutes on QT. After restarting QT another time everything was ok, seemed to be a display issue.

An other fact : I didn't received any rewards since 40 hours from now (before I used to receive between 2 and 3 rewards a day)

Version QT: 3.0.3 (on mac os 10.13.4 high sierra)
Version syscoind: 3.0.3.0

**Comment by gaia** [comment]
Dash has had a similar issue. It recommends deleting mncache.dat and mnpayments.dat then restarting QT.

https://github.com/dashpay/dash/issues/1338#issuecomment-280035317

I can confirm this has solved the problem for me (I'm on windows). But read below https://github.com/syscoin/syscoin/issues/186#issuecomment-400459456 it recommends against deleting mnpayments.dat

**Comment by gaia** [comment]
I can also confirm that the problem does not occur when you start QT after the AWS monitor changes to ENABLED. QT shows enabled and I did not need to delete the 2 files.

**Comment by johnp1954** [comment]
To correct the QT display issue can the QT just automatically delete mncache.dat on Startup, this seems to show the correct statues once the Sync is complete.

**Comment by Duality-CDOO** [comment]
Recommend NOT deleting your mnpayments.dat file as I believe you will lose your Masternodes ranking. Deleting the mncache.dat is the answer however.

**Comment by Keyare** [comment]
Closed. Deprecated version.
