### ISSUE TITLE
aliasupdate and aliasnew not realy work

### ISSUE THREAD

**Issue by ID453543435** [syscoin/syscoin#187]
aliasupdate and aliasnew not realy work

aliasupdate:
https://chainz.cryptoid.info/sys/tx.dws?51e35a660bab4410b7b4f330dce8c06e423a08f064fd2a755492213dfa4b45b6.htm
aliasnew:
https://chainz.cryptoid.info/sys/tx.dws?afe85dae8001a31523b0162716c9c9c66af4586c982141d32b616946fc7b9278.htm

**Comment by ID453543435** [comment]
aliasinfo show -> SYSCOIN_ALIAS_RPC_ERROR: ERRCODE: 5517 - Failed to read from alias DB (code -1)
and not updated alias

**Comment by doublesharp** [comment]
make sure you have `addressindex=1` in your `syscoin.conf` file and then restart with `syscoind -reindex`

**Comment by johnp1954** [comment]
If this is the issue and it does no harm being there can it be added by default on install

**Comment by doublesharp** [comment]
@johnp1954 @sidhujag 

We talked to Jag about this yesterday - it is off by default to save system resources where it is not needed. When you compile the binaries or install Qt is it not enabled however it will be enabled in BM3 as it directly accesses Syscoin services.

**Comment by johnp1954** [comment]
OK should you disable it in your MN script

**Comment by ID453543435** [comment]
make sure you have addressindex=1 in your syscoin.conf file and then restart with syscoind -reindex
i have it

**Comment by ID453543435** [comment]
may be it worc in your testnet but for real money it not worck any way

**Comment by ID453543435** [comment]
may be it work in your testnet but for real money it not work any way

**Comment by doublesharp** [comment]
@ID453543435 I have been able to use my alias on the mainnet.

**Comment by sidhujag** [comment]
You maybe can wait for blockmarket as it will be easier through a user-interface @ID453543435

**Comment by ID453543435** [comment]
it whay poloniex regect this fork

**Comment by ID453543435** [comment]
sidhujag  cannot wait

**Comment by sidhujag** [comment]
then i need clear steps. The unit tests show it and it does work. You must be missing a step

**Comment by Alternating** [comment]
I have tested Every aspect of creating and updating aliases on the command line and I can assure you it works fine. If it is not working for you its probably a syntax error you are introducing or you are not reading the directions.  https://blockchainfoundryco.atlassian.net/wiki/spaces/PUB/pages/38404136/How+to+Create+Alias+Assets+Syscoin+3.0+UPDATED
I have used this as a base and yes it requires some changes to the syntax. Please read your out-puts.

**Comment by ID453543435** [comment]
ok, but "aliasupdate" still not work

**Comment by Alternating** [comment]
That is untrue. I update expiration dates on 6 aliases. Go check your syntax or wait for blockmarket

**Comment by ID453543435** [comment]
Alternating, exactly the same steps on real network didnt work:
https://chainz.cryptoid.info/sys/tx.dws?f02bd8117aaac022e55f6a4932f495fc82f023b127ad7be473bd67f17dbdb7e5.htm

**Comment by Alternating** [comment]
Please join the slack so we can help you directly. This is a syntax issue that you are implementing.  I'm not clicking on any of your links from github. Thank you. I would close this ticket out if i could cause it is a non-issue.

**Comment by Alternating** [comment]
aliasupdate name name sysaddress 3 1665870345 "" "" ""   Proper syntax.. then fund it, signit, syscoinsendit
Also doublecheck your epoch times to ensure you got enough sys to cover your expiration dates https://www.epochconverter.com/

**Comment by ID453543435** [comment]
Alternating 
aliasnew willyk.com "" 3 0 "" "" "" ""
then steps from https://blockchainfoundryco.atlassian.net/wiki/spaces/PUB/pages/38404136/How+to+Create+Alias+Assets+Syscoin+3.0+UPDATED

**Comment by ID453543435** [comment]
SYSCOIN_ALIAS_CONSENSUS_ERROR: ERRCODE: 5017 - Transaction does not pay enough fee: 0.00009964/92233720368.54765808/5.8494242e+011 years. (code 16)

**Comment by sidhujag** [comment]
try it again.. i get that message once in a while.

**Comment by ID453543435** [comment]
SYSCOIN_ALIAS_CONSENSUS_ERROR: ERRCODE: 5008 - Alias input to this transaction not found (code 16)

**Comment by ID453543435** [comment]
most terrible peace of code

**Comment by ID453543435** [comment]
most terrible peace of code

**Comment by ID453543435** [comment]
most terrible peace of code

**Comment by ID453543435** [comment]
why default alias live time 1 hour if it cost same like 1 year?
all these complexities are made out of wrecking motives

**Comment by sidhujag** [comment]
The code works as intended, please join slack and get your answers there or wait until blockmarket comes to use an alias thanks!
