### ISSUE TITLE
Message Info - Timestamp is missing

### ISSUE THREAD

**Issue by mucalov** [syscoin/syscoin#2]
Time is missing in Message Info window.
![timestamp_missing](https://cloud.githubusercontent.com/assets/6578651/13403423/3f5e1602-df15-11e5-9274-3b48e838aa9e.png)

**Comment by sidhujag** [comment]
retest in latest build

**Comment by sebastien1234** [comment]
@sidhujag works for me in latest 3/7/2016 build. fix #2
