### ISSUE TITLE
Editing offer does not allow you to change the currency type / feature request

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#20]
marketplace/selling/edit offer:

When editing an offer, should be able to change the currency, it's currently greyed out. @sidhujag advised this is by design and to request a feature request.

![image](https://cloud.githubusercontent.com/assets/7034589/13559811/1cf7ab2a-e3e6-11e5-87a0-2357422a7aa9.png)

moved from issue 133 in /syscoin

**Comment by sebastien1234** [comment]
issue #20 remains an issue on build 6/18

**Comment by willyko** [comment]
Closing; Offer function UI has been moved to Blockmarket
