### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by vr4dude316** [syscoin/syscoin#202]
unomp@ubuntu:~/syscoin$ make
make: *** No targets specified and no makefile found.  Stop.

Cannot get past this compiling

**Comment by vr4dude316** [comment]
configure: error: Could not link against boost_chrono !

**Comment by sidhujag** [comment]
what boost version? you havr chrono installed or built?

**Comment by vr4dude316** [comment]
I suppose not.
Can you provide in on how to install?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vr4dude316** [comment]
I run this and tells me that is already installed…
unomp@ubuntu:~/syscoin$ sudo apt-get install libboost-chrono-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libboost-chrono-dev is already the newest version (1.58.0.1ubuntu1).
Get Outlook for Android<https://aka.ms/ghei36>

**Comment by doublesharp** [comment]
What version of Ubuntu are you using? How did you install the dependencies?

**Comment by vr4dude316** [comment]
Is version 16.04 and depends were installed as usual per the unix build doc on github.

Chris Staples
Manager, Information Systems
Marist School
3790 Ashford Dunwoody Rd
Atlanta, GA 30319
770.936.6403
staplesc@marist.com

**Comment by doublesharp** [comment]
I wrote that guide and I've used it on several Ubuntu 16.04 machines so
it's weird you're having trouble. Did you install the boost libraries one
by one? The latest version of boost is newer than what you have, so you can
also try to compile from source in the depends directory.

**Comment by vr4dude316** [comment]
Ok.  I will run through again and try again.  I have other coins running on this box.  Maybe something interfering.

Thx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by doublesharp** [comment]
Running multiple masternodes per machine is not supported and is very likely the issue. If you do get it working keep in mind that there are no guarantees against future breaking changes for your configuration.
