### ISSUE TITLE
Unable to create an alias with aliasnew

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syscoin#204]
I have this issue , no matter what i tried i could not get it to confirm the first TX, discussed this with @willyk with no solution. The only way I could get Alias creation to work was to create a new wallet. I am hoping that it works when we get BM3 as all my MN coins are in the wallet that does not work. So to summarise, I have 3 wallets all on 3.0.4 2 will allow Alias creation (and this is just Aliasnew no funding etc) 1 (My Main wallet) will not allow it. I have tried clearing syscoincore,rescan,reindex dumpwallet none of these worked. This wallet was the one i imported from Sys 2 via 3.0.0 and salvagewallet=1. It seems that i am not the only one having these issue now.

**Comment by oldominion** [comment]
I too have this issue. Same upgrade path.

**Comment by bstr156** [comment]
Same issue.  First TX will not confirm.  Running Syscoin Core version v3.0.2.0-dbe0afd for what it's worth.  "Recover Transactions 1" seems to clear the stuck transactions.   Syscointxfund was executed using an MN address with all mined transactions having > 101 confirmations, fully confirmed.  Discussed with @doublesharp.  No solution as of yet.

**Comment by bstr156** [comment]
Issue _might_ be related to addresses generated in non-HD wallets.  It appears we can create aliases fine as long as the TX funding address is recent, and the target address for the alias is recent or HD.  

Two problem scenarios:
1) When using an older address (generated shortly after the Syscoin 3 hard fork) to fund the alias TX, the first transaction is never confirmed.
2) When using a newer address to fund the alias TX, and attempting to associate an alias with an older address, the first transaction confirms fine, but the second execution of `syscoinsendrawtransaction` produces an error.  The following shows up in the log: "insufficient priority (18270 < 18540)" accompanied by "66: insufficient priority (code -1)" as the Console output.

**Comment by johnp1954** [comment]
Ok so to summarise 
1) You cannot create an Alias in a wallet that was HD without creating a new HD address as the funding source.
2) You cannot create an alias on an existing non HD address even with using a HD funding address.

**Comment by sidhujag** [comment]
please try in 3.0.4.1

**Comment by doublesharp** [comment]
https://github.com/syscoin/syscoin/releases/tag/3.0.4.1

**Comment by doublesharp** [comment]
Closing as 3.0.4.1 confirmed to fix tx fees for alias creation with several users having issues with older versions.
