### ISSUE TITLE
Missing icons in bottom right, 3.0.2 and also 3.0.4

### ISSUE THREAD

**Issue by oldominion** [syscoin/syscoin#205]
Missing HD and Padlock symbols in the wallet on Windows 7 64Bit. Another use in slack also has this issue on MAC. Just upgraded to 3.0.4 from 3.0.2 with a fresh Syscoincore folder, and still have the issue.

![image](https://user-images.githubusercontent.com/8029180/40503405-de258868-5f85-11e8-81dd-518203d77545.png)

**Comment by oldominion** [comment]
This is due to no User Interface Theme being selected by default. Changing to SYS-light Theme, it looks as it should.

**Comment by oldominion** [comment]
OK, so choosing SYS-light-hires, the HD icon is not visible, but you can hover over the space for the text.

**Comment by johnp1954** [comment]
This was the same problem for the user on a MAC no default selected

**Comment by Keyare** [comment]
Closed. Deprecated version.
