### ISSUE TITLE
Windows installers triggering Anti Virus

### ISSUE THREAD

**Issue by Keyare** [syscoin/syscoin#217]
Users are reporting Kaspersky and AVG showing that Windows installers are corrupt

**Comment by Keyare** [comment]
Also triggering Windows Defender.

**Comment by johnp1954** [comment]
Windows defender also always triggers on running syscoin-qt.exe the first time, but you are aware of this

**Comment by Keyare** [comment]
Confirmed. See: https://github.com/syscoin/syscoin/wiki/Security-Notice-for-Windows-based-installers
