### ISSUE TITLE
Masternode went into  "SENTINEL_PING_EXPIRED" status and stays there after a few days of normal work

### ISSUE THREAD

**Issue by photigy** [syscoin/syscoin#221]
All was Ok, MN was enabled. However, today noticed "SENTINEL_PING_EXPIRED" on the wallet, while "Masternode successfully started" on VPS MN status.
Tried to start it again from the wallet, did not help.

**Comment by sysnodeinfo** [comment]
Always go off your VPS - QT has an inherited bug from DASH I believe which shows wrong information in regards to masternodes. As long as your Masternode is enabled on VPS, do not touch QT, as this restarts your eligibility period, and you will need to wait 45+ hours at present time to receive rewards.

**Comment by photigy** [comment]
Well - I hope it is like this, but on masternodes.online monitoring MN is showing "offline" with the status "SENTINEL_PING_EXPIRED" No rewards so far - running for a 3rd day.  How can I make sure MN is running ok, other than looking at the QT or VPS?  
On VPS status is "4", started.

**Comment by sysnodeinfo** [comment]
You can check the actual status on your node via 
$ syscli masternodelist full | grep YOURIP 
or 
$ ~/syscoin/src/syscoin-cli masternodelist full | grep YOURIP

**Comment by photigy** [comment]
Thank you, checked. It saying "SENTINEL_PING_EXPIRED". How to fix this?

**Comment by fher98** [comment]
Hello, I used the start bottom from the wallet 12 hours ago, and Im still seeing in the node

  "status": "Not capable masternode: Masternode in NEW_START_REQUIRED state"

**Comment by Keyare** [comment]
Closed. Deprecated version.
