### ISSUE TITLE
"SENTINEL_PING_EXPIRED" after upgrade to v3.0.6

### ISSUE THREAD

**Issue by p3yot3** [syscoin/syscoin#229]
After upgrading both my masternodes & QT wallet to the latest version my QT wallet now shows the dreaded "SENTINEL_PING_EXPIRED" for my masternodes.

Masternodes themselves are all reporting that they are running & successfully syncd.

**Comment by johnp1954** [comment]
Really no point raising Githup issue for a non issue go to #masternodes

**Comment by p3yot3** [comment]
I'm sorry, what do you mean a non issue? It was working fine before the upgrade & now it isn't - I consider that to be an issue.

**Comment by p3yot3** [comment]
Just seen a post from dev on BCT about this - the update script was broken apparently, causing the issue. I've used the updated script & everything now seems fine.

Thanks dev for posting - closing this now.
