### ISSUE TITLE
Reply Message screen issue

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#23]
Messages/Inbox/Reply:

When Replying to a message, "original" message appears to be editable, which should not be the case and should be greyed-out:

![image](https://cloud.githubusercontent.com/assets/7034589/13691965/2f1e7716-e70b-11e5-9fc4-b4e7184282f4.png)

**Comment by sebastien1234** [comment]
issue #23 remains on build 6/18 @sidhujag

**Comment by willyko** [comment]
Closing this.  Messaging function has been moved to Blockmarket
