### ISSUE TITLE
doublesharp.com/sysmasternode Script

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syscoin#231]
If you use this script to update your VPS and ask for sentinel to upgrade too it seems to break sentinel. Using the script amended by Alex does not break it when updating Sentinel. It has been like this for 1.5 hours now.
![image](https://user-images.githubusercontent.com/16462796/41921637-38d71cf6-795b-11e8-884a-a47dc833c729.png)

**Comment by sidhujag** [comment]
need more details.. hows it break sentinel

**Comment by johnp1954** [comment]
If i knew that i could fix it :-)

**Comment by doublesharp** [comment]
Not enough info to debug

**Comment by johnp1954** [comment]
Let me know what i can do to give you that info

**Comment by johnp1954** [comment]
I can give you access to the VPS if that would help

**Comment by doublesharp** [comment]
Is the sentinel folder created under the syscoin use home? What's in the debug log? Are the cron jobs for the syscoin user set up? If you are running other scripts are they doing anything that might conflict especially permissions? Can you run the ping manually?

**Comment by johnp1954** [comment]
Just FYI this worked fine before the upgrade
1) Yes
2) Isnt one
3) * * * * * /usr/local/bin/sentinel-ping
4) No
5) 
![image](https://user-images.githubusercontent.com/16462796/41925175-b7fc5516-7963-11e8-9fed-f5e8c36d4eda.png)

**Comment by johnp1954** [comment]
Others say
*/10 * * * * /usr/local/bin/sentinel-ping 
Is this the issue?

**Comment by johnp1954** [comment]
Ok well i have to reinstall now before i have to go through the grace period again

**Comment by doublesharp** [comment]
The Sentinel log is in `~/sentinel/sentinel-cron.log` under the `syscoin` user. Cronjob will run once per minute (people were impatient) but `*/10` should work fine too, but will take longer to update from ping expired. Nothing in your setup seems off, so check the log and try to run the ping as the syscoin user `sudo su -c "sentinel-ping" syscoin`.

**Comment by johnp1954** [comment]
Had to rebuild will try again when things calm down, there was no ~/sentinel/sentinel-cron.log

**Comment by doublesharp** [comment]
Then the ping is never running but I suspect you are looking in the wrong place - did you check as the syscoin user? When you use `~` it means "home" so you have to run it as that user - `sudo su -c "tail ~/sentinel/sentinel-cron.log" syscoin`.

I also checked out @einalexes script and it does not work properly, it updates sentinel in the wrong location (current user home). It will have no effect on the sentinel/ping/crontab running as the `syscoin` user.

**Comment by jvlugoinv** [comment]
Sorry to interject the conversation, but I am in the same boat. Applied
Justin's script to upgrade 3.0.5 (which was working perfectly fine) to
3.0.6, used the script to upgrade with the option to also update Sentinel,
and now the mn is down for a whole day with SENTINEL_PING_EXPIRED status.

Any solution on this?

**Comment by jvlugoinv** [comment]
Working with @einalex. He found that the /usr/local/bin/sentinel-ping file
was empty. He guided me to add this to the file:

---
#!/bin/bash

/home/syscoin/sentinel/venv/bin/python
/home/syscoin/sentinel/bin/sentinel.py 2>&1 >>
/home/syscoin/sentinel/sentinel-cron.log
----

**Comment by doublesharp** [comment]
Thanks @jvlugoinv - I re-ordered commands in the script and it should work now.

**Comment by doublesharp** [comment]
@jvlugoinv @johnp1954 you can rerun the script and it will update the file correctly.

**Comment by johnp1954** [comment]
Rerun with no issues Thanks
