### ISSUE TITLE
Display Issue with assets/tokens

### ISSUE THREAD

**Issue by Alternating** [syscoin/syscoin#232]
Noticed my balance (tokens) for a particular asset in block market desktop did not reflect what I actually had which created confusion. Although my alias controlled the asset it actually did not have any tokens. 
![image](https://user-images.githubusercontent.com/28740917/41940545-ae5936a0-795e-11e8-9adb-b14a8e5ab2a3.png)

My quick test was to send that token to that alias and sure enough it cleared up the incorrect display 
![image](https://user-images.githubusercontent.com/28740917/41940572-c4fe3252-795e-11e8-90a3-01998b1daed4.png)

It just created confusion so low priority. not sure why it did that. Its like it used the balance of the asset I control in the token section. But it was for only this particular asset I have 4 others that this did not occur. Weird

**Comment by Keyare** [comment]
Closed. Deprecated version.
