### ISSUE TITLE
Alias sending Tokens needs to be known by receiving party / option to refuse tokens necessary

### ISSUE THREAD

**Issue by Mettamark** [syscoin/syscoin#233]
1. As tokens symbols are not unique, the sending alias needs to be visible so the wallet owner knows whether a token received is actually legitimate (Currently, two aliases could each setup the token ETH and receiving alias would currently not know which one was legitimate).

2. A receiving wallet should also be able to deny tokens – prevent spam of unwanted tokens clogging up one's wallet.  This will also addresses legal issues, as tokens may be linked to illegal activity/content that receiving alias would not want to be associated with.

3. Ideally, assets would also list # of tokens sent to each alias, not just total # of tokens left available.

**Comment by Keyare** [comment]
Closed. Deprecated version.
