### ISSUE TITLE
can't send funds from QT wallet

### ISSUE THREAD

**Issue by skironDotNet** [syscoin/syscoin#235]
When trying to send, getting 2 errors that are not logged in debug.log 
Any ideas?
![2018-07-05 11_14_31-syscoin core - wallet](https://user-images.githubusercontent.com/2981715/42335219-410c8960-8045-11e8-88c3-6abb46e178e4.png)
![2018-07-05 11_14_38-syscoin core - send coins](https://user-images.githubusercontent.com/2981715/42335218-40fc2994-8045-11e8-9309-2842c69125b0.png)

**Comment by sidhujag** [comment]
need more info... this does not help. The creating of tx for sending sys works, not sure what commands your calling.

**Comment by skironDotNet** [comment]
Yeah I know, you need more info, but debug.log doesn't have anything about that. I don't call any commands I use GUI wallet, and this is what happens after clicking Send.

Only thing I can tell the wallet is build by importing private keys from coinomi address generator, and I had masternode running, when I wanted to send funds form MN (after unlocking using coin control window) I was getting same error, so I use android coinomi wallet to "break" MN by sending part of the funds, everything was sent nicely and visible in both coinomi and QT wallet as sent. 
Then I sent funds back to another address within my wallet and I have over 100k sys as it should be, and I want to sent round 100k to another address in my wallet to have MN again.

I think you can't help me, because there is no way to debug without directly having my wallet in hand, but maybe you could investigate source code for what happens when  someone is trying to send funds from active masternode?

coin controll
![2018-07-05 12_01_14-coin selection](https://user-images.githubusercontent.com/2981715/42337234-bb298602-804b-11e8-8b21-ab08c298cb9a.png)


and sending to my own wallet and my own change address that is imported 
![2018-07-05 12_03_22-syscoin core - wallet](https://user-images.githubusercontent.com/2981715/42337238-bead15c8-804b-11e8-8e9d-282f7a4b323a.png)

**Comment by sidhujag** [comment]
try this: dump your wallet, save it.. delete your data directory, import your wallet and index the blockchain.. that will give you correct state. It seems like it cannot sign the inputs your wallet things it has.

**Comment by skironDotNet** [comment]
Yeah I'll try it because I'm getting this, makes no sense, maybe there is some bug on top of it, the JSON thing...

I think you are right wallet may be messed up because it was Coinomi sending and QT wallet didn't record that information... but it does show spent TX, so I was trying to check that TX 

From CLI
![2018-07-05 12_25_59-cmdr](https://user-images.githubusercontent.com/2981715/42338244-cf6df7da-804e-11e8-9f37-f7076b35c5b5.png)

From debug window in QT
![2018-07-05 12_24_00-tools window](https://user-images.githubusercontent.com/2981715/42338254-d5022252-804e-11e8-88a9-0964e7465a1f.png)

**Comment by skironDotNet** [comment]
Wallet dump and import almost worked but this tiny amount you can see in my first posed coin control won't import neither as  walletimport or importpriv key, but the address shows balance on explorer.
ShpWB5A2vHLpkrzzDrgwNCYqTt9Xt1GTBB

This is above my understanding, the address was generated as HD part because when I was sending funds from QT I forgot to use "custom change address" and this fraction was sent to "in wallet" change address. It does exports as part of dumpwallet but can't import. Is this balance lost somehow?
(that's probably the reason it couldn't sign the TX from original wallet)
I haven't delete data directory yet as advised, because I didn't want to sync BC from 0 but since it's small I can try now too...

![2018-07-05 12_47_56-coin selection](https://user-images.githubusercontent.com/2981715/42339603-0cbe43ca-8053-11e8-9fd1-172458bd37f4.png)

**Comment by skironDotNet** [comment]
It's not worth spending the time for 0.97 SYS, I consider this lost.
Final conclusion is that HD generation of QT wallet does generate valid public address but invalid private key, then when you want to sent funds can't sign TX because you have no priv key. Also can't import that private key to another wallet.

I will still work on this out of curiosity, if I can generate proper priv key from root bip32 key from original wallet dump....

**Comment by skironDotNet** [comment]
Finally figured it out - damn I'm smart!

Here is the story, my wallet was created using Syscoin 3.0 and this version was using derivation path 5 instead of 57 thus at first I wasn't able recover correct priv key using bip32 tool as I was using path from new Syscoin 3.6 where dump was shown as m/44'/57'/0'/1/0

The private key from wallet was indeed wrong format and so even old SYS 3.0 couln't import it, but thanks to revising versions I was able to try my wallet dump xpriv key for bip32 with path m/44'/5'/0'/1/0
and successfully generated proper priv key that is importing and accessing the balance.

Many thanks @sidhujag for your quick support that pushed me in correct direction of solving my case only issue.
Also thanks @sidhujag for keeping older versions of QT in Releases tab and for documenting changes for each release, without it I would not be able to figure it out
(thanks to myself for asking @sidhujag to upgrade derivation path from 5 to 57 as this also is compatible with Coinomi and iancoleman.io  and generates proper keys)
