### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zhangtiantian222** [syscoin/syscoin#236]
![image](https://user-images.githubusercontent.com/38236278/42564507-871814c2-8533-11e8-81e5-4866cb573d9a.png)

 Synchronization stops at 87599, upgrade to syscoin3.0.6.1 shows the connecting node

**Comment by c-e-d-git** [comment]
Happened because you updated far too late.
3.0.5 or below got stuck at that block because it could not validate the following superblock.
You need to either use invalidateblock + reconsiderblock or reindex (Tools->Wallet Repair->Rebuild index).
Solution is on the Syscoin Slack all over the place.

**Comment by doublesharp** [comment]
You need to be running version 3.0.6+ and restart with -reindex
