### ISSUE TITLE
White corner out of place

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#24]
Messages/Inbox or Outbox:

The table that shows the outbox or inbox history on the top left of the table has an out-of-place looking square box:

![image](https://cloud.githubusercontent.com/assets/7034589/13692019/a3f2e63a-e70b-11e5-855d-0e1c1347a826.png)

This should match other parts of the wallet that has a simliar layout like "transactions":

![image](https://cloud.githubusercontent.com/assets/7034589/13692038/d7fe5176-e70b-11e5-8286-c59da3b5d85e.png)

**Comment by sebastien1234** [comment]
@sidhujag issue #24 remains in build 6/18

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
