### ISSUE TITLE
Regtest mode peering RPC and P2P port

### ISSUE THREAD

**Issue by qizhong19920114** [syscoin/syscoin#242]
Hi, 

I'm trying to do **regtest** mode to build a private network on syscoin. I couldn't get the nodes to peer with each other. 

I used 18443 for RPC and 8398 for P2P and it didn't work. So I'm wondering what's the correct ports and what could be the potentially issue for them not peering.

**Comment by qizhong19920114** [comment]
Errors I'm getting shown below: 

_node2_1  | 2018-07-12 20:50:07 connect() to 172.23.0.4:18443 failed after select(): Connection refused (111)
miner_1  | 2018-07-12 20:50:07 connect() to 172.23.0.4:18443 failed after select(): Connection refused (111)
node1_1  | 2018-07-12 20:50:07 connect() to 172.23.0.3:18443 failed after select(): Connection refused 
node2_1  | 2018-07-12 20:50:07 connect() to 172.23.0.3:18443 failed after select(): Connection refused (111)
miner_1  | 2018-07-12 20:50:08 connect() to 172.23.0.2:18443 failed after select(): Connection refused (111)
node1_1  | 2018-07-12 20:50:08 connect() to 172.23.0.2:18443 failed after select(): Connection refused (111)_

**Comment by willyko** [comment]
Try using a routable IP?

**Comment by qizhong19920114** [comment]
@willyko. The two ip addresses can ping each other. I don't see why they are not routable

**Comment by tomergev** [comment]
+1

**Comment by willyko** [comment]
Please add this to your conf file.  "-allowprivatenet=1". 
This allows RFC1918 addresses to be relayed and connected to and it's set to false by default.

Please see [https://tools.ietf.org/html/rfc1918](url)

3. Private Address Space

   The Internet Assigned Numbers Authority (IANA) has reserved the
   following three blocks of the IP address space for private internets:

     10.0.0.0        -   10.255.255.255  (10/8 prefix)
     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)
