### ISSUE TITLE
Blockmarket does NOT load 

### ISSUE THREAD

**Issue by kriptorick** [syscoin/syscoin#252]
Hello
So I have installed 'Blockmarket-3.0.dmg' on 1st of July after deleting all files of the old version and QT version. 
When opening the application, instead of loading from %1 to %100(bottom left) Blockmarket stuck on the 'Loading' as shown in the picture below. Meanwhile it creates 3 different folders(Blockmarket/syscoincore/SyscoinCore) under "Library> Application Support"
<img width="994" alt="screen shot 2018-06-28 at 18 03 38" src="https://user-images.githubusercontent.com/41576091/43147908-d45d4e6c-8f6c-11e8-89c5-cdb39a0ed52d.png">

Here are which files it creates under those folders:
**1.) 'Blockmarket'** 
_Blockmarket.json
blockmarket.log
bmd_data.sqlite
Cache
Cookies
Cookies-journal
GPUCache
Local Storage
Preferences_
**2.) 'syscoincore'**
_syscoin.conf_
**3.) 'SyscoinCore'**
_aliases
assetallocations
assetallocationtransactions
assets
backups
banlist.dat
blocks
certificates
chainstate
db.log
debug.log
escrow
fee_estimates.dat
governance.dat
masternode.conf
mempool.dat
mncache.dat
mnpayments.dat
netfulfilled.dat
offers
peers.dat
syscoin.conf
wallet.dat_

**Comment by jnessbcf** [comment]
Hey there,

Looks like you're experiencing a similar issue to what a different user encountered.  This has been fixed and will be part of the next BMD release.  Will close it at that time.

**Comment by doublesharp** [comment]
Please use https://github.com/syscoin/blockmarket-desktop-public/issues for Blockmarket issues, thanks!
