### ISSUE TITLE
Off-line multi sign

### ISSUE THREAD

**Issue by xianaofei** [syscoin/syscoin#255]
Do you support off - line multi - sign?
Please provide a reference, thank you.

**Comment by doublesharp** [comment]
Can you be more specific? You should be able to sign as long as you have private keys regardless if you are connected to peers or not, you just wouldn't be able to submit the tx.

**Comment by xianaofei** [comment]
@doublesharp  hi  I mean multi signature.
For example, 5 sign 3, each transaction needs 3 private keys for signature confirmation before payment can be made.
In addition, offline refers to each transaction does not need to be sent online, offline generation of transactions, the transaction can be copied to the networked machine to send.
