### ISSUE TITLE
Help text for assetallocationcollectinterest is misleading - executes differently

### ISSUE THREAD

**Issue by bstr156** [syscoin/syscoin#259]
I decided to attempt assetallocationcollectinterest via QT Console, to see whether this would work because I was receiving an error in Blockmarket when attempting to collect interest on CPS Coin.  I discovered this command's help text is misleading.  

It reads: 
"assetallocationcollectinterest [asset] **[alias] [witness]**"

But the command executes as:
"assetallocationcollectinterest [asset] **[witness] [alias]**"

The good news is the command works!  I was able to see successful collection of interest once I finally figured out 'alias' and 'witness' are reversed.

Could this issue be the cause for Blockmarket's error?  (see: [https://github.com/syscoin/blockmarket-desktop-public/issues/389](url)).  Either way, the help text discrep needs to be reported, so here you go.

**Comment by locutus75** [comment]
Great find, thanks!
