### ISSUE TITLE
AliasDB recreated but alias records are not reloaded

### ISSUE THREAD

**Issue by CryptoDJ** [syscoin/syscoin#263]
After I delete the alias directory in the data directory, I can not find existing alias entries anymore.

This is before deleting the alias directory:
![before-aliasdb-deleted](https://user-images.githubusercontent.com/13896934/44302692-e951b980-a2f3-11e8-8981-88b1d472f9f6.png)
 
This is after deleting the alias directory:
![after-aliasdb-deleted](https://user-images.githubusercontent.com/13896934/44302694-f2428b00-a2f3-11e8-8bde-12cace38d2c0.png)

If I manually rebuild the index in wallet repair, it fixes the alias db but I think it should do that automatically if it needs to recreate the directory but doesn't need to recreate the transaction database in blocks.  Maybe there is an easy and less time consuming way to repopulate the alias database.  I did not test the other directories like certificates, escrow, offers and assets so they might have the same issue.

I am using Syscoin v3.0.6.2-e50948b on Ubuntu 16.04 (64-bit) built from source.

**Comment by sidhujag** [comment]
quickest way is to reindex your node to get your alias db back. It will run through all transactions and recreate syscoin dbs from scratch

**Comment by justicegray** [comment]
Is this more of a feature request than a bug report?  I.e “if I manually tamper with the files for my domain objects, I want the recreation of them to happen automatically?”

**Comment by Keyare** [comment]
Closed. Deprecated version.
