### ISSUE TITLE
ERRCODE: 5505 - This alias already exists - Error code changed 

### ISSUE THREAD

**Issue by argvil19** [syscoin/syscoin#264]
Not sure if this was on purpose, but my app broke and i had no idea why. Found out the error code changed from 5506 to 5505. 

Was this on purpose or just a typo?.

**Comment by sidhujag** [comment]
We change the error codes once every few updates as new ones are added it pushes the older ones down.. we will need a better way to manage those error codes but they are generally sequential. Once we nail down the 3.1 release (today) then we will basically have a hardened set of error codes. Are you using the error codes for your application logic?

**Comment by argvil19** [comment]
I'm using them to identify the error responses im getting from CLI

**Comment by Keyare** [comment]
Closed. Deprecated version.
