### ISSUE TITLE
Syscoin 3.1 QT

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syscoin#270]
When running a rescan the progress indicator displayed does not change from 0 although in the debug log you can see that it is progressing

**Comment by keith34** [comment]
syscoin3.1.4 won't sync. says connecting to peers weeks behind with no progress after 24 hrs online?

**Comment by Keyare** [comment]
Backup your wallet.dat and masternode.conf files

1) Close Qt
2) Delete all data from syscoincore directory EXCEPT for wallet.dat and
masternode.conf
3)Restart Qt and let it resync

**Comment by Keyare** [comment]
Closed. Deprecated version.
