### ISSUE TITLE
Cannot send when coin control is disabled - "Insufficient funds" (BMD never installed on this machine)

### ISSUE THREAD

**Issue by bstr156** [syscoin/syscoin#279]
Syscoin QT 3.1.2

Inputs are **not** automatically chosen when Coin Control is disabled.  Instead, I get "Insufficient funds" error upon attempts to send.  On the other hand, when I enable Coin Control and choose my inputs, it works fine.  I tested this after troubleshooting the same issue with a user in Slack #help.

Note: Blockmarket Desktop has never been installed in this instance, nor has it interacted with my .syscoincore folder.  This is purely a Syscoin Core + QT install with recently cleared and regenerated databases.

**Comment by sidhujag** [comment]
are there other non 100k outputs in this wallet that are also not stored in an alias address?

**Comment by bstr156** [comment]
This particular wallet.dat does not have any associations with masternode collateral nor 100k TXs.  I do have entries in the masternodes.conf, but those collateral are held in a separate cold wallet.

**Comment by bstr156** [comment]
All TXs associated with this wallet.dat are not 100k, and all the SYS are held at alias addresses.

**Comment by sidhujag** [comment]
thats why.. working as designed.. it wont spend alias funds from under you. use aliaspay to spend from alias.
