### ISSUE TITLE
Persistent issue: QT 3.1.3 and 3.1.2 using Windows 10

### ISSUE THREAD

**Issue by 3-AR-3** [syscoin/syscoin#280]
![image](https://user-images.githubusercontent.com/31573485/45350846-ad390e00-b5ac-11e8-83c6-69e78b892162.png)

![image](https://user-images.githubusercontent.com/31573485/45351185-6e578800-b5ad-11e8-95b2-10c9e2a1be25.png)

After downloading and syncing 3.1.3 QT (sync worked fine, no issue) wallet becomes temporarily unresponsive. 

This occurred first when clicking on Masternode Tab in wallet UI. Then slowly recovers, and becomes responsive again so I attempt to click other tabs and, again, becomes unresponsive. This doesn't happen every time I'm selecting a tab, however has occurred with both 3.1.2 and 3.1.3. Had not had this issue at all with any previous versions of Sys QT. 

Attempted to attach two screen prints to show issue. One prtsc does show a tiny image of the wallet UI squashed in the top left hand corner of the screen. This has happened a few times. Other times just a black screen. Other times UI fully visible but frozen.

**Comment by johnp1954** [comment]
I am seeing this issue also on the last 2 QT releases where it becomes unresponsive and you have to wait. This happens randomly for me. However today I got this as well

![image](https://user-images.githubusercontent.com/16462796/45430648-bce44f80-b69d-11e8-8a3f-ab1c4a27bd05.png)

**Comment by Keyare** [comment]
Closed. Deprecated version.
