### ISSUE TITLE
Have a Fixed Funding Address for when creating a new alias

### ISSUE THREAD

**Issue by 1SPIRIT** [syscoin/syscoin#281]
Dear Team,

After creating a new alias please can you create the option to be able to edit the funding address and save it.

This helps keep control of accounting staying clean.

Currently there is no option to edit the alias funding address. I don't want my alias choosing randomly which address to deduct fees from especially if you have different entities on each alias.

Having control of where the funds are debited from helps clean accounting.

Thanks

**Comment by Keyare** [comment]
Closed. Deprecated version.
