### ISSUE TITLE
Can't start masternode QT sync stuck in seconds forever

### ISSUE THREAD

**Issue by skironDotNet** [syscoin/syscoin#282]
Something is generally not right I tried old syscoin 3.0 and still QT stuck in sync even when synced fresh BC from 0

Also syscoind always report this unfinished progress
2018-09-21 16:06:12 CMasternodeSync::ProcessTick -- nTick 19 nRequestedMasternodeAssets 0 nRequestedMasternodeAttempt 0 nSyncProgress -0.250000

![2018-09-21 10_59_44-syscoin core - wallet](https://user-images.githubusercontent.com/2981715/45892526-00ba1180-bd8e-11e8-9917-6b4a7b6fb980.png)

**Comment by Keyare** [comment]
You won’t be able to sync on 3.0.0 – You need to  run 3.1.3 and sync from scratch.
Make a backup of your syscoincore folder, then delete everything except wallet.dat and masternode.conf and sync to the chain.


Sent from Mail for Windows 10

From: Pawel Cioch
Sent: September 21, 2018 9:04 AM
To: syscoin/syscoin
Cc: Subscribed
Subject: [syscoin/syscoin] Can't start masternode QT sync stuck in secondsforever (#282)

Something is generally not right I tried old syscoin 3.0 and still QT stuck in sync even when synced fresh BC from 0

**Comment by skironDotNet** [comment]
The point was it was always working on v3.0.2.0 and then I updated and noticed that. Now tried again with v3.0.2.0 and I'm fully synced. I'll try now to switch to latest, and if problem exists then I'll try latest from 0

**Comment by skironDotNet** [comment]
Ok it worked when synced from 0 using latest and oldest client. Maybe just my data were corrupted.
Thanks, and sorry for false alarm
