### ISSUE TITLE
Allow usage of arrays while filtering in list commands

### ISSUE THREAD

**Issue by argvil19** [syscoin/syscoin#299]
I think it would be super useful that `list` commands accept arrays as input while filtering. Example: `listassetallocations` accepts the following filters:

```
{
      "txid":txid                                       (string) Transaction ID to filter.
      "asset":guid                                    (string) Asset GUID to filter.
      "receiver_alias":string                     (string) Receiver alias to filter.
      "receiver_address":string                (string) Receiver address to filter.
      "startblock":block                           (number) Earliest block to filter from. Block number is the block at which the transaction would have confirmed.
    }
```

I'm using `receiver_address` filter to get the total balance of a single asset. If i want to go through every alias/address and sum their balance, i would have to make a number of calls equal to the number of aliases/addresses in my wallet. Tried with a wallet with a lot of aliases and my PC blew up.

Passing an array of strings instead of a string would allow me to do only one call and solve the performance issue in my app.

**Comment by Keyare** [comment]
Closed. Deprecated version.
