### ISSUE TITLE
Wrong font in "From" column

### ISSUE THREAD

**Issue by mucalov** [syscoin/syscoin#3]
Should be aligned with the rest, seems like Courier New is used for this one.
![wrong_font](https://cloud.githubusercontent.com/assets/6578651/13403581/f8f0599a-df15-11e5-9868-f8991edb214a.png)

**Comment by sidhujag** [comment]
retest in latest

**Comment by sebastien1234** [comment]
@sidhujag looks like the font changed to the same, however the alias looks a tiny bit bigger by 1 or 2 points. see screenshot; it's hardly noticeable but still different if you look closely.

![image](https://cloud.githubusercontent.com/assets/7034589/13693466/7ab335aa-e719-11e5-9dfa-35dba42c79b8.png)

**Comment by sebastien1234** [comment]
@mucalov when you test the latest upcoming build, please check again, all font incompatibilities seem to be resolved. Please close #3 when you test again.
