### ISSUE TITLE
Performance issues while using syscoin-cli/syscoind in W10

### ISSUE THREAD

**Issue by argvil19** [syscoin/syscoin#300]
Even lightweight requests as `getinfo` would take 1-3 seconds depending on how many syscoin-cli calls are running at the moment. Performance seems to slow down when the number of syscoin-cli instances increases. For example, `listassetallocations` can take up to 16 seconds when there is other `listassetallocations` calls running. Take a look at this:

![image](https://user-images.githubusercontent.com/15952485/48167607-a126af80-e2c2-11e8-958d-fe960997dc72.png)

Performance inside QT seems to be normal, the problem only happens when using syscoin-cli.

Tried using OSX and performance seems to be much better than W10. Did not try other versions of Windows.

**Comment by sidhujag** [comment]
dont use cli for an app layer like you are doing. Do direct RPC calls. There is cors support no server needed in between. Using CLI requires connection overhead on each call.
