### ISSUE TITLE
Cannot open Blockmarket wallet 

### ISSUE THREAD

**Issue by jhmblvd** [syscoin/syscoin#303]
I cannot open Blockmarket. I have the password but it will not unlock. I get the error message in the attachnment 
Wallet Unlock Failed -1- CDB - Error 30974, can't open database wallet.dat. This is the older wallet 1.2.3 I have a backup of the wallet.dat.

I am using the correct wallet password it just won't open. Thanks

**Comment by Keyare** [comment]
Closed. Deprecated version.
