### ISSUE TITLE
How to upgrade SysCoin wallet?

### ISSUE THREAD

**Issue by SilkKheldar** [syscoin/syscoin#311]
I use on my PC wallet Syscoin Core version v0.13.2.0-71e929b (64-bit).
I see my Syscoins in this wallet but I have still "37 weeks behind" and "No block source available..." info.
What should I do to have control over my coins again?
I can install new version of wallet syscoincore-3.2.0.0 but how to move old "wallet.dat" with coins into new version?

**Comment by Keyare** [comment]
To upgrade from Syscoin 2.0 to Syscoin 3.x:
1. Use the OLD wallet to create a "DUMP" file
2. Import the "Dump" file into Blockmarket 3.2

Instructions: https://medium.com/@bittyjohn1954/syscoin-3-conversion-from-syscoin-2-579a8cf02603


To upgrade from Syscoin 3.0 to Syscoin 3.2:
If you have not upgraded to QT 3.2 please close your application first, then navigate to your syscoincore folder:

MAC: /Users/[USERNAME]/Library/Application Support/syscoincore

WINDOWS: C:\Users\[USERNAME]\AppData\Roaming\syscoincore

If you have already updated to QT 3.2 you do not need to delete data but you will need to reindex. Skip to Step #4 then Tools->Reindex Blockmarket. Else:

1) Make a backup of your wallet.dat and masternode.conf file in a safe place.
2) Within the syscoincore folder, delete everything except wallet.dat and masternode.conf (Masternode.conf is REQUIRED to lock your collateral within QT or BMD)
3) Install Blockmarket Desktop 3.2
4) Let Blockmarket 3.1.3 synchronize to 100%
5) Please check that your Blocks match that of the explorer (hover over blue 100% indicator to see.) https://chainz.cryptoid.info/sys/#
6) Check that debug.log is off. Go to Tools->Open syscoin.conf if there is not a line debug=0 then add it and save. Close and reopen BM.

**Comment by SilkKheldar** [comment]
Due to instruction I created dump file from my wallet in old syscoin application.   I installed Syscoin 3.2 and it&#39;s now fully synchronized.  But I can&#39;t find &#34;Wallet-Import&#34; options in any menu or screen. Where is it, or how to start this command?   I have a different location for &#34;data&#34; folder than default (&#34;c:/user/...&#34;) - selected in Syscoin 3.2 after first run. Does it count? Maybe I should move my dump wallet in specific location?  Thanks for help,   Tomasz   Dnia 21 lutego 2019 20:39 Brad Hammerstron &lt;notifications@github.com&gt; napisał(a):  To upgrade from Syscoin 2.0 to Syscoin 3.x:  Use the OLD wallet to create a &#34;DUMP&#34; file  Import the &#34;Dump&#34; file into Blockmarket 3.2  Instructions:  medium.com medium.com  To upgrade from Syscoin 3.0 to Syscoin 3.2:   If you have not upgraded to QT 3.2 please close your application first, then navigate to your syscoincore folder:  MAC: /Users/[USERNAME]/Library/Appl Support/syscoincore  WINDOWS: C:\Users[USERNAME]\AppData\Roa  If you have already updated to QT 3.2 you do not need to delete data but you will need to reindex. Skip to Step  github.com #4  then Tools-&gt;Reindex Blockmarket. Else:  Make a backup of your wallet.dat and masternode.conf file in a safe place.  Within the syscoincore folder, delete everything except wallet.dat and masternode.conf (Masternode.conf is REQUIRED to lock your collateral within QT or BMD)  Install Blockmarket Desktop 3.2  Let Blockmarket 3.1.3 synchronize to 100%  Please check that your Blocks match that of the explorer (hover over blue 100% indicator to see.)  chainz.cryptoid.info chainz.cryptoid.info  Check that debug.log is off. Go to Tools-&gt;Open syscoin.conf if there is not a line debug=0 then add it and save. Close and reopen BM.  —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

**Comment by SilkKheldar** [comment]
I&#39;ve managed by myself and import the dump walled via debug console.  Now I can manage my coins on new Syscoin 3.2. BTW: very nice help is included into debug console.  Thanks for help.   Best Regards,  Tomasz 
            
          
     
      
       
        Dnia 21 lutego 2019 20:39 Brad Hammerstron &lt;notifications@github.com&gt; napisał(a):
       
    
       
         To upgrade from Syscoin 2.0 to Syscoin 3.x: 
 
 Use the OLD wallet to create a &#34;DUMP&#34; file 
 Import the &#34;Dump&#34; file into Blockmarket 3.2 
 
 Instructions:  medium.com medium.com 
 To upgrade from Syscoin 3.0 to Syscoin 3.2:  
If you have not upgraded to QT 3.2 please close your application first, then navigate to your syscoincore folder: 
 MAC: /Users/[USERNAME]/Library/Appl Support/syscoincore 
 WINDOWS: C:\Users[USERNAME]\AppData\Roa 
 If you have already updated to QT 3.2 you do not need to delete data but you will need to reindex. Skip to Step  github.com #4  then Tools-&gt;Reindex Blockmarket. Else: 
 
 Make a backup of your wallet.dat and masternode.conf file in a safe place. 
 Within the syscoincore folder, delete everything except wallet.dat and masternode.conf (Masternode.conf is REQUIRED to lock your collateral within QT or BMD) 
 Install Blockmarket Desktop 3.2 
 Let Blockmarket 3.1.3 synchronize to 100% 
 Please check that your Blocks match that of the explorer (hover over blue 100% indicator to see.)  chainz.cryptoid.info chainz.cryptoid.info 
 Check that debug.log is off. Go to Tools-&gt;Open syscoin.conf if there is not a line debug=0 then add it and save. Close and reopen BM.

**Comment by Keyare** [comment]
Closed. Deprecated version.
