### ISSUE TITLE
Issue with 32bit ubuntu IsBlockValueValid: coinbase amount exceeds block subsidy schedule

### ISSUE THREAD

**Issue by Bill48105** [syscoin/syscoin#312]
Discussed & confirmed on syscoin #help on discord.  
3.0.4 worked fine. Tried to upgrade to 3.2 & ran into issues. Went thru various testing even starting with clean syscoincore data directory, coping working data directory from fully sync'd 64bit windows (didn't test 32bit windows), using pre-built 32bit binary vs building, etc.  With a fresh data dir it always dies at the same height.  Starting from a sync'd data dir copied over the error seems to be the last block sync'd on the other machine.

2019-02-15 18:37:57 ERROR: ConnectBlock(SYS): IsBlockValueValid: coinbase amount exceeds block subsidy schedule
2019-02-15 18:37:57 InvalidChainFound: invalid block=f71ba62a80918052dfb5265f8def39a176649044111a9e4c40ca4eb42534df17  height=175632  log2_work=86.42883625  date=2018-09-06 01:08:21
2019-02-15 18:37:57 InvalidChainFound:  current best=c9547d384a3847258b3c6a9cace02b9f0f9d75ff38779b75ba3f3a86863a3f43  height=175631  log2_work=86.42883421  date=2018-09-06 01:06:07
2019-02-15 18:37:57 ERROR: ConnectTip(): ConnectBlock f71ba62a80918052dfb5265f8def39a176649044111a9e4c40ca4eb42534df17 failed

**Comment by Keyare** [comment]
If 3.0.4 works fine then you shuould be able to upgrade to 3.2 easily. Use the 64 bit version.
1) BACK UP YOUR SYSCOINCORE FOLDER
2) Delete everything in the syscoincore folder except for wallet.dat and masternode.conf 
3) Install 3.2 and let it sync

**Comment by buzztiaan** [comment]
well the posted issue says that he was able to upgrade to 3.2 just fine, just that the isBlockValueValid() function doesn't allow all the blocks from 3.0.4 to work on a 32-bit system.

**Comment by locutus75** [comment]
Keyare, I reproduced the error as well. I believe there is an issue in the invalidateblock routine in 32bit

**Comment by Bill48105** [comment]
Thanks for the response Brad and yes I *SHOULD* be able to simply upgrade but as buzztiaan said I *was* able to upgrade from 3.0.4 but it refused to fully sync. As I mentioned in the OP I went thru all the hoops to get it working including starting fresh without success. I reached out to #help channel on syscoin discord & multiple people helped out including locutus who duplicated the issue on a fresh 32bit system. Pretty sure the errors are good clue as to what's broken. 32bit int overflow or something? Just reporting here for it to be looked into. Thx

**Comment by Keyare** [comment]
32Bit is not supported. I didn't catch this earlier, Sorry. Please use 64 bit.

**Comment by Bill48105** [comment]
LOL OK but perhaps that should be noted in the release notes.. Plus there are official 32bit binary releases ;)

**Comment by locutus75** [comment]
Bill uses the 32b version as a wallet, not for masternode setup.

**Comment by Keyare** [comment]
Yeah they shouldn't be there. we'll clean that up.

**Comment by Bill48105** [comment]
Ok thanks for clarifying. While 32bit may not be too common these days (seems I was 1st person to run into the issue which has existed awhile since I tried 3.1.4.0 which gives the same error but 3.0.4 worked fine) it sure does leave users in the lurch dumping 32bit especially unannounced which is kinda in bad form don't ya think

**Comment by Keyare** [comment]
Closed. Deprecated version.
