### ISSUE TITLE
Smaller screen (1366x768) support

### ISSUE THREAD

**Issue by Keyare** [syscoin/syscoin#32]
On smaller screens (My laptop is 1366x768)  the default wallet size does not show the bottom network activity icons and the window cannot be vertically resized. 
![untitled](https://cloud.githubusercontent.com/assets/7099087/13727444/a1979a50-e8a7-11e5-9529-57e7ccb24ee4.png)

**Comment by sidhujag** [comment]
@keyare hit the maximize button, if you goto aliases tab and buttons dissappear hit the minimze and maximize button again, does that work?

**Comment by ID453543435** [comment]
also need need supprt for 800x600 and 640x480 monitors

**Comment by dwasyluk** [comment]
We'll support all modern resolutions, same as what Bitcoin core supports. Most modern resolutions are defined as >=1024x768. If Bitcoin supports lower, so will we.
