### ISSUE TITLE
No Linux release for v4

### ISSUE THREAD

**Issue by Newar417** [syscoin/syscoin#336]
https://github.com/syscoin/syscoin/releases shows no Linux release file, as we used to have. Are Linux users expected to build from now on?

**Comment by ghost** [comment]
When is the eTA on a linux daemon? compiling the wallet every time an upgrade comes along is really not user friendly

**Comment by p3yot3** [comment]
More to the point, there's been 3 releases in the last 9 days FFS - stop using your users as guinea pigs & clearly state weather this wallet is the final, beta, alpha or whatever - if the wallet isn't ready then say so. What on earth are you playing at?

**Comment by locutus75** [comment]
Only 1 mandatory update (4.0.1); last update to 4.0.2 is not mandatory. Not uncommon to have more updates after a major release, so please don't overreact.

**Comment by juananzgz** [comment]
If you don't want to compile, you can try the win64.zip with wine. It works perfectly for me.

**Comment by p3yot3** [comment]
> 
> 
> Only 1 mandatory update (4.0.1); last update to 4.0.2 is not mandatory. Not uncommon to have more updates after a major release, so please don't overreact.

Wrong. v4.0.0 & v4.0.1 were mandatory. No doubt there will be another mandatory update again soon. Constantly releasing mandatory releases that are full of bugs is bad development & not user friendly. Releases should be tested fully before being publicly released, or marked clearly as beta.

**Comment by locutus75** [comment]
4.0 was a major release, not gonna count that as an update. Can you enlighten me as to why this is an issue for you at the moment? Because to me it looks like you are just bashing here for some reason you won't reveal.

**Comment by ghost** [comment]
I have no issues with the mandatory/non mandatory wallet updates, i believve that discussion should not be held here.

Windows + wine is not a scalable solution, that's a hotfix. The solution is a linux daemon release.

**Comment by locutus75** [comment]
Of course, and that will be released as well. I can check again what the projected release date will be.

**Comment by ghost** [comment]
That would be much apreciated, thanks

**Comment by rBurgett** [comment]
Mandatory updates aren't a problem as long as they provide wallets. The devs can't announce a mandatory wallet update then not provide Linux wallets.

**Comment by sidhujag** [comment]
@Newar417 linux builds are in 4.0.3 please try it in this release (non-mandatory)

**Comment by sidhujag** [comment]
4.0.3 should have linux binary, (x86_64). If you are on any other platform you should build yourself aswell as Geth which is a dependency. Replace the geth binary in the src/bin/linux directory. Also you will need to build the relayer using Pkg for your linux distro if pkg supports it: https://www.npmjs.com/package/pkg

relayer can be found here: https://github.com/syscoin/relayer

Again x86_64 relayer binary is already included in the src/bin/linux distribution of syscoin as well as Geth. So that one will work fine.

**Comment by rBurgett** [comment]
@sidhujag there is no version `4.0.3` in releases.

**Comment by p3yot3** [comment]
No, looks like it's been taken down because it doesn't work, again. This is what happens when devs throw wallets together & publish them as releases before testing them properly. What a shambles this "new" wallet release is.

**Comment by Keyare** [comment]
* This is not the place to post opinions and factual errors. They will be deleted.

**Comment by sidhujag** [comment]
It is in internal testing and will be released soon as sanity tests pass

**Comment by p3yot3** [comment]
@sidhujag Glad you took my advice & removed the buggy wallet for more development & testing before releasing it. It's disappointing that @Keyare deems it necessary to extend his censorship of the BCT thread over to github in an effort to hide my suggestion which was made in good faith & based on common sense.

**Comment by sidhujag** [comment]
4.0.3 released guys give it a try

**Comment by Newar417** [comment]
Thanks!

First I had to get libc / libc6 from the "experimental" repository to match a GLIBC version > 2.27.

It does load the splash screen, but then freezes at "Done loading". The debug log does not reveal anything particular, AFAICT:

https://pastebin.com/6gDj4rQQ

**Comment by sidhujag** [comment]
> Thanks!
> 
> First I had to get libc / libc6 from the "experimental" repository to match a GLIBC version > 2.27.
> 
> It does load the splash screen, but then freezes at "Done loading". The debug log does not reveal anything particular, AFAICT:
> 
> https://pastebin.com/6gDj4rQQ

ok thanks.. you must be on ubuntu 16 or below? ill take a look at getting glibc compatibility flag working which will fix it.

**Comment by rBurgett** [comment]
New version works great for me in Linux. Thanks!

**Comment by sidhujag** [comment]
> Thanks!
> 
> First I had to get libc / libc6 from the "experimental" repository to match a GLIBC version > 2.27.
> 
> It does load the splash screen, but then freezes at "Done loading". The debug log does not reveal anything particular, AFAICT:
> 
> https://pastebin.com/6gDj4rQQ

Can you try dev-4.x branch and try to build it, see if it works for you if possible? Make sure to do: 
[from syscoin github base directory]
```
cd depends
make
cd ..
./autogen.sh
./configure --enable-glibc-back-compat --prefix=`pwd`/depends/x86_64-pc-linux-gnu LDFLAGS="-static-libstdc++"
make (make -j4 or make -j8 depending on how many cores you have)
```

then you can do `ldd syscoind` and we can confirm it looks good if you post the result

**Comment by sidhujag** [comment]
If you haven't built yet, can you try the 4.0.3 release binary again we have replaced the shasums and the linux binary. It has been built with glibc compatibility and also we have used trusty to build the relayer (which depends on scrypt nodejs which uses glibc as well as part of the native bindings).

**Comment by Newar417** [comment]
>  you must be on ubuntu 16 or below? 

Latest Debian actually, sorry, should have mentioned that. 


> If you haven't built yet, can you try the 4.0.3 release binary again we have replaced the shasums and the linux binary. It has been built with glibc compatibility and also we have used trusty to build the relayer (which depends on scrypt nodejs which uses glibc as well as part of the native bindings).

Tried that as well, same result. I guess, I go with a persistent Ubuntu USB for now.

**Comment by sidhujag** [comment]
Can we try to fix it before you move on? Can you paste the error here and also the ldd syscoind output?

**Comment by sidhujag** [comment]
> > you must be on ubuntu 16 or below?
> 
> Latest Debian actually, sorry, should have mentioned that.
> 
> > If you haven't built yet, can you try the 4.0.3 release binary again we have replaced the shasums and the linux binary. It has been built with glibc compatibility and also we have used trusty to build the relayer (which depends on scrypt nodejs which uses glibc as well as part of the native bindings).
> 
> Tried that as well, same result. I guess, I go with a persistent Ubuntu USB for now.

did you get the error output?

**Comment by Newar417** [comment]
tl,dr: It works now!

Ran syscoind once, then QT and it works now. Still some errors in the log, so here it is (ignore the network errors, they are mine): https://paste.ee/p/ch9XS

```
ldd syscoind

	linux-vdso.so.1 (0x00007ffd81beb000)

	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f004b886000)

	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f004b87c000)

	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f004b6f9000)

	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f004b4e2000)

	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f004b321000)

	/lib64/ld-linux-x86-64.so.2 (0x00007f004c7fa000)
```


Two notes on the log:
`Syscoin Core version v4.0.2.0-290fe66e5 (release build)`
However, I do run the latest release (github: v4.0.3, ff63dc1), verified by hash sum.

I have no RPC password set. The only thing in the `syscoin.conf` is adress index=1

**Comment by sidhujag** [comment]
Ok so it was working and maybe you were not running the right syscoind? The ldd looks right so it shouldn’t have complained about boost with this one or gcc if built with compatibility mode. I will close this and see if you can reproduce your behaviour with this binary if you can please reopen.

**Comment by Newar417** [comment]
The syscoind was / is the latest one. I always make a separate folder and work from there.

I have now tried to run both by using `& disown`. Oddly, this works for syscoind, but not syscoin-qt.
