### ISSUE TITLE
Fusion

### ISSUE THREAD

**Issue by johnp1954** [syscoin/syscoin#337]
You are unable to set the DataDir that fusion uses, please allow the application to be started with the datadir switch as in QT and Spark.  QT uses '-datdir='  Spark uses'--datdir=' .

This will allow users whose Data is NOT stored on the C Drive to use it

**Comment by gaia** [comment]
is it `--datdir=` or `--datadir=` ??

**Comment by johnp1954** [comment]
Whoops
uses '-datadir=' Spark uses'--datadir=' .

**Comment by Keyare** [comment]
This should be in the Fusion repo. This functionality is now implemented and pushed to master https://github.com/syscoin/Syscoin-Fusion/commit/b3ab4c591bdac9ca60a89d5a236ff8bce94884c5
