### ISSUE TITLE
Inability to unlock wallet from OS shell CLI, if wallet encrypted in QT *after* importing v3 dump 

### ISSUE THREAD

**Issue by bstr156** [syscoin/syscoin#339]
Reproduction steps:

NOTE:  I understand unlocking a wallet in plaintext on OS shell is not exactly a security best-practice.  That said, it *should* work, but doesn't in this case.

1. Generate new wallet
2. Execute importwallet w/ Syscoin 3 dump
3. After import, encrypt wallet in QT
4. execute **`~/syscoin/src/syscoin-cli walletpassphrase <passphrase> 100`** (passphrase **rejected**!)
5. Within QT, open console.  execute **`walletpassphrase <passphrase> 100`** (passphrase **accepted**!)

**Comment by sidhujag** [comment]
Check your passphrase it might be invalid chars or escape sequences you need on cli vs qt

**Comment by sidhujag** [comment]
@bstr156 please reply or this issue will be assumed invalid

**Comment by bstr156** [comment]
Checking now

**Comment by bstr156** [comment]
Yes, that was the issue Jag!  Special character needed escape.  Closing!
