### ISSUE TITLE
Change reseller comment

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#34]
marketplace/search/resell offer:

Please change the text in Resell offer to:

"Enter mark-up or mark-down(negative amount) percentage amount(without the % sign). You cannot give more of a discount than the rebate you were provided to Re-sell."

![image](https://cloud.githubusercontent.com/assets/7034589/13731153/f8d9ac86-e938-11e5-82d6-f1255f4c7a3c.png)

**Comment by sebastien1234** [comment]
@sidhujag , Also, in this same form, the word "commission" should be revised as the number in question is not the actual commission but the mark-up or down number. Should be changed to "Affiliate Amount"  with the description I indicated? Not sure, I'm open to suggestions but commission is not accurate.

**Comment by Keyare** [comment]
I suggest making the label: 
Markup/Discount %: (no need to use the word affiliate)

And showing the new offered price beside it.
And simply NOT allowing a larger discount than the original merchant discount. Anything larger will default to maximum allowed.
![lp](https://cloud.githubusercontent.com/assets/7099087/13900918/466164e0-edcf-11e5-9413-07bc9c8b75f9.jpg)

**Comment by sebastien1234** [comment]
@Keyare I agree, with the below adjustment. @sidhujag the text on the 3/17 build currently indicates:

"Enter the percentage amount (without the % sign) that you would like to mark-up the price to" so it's not exactly what I requested, however I like @Keyare 's suggestion better with the % sign as he indicated so that it doesn't require a huge explanation and is intuitive. The only thing I think should be indicated in blue is "Use a negative number for discount. Discount cannot be lower than discount given to Affiliate."

And also as @Keyare mentioned, it should not allow us to resell at a lower discount than given, currently, it lets you do it but does not work.


![image](https://cloud.githubusercontent.com/assets/7034589/13905895/be0bb8dc-eea2-11e5-84e0-efdf2788a4dd.png)

**Comment by sebastien1234** [comment]
@sidhujag issue remains on 6/18 build, as indicated by @Keyare please see his picture above, if we can just have a box that says "markup/discount %" and indicate "Use a negative number for discount. Discount cannot be lower than discount given to Affiliate."

**Comment by sebastien1234** [comment]
@sidhujag it now appears that you are not able to markdown the price at all.

There's certainly many usecases for marking down the price. For example, Seller gives you a 10% discount to resell at, you give a 5% discount as that is the incentive to resell, giving a better deal than full price. 

![image](https://cloud.githubusercontent.com/assets/7034589/18418728/79a505a8-7819-11e6-96fd-6d9e23e605f7.png)

**Comment by sidhujag** [comment]
Whats the error msg or is there one?

**Comment by sebastien1234** [comment]
sorry @sidhujag check again above, was using vm and printscreen not working

**Comment by willyko** [comment]
Closing this as resell function has been scraped
