### ISSUE TITLE
false mn.conf parameter may cause qt4 to crash when initializing masternode

### ISSUE THREAD

**Issue by dan12133** [syscoin/syscoin#348]
When I set the mn.conf up i did a mistake and did not put the mn genkey instead i used the transacation id hash twice. 
This caused that qt4 crashed when trying to initialize the mn. Whenever you encouter problems like this, have a look at the mn.conf.

**Comment by sidhujag** [comment]
user error i believe, noone else has complained about this, the mn.conf is not dummy proof it is not really priority at the moment.
