### ISSUE TITLE
syscoin-cli masternodelist lastseen shows a wrong value

### ISSUE THREAD

**Issue by juananzgz** [syscoin/syscoin#354]
On sys3 it showed the number of seconds passed since the masternodes had been seen. On Sys4 it shows a value a little lower than the lastpaidtime value.
It can be seen easily at http://sysnode.info/masternode-check.html . The Last Payment and Last seen values are very similar.

**Comment by johnp1954** [comment]
Lastseen is the correct value, SYS4 changed the way pings etc where used and this is now the time you enter the winners list.

**Comment by juananzgz** [comment]
If this is correct, How can we see the time passed since a masternode has been seen. It's a really important data to know if there is any problem with your masternode. And lastseen seems the most descriptive command for that IMO.
So, if we see http://sysnode.info/masternode-check.html we can see that a masternode enters on the Winner List from 1 to 10 minutes after been paid. Is this correct?

**Comment by sidhujag** [comment]
lastseen is the most accurate time to know the last time a masternode has been seen. Yes 20 blocks before payment and until 10 blocks since payment your masternode should be actively pinging.

**Comment by juananzgz** [comment]
So it should be usually from 5 to 15 minutes. Now it usually shows that last time it has been seen is several hours before.
I understand this is a bug. Please check the link http://sysnode.info/masternode-check.html

**Comment by ced4SYS** [comment]
'Last seen' shows the time of the last ping.
It gets pinged every block while it is in the winners list, which means from 10 blocks before it gets the reward until 10 blocks after (1 block ~ 1 min).
Means 'Last seen' should be roughly 10 min (depending on actual block times) after 'Last paid' after the MN left the winners list.

**Comment by juananzgz** [comment]
Ok. This is how it is working now. I don't see it very useful, but then there is not a bug.
Then how can we see last time a ping was received (so, what lastseen showed in sys3). I think it's a very important value.

**Comment by ced4SYS** [comment]
It is not steady pinging anymore (like in V3), reducing traffic and freeing resources for higher tx throughput.
You can check "status" to see if there is something wrong.
You can check "pingretries".
If the MN is offline while it's in the winners list, the count is increasing. If it reaches 60, you need to restart and requalify.

**Comment by juananzgz** [comment]
Ok. Understood! Then all is ok. I will close the issue.
Thank you!
