### ISSUE TITLE
change my offer affiliates wording

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#36]
marketplace/selling/manage affiliates:

When choosing manage affiliates it opens a window called "my offer affiliates", should be changed to "Manage Affiliates"
![image](https://cloud.githubusercontent.com/assets/7034589/13731862/4bdaa410-e94a-11e5-96f0-d18061398540.png)

**Comment by Keyare** [comment]
![ma](https://cloud.githubusercontent.com/assets/7099087/13900410/9528e83a-edc2-11e5-85bd-c5668270ec67.jpg)
