### ISSUE TITLE
send tokens cps

### ISSUE THREAD

**Issue by nico1414** [syscoin/syscoin#362]
in spark i have error sending tokens (code 0)
and i dont have my cps adress (sys1..) in fusion but I ve an adress but I ve error segwit based adress to send cps

**Comment by sidhujag** [comment]
Need sys1 address to hold Cps

**Comment by nico1414** [comment]
I ve the same error
<img width="937" alt="Capture" src="https://user-images.githubusercontent.com/25005165/59935431-114b0580-944e-11e9-87a5-0576addc1b35.PNG">
<img width="202" alt="Capture2" src="https://user-images.githubusercontent.com/25005165/59935432-11e39c00-944e-11e9-9ea0-f3c29ab16e60.png">

**Comment by sidhujag** [comment]
do you have SYS on that address for gas fees

**Comment by nico1414** [comment]
Yes

Le sam. 22 juin 2019 à 02:15, jagdeep sidhu <notifications@github.com> a
écrit :

**Comment by sidhujag** [comment]
can you copy your address here so i dont have to look at the screenshot to copy it

**Comment by nico1414** [comment]
sys1q7ujr483xm6qx5ekyhugcjaprr5umpzk5z8l49l

**Comment by sidhujag** [comment]
allocation info:
{
  "asset_allocation": "135354521-sys1q7ujr483xm6qx5ekyhugcjaprr5umpzk5z8l49l",
  "asset_guid": 135354521,
  "symbol": "CPS",
  "address": "sys1q7ujr483xm6qx5ekyhugcjaprr5umpzk5z8l49l",
  "balance": 69195.03699670,
  "balance_zdag": 69195.03699670
}
address balance:
{
  "amount": 3.00000000
}

i see no problems on the core side. I was able to create an unsigned allocation send:
assetallocationsend 135354521 sys1q7ujr483xm6qx5ekyhugcjaprr5umpzk5z8l49l sys1q00x3h2y9xf7eu8cwe6zdetzdvjldud5f57efqm 2
{
  "hex": "08740000015a4323413b8315f919a421efc8425c3a6cb8a4df6d5b14883ce58cfd778536e401000000160014f7243a9e26de806a66c4bf118974231d39b08ad4ffffffff020000000000000000686a4c65995811080014f7243a9e26de806a66c4bf118974231d39b08ad40100147bcd1ba885327d9e1f0ece84dcac4d64bede368900c2eb0b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff1cc5f50500000000160014f7243a9e26de806a66c4bf118974231d39b08ad400000000"
}

Try to reindex and try again or sync from scratch.. id need to see what error code on the core its giving you.

**Comment by nico1414** [comment]
error again
07:22:39
￼
assetallocationsend 135354521 sys1q7ujr483xm6qx5ekyhugcjaprr5umpzk5z8l49l sys1qr6c2ea7cmesfquzjgh096j5s8pxgzm70zr8tw8 2


07:22:39
￼
{
  "hex": "08740000015a4323413b8315f919a421efc8425c3a6cb8a4df6d5b14883ce58cfd778536e401000000160014f7243a9e26de806a66c4bf118974231d39b08ad4ffffffff020000000000000000686a4c65995811080014f7243a9e26de806a66c4bf118974231d39b08ad40100141eb0acf7d8de6090705245de5d4a90384c816fcf00c2eb0b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff1cc5f50500000000160014f7243a9e26de806a66c4bf118974231d39b08ad400000000"
}

**Comment by sidhujag** [comment]
There’s no error though.. you can signrawtransactionwithwallet then sendrawtransaction and it should go through. If spark shows an issue it is a spark issue and we should see why that address has issue sending it doesn’t seem like a core issue

**Comment by nico1414** [comment]
if "signrawtransactionwithwallet hex" is correct

I ve an error after signrawtransactionwithwallet : _Witness program hash mismatch_

**Comment by nico1414** [comment]
I tried to import my address with cps but I see only
<img width="372" alt="sys" src="https://user-images.githubusercontent.com/25005165/60129622-bdb22200-9795-11e9-8ee5-38d66cb66343.PNG">

**Comment by Keyare** [comment]
Looks like a watchonly addess. Did you importaddress or importprivkey?
importaddress just imports a watch-only address.
importprivkey will import that actual address/private key

**Comment by nico1414** [comment]
Both

Le mer. 26 juin 2019 à 00:36, Brad Hammerstron <notifications@github.com> a
écrit :

**Comment by Keyare** [comment]
I think the 4.0.3 version of the wallet will address this.

**Comment by sidhujag** [comment]
im not sure it is, it seems like a bitcoin known issue around legacy NON HD addresses being imported in sys4 causing the bech32 addresses to seem valid.. @nico1414 can you try to do getaddressinfo and see if you own that address?

**Comment by sidhujag** [comment]
please post the getaddressinfo, specifically i want to know if your address is compressed (the legacy address) if you can do convertaddress and do getaddressinfo on the v3 address (hide your private key) that would be great.

**Comment by nico1414** [comment]
getadressinfo :
￼
{
  "address": "sys1q7ujr483xm6qx5ekyhugcjaprr5umpzk5z8l49l",
  "scriptPubKey": "0014f7243a9e26de806a66c4bf118974231d39b08ad4",
  "ismine": false,
  "solvable": false,
  "iswatchonly": true,
  "isscript": false,
  "iswitness": true,
  "witness_version": 0,
  "witness_program": "f7243a9e26de806a66c4bf118974231d39b08ad4",
  "pubkey": "045b96f7aa6840bf7f54fca614214cee2d22191c5835467e4f9efb324553894b1149c2e322e846c11880a94dcb310b11619f24ae87bee7bb042268a379ca3100f8",
  "label": "",
  "account": "",
  "ischange": false,
  "timestamp": 1525359060,
  "labels": [
    {
      "name": "",
      "purpose": "receive"
    }
  ]
}
and 
convertaddress

￼
{
  "v3address": "SjpmLTUcS1DycBUx1frYBisMEHt7vNFygQ",
  "v4address": "sys1q7ujr483xm6qx5ekyhugcjaprr5umpzk5z8l49l"
}                     
 and getadressinfo
address": "SjpmLTUcS1DycBUx1frYBisMEHt7vNFygQ",
  "scriptPubKey": "76a914f7243a9e26de806a66c4bf118974231d39b08ad488ac",
  "ismine": true,
  "solvable": true,
  "desc": "pkh([f7243a9e]045b96f7aa6840bf7f54fca614214cee2d22191c5835467e4f9efb324553894b1149c2e322e846c11880a94dcb310b11619f24ae87bee7bb042268a379ca3100f8)#6rw8vqrw",
  "iswatchonly": false,
  "isscript": false,
  "iswitness": false,
  "pubkey": "045b96f7aa6840bf7f54fca614214cee2d22191c5835467e4f9efb324553894b1149c2e322e846c11880a94dcb310b11619f24ae87bee7bb042268a379ca3100f8",
  "iscompressed": false,
  "label": "mné",
  "account": "mné",
  "ischange": false,
  "timestamp": 1525359060,
  "labels": [
    {
      "name": "mné",
      "purpose": "receive"
    }
  ]
}

**Comment by sidhujag** [comment]
ok you are on an uncompressed key, are you using your masternode key converted to bech32 as your CPS address?

**Comment by sidhujag** [comment]
please create a new bech32 address and post it here

**Comment by sidhujag** [comment]
I will need to add a function that was removed in bitcoin previously in order to add to wallet, please follow this guide to get your compressed private key: https://bitcointalk.org/index.php?topic=2689834.msg27503623#msg27503623

**Comment by nico1414** [comment]
it s ok. I ve my compessed private key but there isnt _addwitnessaddress_ in the syscoincore

**Comment by sidhujag** [comment]
yes Ive got to add that from previous bitcoin version.. I will add it to dev-4.x branch and get you to pull and build off of that..

**Comment by sidhujag** [comment]
@nico1414 can you try to pull dev-4.x branch?

For compressed private key you should importprivkey and then call convertaddresswallet passing in the sys1 address or the corresponding S legacy address, it will add the v4 address to your address book receiving list and also add the script. Make sure to also pass in a label in second param of convertaddresswallet so it saves the the key to your wallet.

**Comment by nico1414** [comment]
I m sorry but I dont know how to do

**Comment by sidhujag** [comment]
Call importprivkey on compressed private  key. If you still can’t sign then call convertaddresswallet with label passed in on the imported Address

**Comment by nico1414** [comment]
convertaddresswallet no exist in syscoin qt but I dont know to pull dev-4.x branch

**Comment by sidhujag** [comment]
is this issue resolved @nico1414 haven't heard from you, i will close this comment if you have any issue feel free to reopen or create a new one
