### ISSUE TITLE
Precision issue on bridge

### ISSUE THREAD

**Issue by sidhujag** [syscoin/syscoin#372]
Whoever can solve this problem with bitshifting/bitmasking first gets 50k SYS as bounty.

Description:
Precisions on Syscoin have a maximum of 8 decimal places. ERC20's can have much more and defaults to 18 decimal places.

Storage of values happens in uint256.

Value for example represents 18 decimal places on ethereum and stored for example 1234512345123451234512. This represents 1234.512345123451234512 but when it gets to Syscoin validation it won't fit within an int64 which is what Syscoin stores its values as. We need a way to convert the value to remove the decimal places and truncate decimal places to make it fit within an int64.

The validation code knows the precision of the opposing blockchain, for example on Syscoin validation I know that 1234512345123451234512 represents 18 decimal places with a whole value 1234 and decimal value of 0.512345123451234512. Syscoin precision is 8 decimal places. So we would truncate decimal value to 0.51234512 and store as 1234.51234512 which fits in an int64 as 123451234512.

We need an efficient way to take an uint256 and extract the value of 1234 as well as 0.512345123451234512 and then further truncate to 0.51234512 based on local precision. Bitmasking and Bitshifting likely will solve this so I prefer a solution without string manipulation if possible.

The following are operations permitted on the uint256:

    friend inline const base_uint operator+(const base_uint& a, const base_uint& b) { return base_uint(a) += b; }
    friend inline const base_uint operator-(const base_uint& a, const base_uint& b) { return base_uint(a) -= b; }
    friend inline const base_uint operator*(const base_uint& a, const base_uint& b) { return base_uint(a) *= b; }
    friend inline const base_uint operator/(const base_uint& a, const base_uint& b) { return base_uint(a) /= b; }
    friend inline const base_uint operator|(const base_uint& a, const base_uint& b) { return base_uint(a) |= b; }
    friend inline const base_uint operator&(const base_uint& a, const base_uint& b) { return base_uint(a) &= b; }
    friend inline const base_uint operator^(const base_uint& a, const base_uint& b) { return base_uint(a) ^= b; }
    friend inline const base_uint operator>>(const base_uint& a, int shift) { return base_uint(a) >>= shift; }
    friend inline const base_uint operator<<(const base_uint& a, int shift) { return base_uint(a) <<= shift; }
    friend inline const base_uint operator*(const base_uint& a, uint32_t b) { return base_uint(a) *= b; }
    friend inline bool operator==(const base_uint& a, const base_uint& b) { return memcmp(a.pn, b.pn, sizeof(a.pn)) == 0; }
    friend inline bool operator!=(const base_uint& a, const base_uint& b) { return memcmp(a.pn, b.pn, sizeof(a.pn)) != 0; }
    friend inline bool operator>(const base_uint& a, const base_uint& b) { return a.CompareTo(b) > 0; }
    friend inline bool operator<(const base_uint& a, const base_uint& b) { return a.CompareTo(b) < 0; }
    friend inline bool operator>=(const base_uint& a, const base_uint& b) { return a.CompareTo(b) >= 0; }
    friend inline bool operator<=(const base_uint& a, const base_uint& b) { return a.CompareTo(b) <= 0; }
    friend inline bool operator==(const base_uint& a, uint64_t b) { return a.EqualTo(b); }
    friend inline bool operator!=(const base_uint& a, uint64_t b) { return !a.EqualTo(b); }

so you have these operations to play with to manipulate the uint256 to extract values.

One way to extract the whole value for example in an inefficient way is: value / pow(10, x) where x=18 for the precision coming from the opposing blockchain. This will give 1234 correctly although a division and pow are not ideal.

**Comment by NoahMarconi** [comment]
`We need an efficient way to take an uint256 and extract the value of 1234 as well as 0.512345123451234512 and then further truncate to 0.51234512 based on local precision. `

Are these being stored differently (the whole values in one int64 and the decimals in a second int64)?

Quick answer is to divide by 10^10 to chop off the extra 10 decimals. The takes you from `1234512345123451234512` down to `123451234512`

**Comment by sidhujag** [comment]
cool! so if local precision < other blockchain's precision then value / pow(10, otherblockchainprecision-localprecision).

else if local precision > other blockchain's precision then value * pow(10, localprecision-otherblockchainprecision).

Sound about right?

**Comment by NoahMarconi** [comment]
That would do it. Depending on the delta you need to add or remove precision.

`123451234512  * (10^10)`  pads the uint256 with 10 Zeros: `1234512345120000000000` . 

`1234512345123451234512 / (10 ^ 10)` goes the other direction to strip out the trailing precision `123451234512 `.

There are ways to use bitshifting to optimize but your code is much more legible (and harder to make mistakes) using higher level multiplication and division.

For bitshifting you'd need a variant of the divide by 100 example: http://www.hackersdelight.org/divcMore.pdf

**Comment by NoahMarconi** [comment]
sys1qjsj8c96dg230eehz59c549rn0rejumlrv5xv3k

**Comment by sidhujag** [comment]
sent! 790a8cfe3c72fbc6a9f62d3d3ae3c4a9db0cd98d7b156ba93d92362ff6826c69
