### ISSUE TITLE
listassetindex: "ScanAssetIndex: failed, cannot read TXIDs of asset"

### ISSUE THREAD

**Issue by bstr156** [syscoin/syscoin#373]
Syscoin Core version v4.0.3.0-ff63dc15a

This execution uses JOHNP as the subject, an asset for which I know there have been transactions of various types including assetallocationsend.  I have attempted with other assets, with same result.  My syscoin.conf includes: 
_addressindex=1
assetallocationindex=1
txindex=1
assetindex=1_
Furthermore, the .ldb files for each of these appear to be populated.  I ran -reindex and the issue persists.  (FYI, assetinfo works).

(this execution follows the first example given in the help text for the command)
![Error_listassetindex](https://user-images.githubusercontent.com/6069215/65818051-6fb51c00-e1d3-11e9-9362-4ad783d82ed8.png)

Debug log:
"ScanAssetIndex: failed, cannot read TXIDs of asset"

**Comment by sidhujag** [comment]
ACK looks like a valid bug in the index probably something to do with paging

**Comment by bstr156** [comment]
Fix in dev-4.x has been validated.  Command now produces proper output without error.  Issue resolved.
