### ISSUE TITLE
Wrong token balance

### ISSUE THREAD

**Issue by SanShiner** [syscoin/syscoin#380]
My BEER token 1086616951 balance is 166.4 but correct is 0.65 
(4.0 daemon shows correctly)

**Comment by sidhujag** [comment]
@SanShiner need more details, what client is it wrong on, what is your OS and setup like?

**Comment by sidhujag** [comment]
@SanShiner pls update us here with more details

**Comment by sidhujag** [comment]
Will give this a couple days then will close due to inactivity
