### ISSUE TITLE
Cannot launch Geth in Rinkby mode

### ISSUE THREAD

**Issue by Keyare** [syscoin/syscoin#381]
Syscoin 4.1.0 RC4
Running on Syscoin Testnet with 
testnet=1
gethtestnet=1
addnode=54.203.169.179

Does not connect to Ethereum testnet.

Does connect to Ethereum Mainnet

**Comment by willyko** [comment]
What OS is this?

**Comment by Keyare** [comment]
WIN	10.0.18363 x64

**Comment by willyko** [comment]
Ah ok found the bug.  syscoin is not passing `--rinkeby` when launching geth

**Comment by sidhujag** [comment]
ACK

**Comment by sidhujag** [comment]
this was fixed in 62d570114f10deca77671e1337768c4c7b657b0b
