### ISSUE TITLE
QT Masternode sync status should indicate MNSYNC status.

### ISSUE THREAD

**Issue by Keyare** [syscoin/syscoin#387]
When starting QT, QT syncs, then masternodes sync, but this does not indicate mnsync status. 
There is NO UI indication of mnsync status. 
It looks like masternode syncing is done in the UI, but mnsync status takes up to 10 minutes longer. This causes user frustration because staring a MN returns "masternode syncing not complete" when the UI is showing that masternodes have synced (but has only done the first step).

**Comment by Blocknugget** [comment]
Said the same in channel few weeks back. Was told that Qt had to be as minimal as possible to keep inline with BTC. But BTC doesn't have masternodes tab! I'm sure this issue confuses a lot of people setting up their masternodes.
