### ISSUE TITLE
High CPU usage OR why no masternode without wallet?

### ISSUE THREAD

**Issue by skironDotNet** [syscoin/syscoin#388]
Running Syscoin 4.1.2 and it has supper high CPU usage, while I think 4.0.3 was super calm for months. I don't remember what was the last version I used :( but recent Syscoin 4.1.2 is definitely poor.

Can anybody review the code?

**Comment by sidhujag** [comment]
4.1.2 fixed the CPU issue, perhaps its sysgeth.nod with high CPU? that is a known issue (https://github.com/ethereum/go-ethereum/issues/20464) but the Syscoin Core one was fixed https://github.com/syscoin/syscoin/issues/382.

Ensure your not running 4.1.0 which had the CPU issue on Syscoin Core then dbl check what is causing the CPU (which process)

**Comment by skironDotNet** [comment]
Thanks for quick reply. looks like syscoind
![image](https://user-images.githubusercontent.com/2981715/72410980-74c0bb80-372f-11ea-86d0-00bd37bff181.png)

UPDATE
but ignore this result for now, as it's not fully synced yet, I just realized "2020-01-15T06:39:48Z AcceptConnection -- masternode is not synced yet, skipping inbound connection attempt"

**Comment by sidhujag** [comment]
Can you also show me output of getblockchaininfo?

**Comment by skironDotNet** [comment]
```
{
  "chain": "main",
  "blocks": 330210,
  "headers": 330210,
  "bestblockhash": "9a9ea69d2dda9f9465b9cabb955cd6b14ded835a659e638942bce57c0eef2849",
  "difficulty": 250336976098.7089,
  "mediantime": 1579112102,
  "verificationprogress": 1,
  "initialblockdownload": false,
  "chainwork": "0000000000000000000000000000000000000000009ff538bee9aaf241448f37",
  "size_on_disk": 515161058,
  "pruned": false,
  "geth_sync_status": "synced",
  "geth_total_blocks": 9287313,
  "geth_current_block": 9287313,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 1
    },
    "bip66": {
      "type": "buried",
      "active": true,
      "height": 1
    },
    "bip65": {
      "type": "buried",
      "active": true,
      "height": 1
    },
    "csv": {
      "type": "buried",
      "active": true,
      "height": 1
    }
  },
  "warnings": ""
}

```

**Comment by skironDotNet** [comment]
I think the issue I had was because my own compilation --without-wallet as I had no barkley DB dependency found.
I recompiled with --with-incompatible-bdb so all RPC commands now available to check MN status etc. and CPU usage seems to OK avg 2.5% with ups and downs, but that's normal.

Sorry for raising the panic.

**Comment by sidhujag** [comment]
What OS are you using that you need incompatible bdb? Are you saying without-wallet it will cause CPU issue?

**Comment by skironDotNet** [comment]
I compile on Ubuntu 16.04 but XUbuntu flavor to to be exact, and run on VPS with Ubuntu Server 16.04

> Are you saying without-wallet it will cause CPU issue? 

haven't tested 2nd time, but this is what happened, but Also I think the code for RPC is wrong. Why would I need wallet to check masternode status, that should be independent, so some of RPC calls are intermingled with wallet functionality part 

![image](https://user-images.githubusercontent.com/2981715/72625569-9f1c9f80-390e-11ea-897b-4ee0ad2ca148.png)

**Comment by sidhujag** [comment]
@skironDotNet thanks for the issue regarding wallet, I did a lot of work to make all of those calls compatible with disabling wallet and those ones were conflicting, however on closer look it should be included if wallet is disabled simply certain functions of the calls are going to be missing rightfully.

Regarding getauxblock, it is only valid in wallet mode, cross-referencing Namecoin it also enforces this.. during creation and submission it references wallet, so you cannot call that with wallet disabled

**Comment by sidhujag** [comment]
@skironDotNet if you want to try dev-4.x branch, the masternode stuff should be fixed with disable-wallet
