### ISSUE TITLE
Confusing message for reseller error.

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#39]
Try to resell an offer and you do not own Alias that allows transaction, you get the following message:

Error creating new linked offer: "Error: The transaction was rejected! Alias inputs were invalid"

![image](https://cloud.githubusercontent.com/assets/7034589/13906354/96fe23bc-eeaa-11e5-9f1f-480ee098ec12.png)

Instead the message should say:

"Unable to Resell an exclusive offer without owning an Affiliate Alias"

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
