### ISSUE TITLE
auxfees bug

### ISSUE THREAD

**Issue by sidhujag** [syscoin/syscoin#390]
I've entered:
"fee_struct":[["0","0.01"],["10","0.004"],["250","0.002"],["2500","0.0007"
Attempting to simulate fee structure required above.

Resulting fees on test cases:
10 = 10.01 (correct)
3000 = 3007.66 (should be 3005.91)
6 = 6.06 (correct)
20 = 20.14 (correct)
250 = 251.06 (correct)
500 = 501.56 (correct)
1250 = 1253.06 (correct)
2500 = 2507.31 (should be 2505.56)
7500 = 7510.81 (should be 7509.06)

auxfees not showing properly, seems last bound is used twice 

should be (10*0.01)+(240*0.004)+(2250*0.002)+(500*0.0007)=5.91 for 3000 but it adds another (500*0.0007).

**Comment by Keyare** [comment]
Retested and confirmed fixed
