### ISSUE TITLE
assetupdate fails to update [contract] despite current update_flags = 31

### ISSUE THREAD

**Issue by bstr156** [syscoin/syscoin#404]
`assetupdate "490411102" "Test Interchain Token" "419D0d8BdD9aF5e606Ae2232ed285Aff190E711b" "0" "31" {} ""`

sign + send.  Transaction confirms fine.  However, [contract] fails to update. In my probing I found [public_value] **does** update as expected. I do not see [contract] included in the systx raw transaction data. Is its absence a bug? 

**Expected behavior**
[contract] should update

**Actual behavior**
![image](https://user-images.githubusercontent.com/6069215/81458395-cc13ed00-915f-11ea-8d3f-04d744cbc04c.png)

decoded raw tx:
![image](https://user-images.githubusercontent.com/6069215/81458327-70496400-915f-11ea-92c5-55fb4bbaf98a.png)

tx confirms and...  [contract] does not update as it should, but [public_value] does.

**To reproduce**
Easy to reproduce, and I have done so repeatedly. Just submit the assetupdate tx shown above.

**System information**

![image](https://user-images.githubusercontent.com/6069215/81458485-39278280-9160-11ea-8490-542655a68ed8.png)

self-compiled on Ubuntu 18.04.4 LTS, Intel Core i7, SSD

I could not find any errors in debug.log w/ debug = 1.

**Comment by bstr156** [comment]
One piece I left out:
The reason I'm updating [contract] is because I accidentally included the leading 0x when I created the asset. Just think you should know in case I created some kind of field overflow related issue.

**Comment by bstr156** [comment]
ALSO, wondering if this might be related to the addition of auxfees, because I don't see any bitmask description for that new field in the update_flags help text. Did bitmasks get offset/misaligned? Just speculation.

**Comment by bstr156** [comment]
Created a new SPT w/ proper contract address (40 char).  Now I realize that "0x" is added automatically, so I can't legitimately tell whether contract is updating or not. It might be.  All I know is when I try to use Asset Registry for the original asset, I get a contract error.  Will post that next time I come across it.

**Comment by sidhujag** [comment]
the 0x should be stripped out when you pass in rpc data, the asset registry tx should be the tx that updates the contract did you use assetnew or assetupdate for the registry?

**Comment by sidhujag** [comment]
from your decoded tx looks like the contract field doesnt have anything, was there already a contract with that address defined for that asset?

**Comment by sidhujag** [comment]
you can see the first tx you did https://sys1.bcfn.ca/tx/6f74b6d009713710e8cecfd38fbc4fc5c63b9a0ea59a299d601d8a5ce4a6e775 already had that same contract, so the contract field already had that address, and thus your contract address was not set because theres nothing to set its the same

**Comment by bstr156** [comment]
Are you saying the 0x is automatically stripped out if it's passed by the user? Help text gave me the impression I would have to limit to 40 chars, hence my attempt to "correct" it after the fact...  and [contract] absence from the systx when attempting to do so. That makes sense.

I was trying to Register the asset using assetupdate tx (which lacked contract because already defined).  NO WONDER it wasn't working. Just submitted the assetactivate tx to Registry and it worked!  There is now some FUN in the Manager contract :)  https://etherscan.io/tokenholdings?a=0xFF957eA28b537b34E0c6E6B50c6c938668DD28a0

**Comment by sidhujag** [comment]
@bstr156 yup so wallets are expected to pass in the data and not empty, empty will attempt to clear data.. its kind of weird but it works because we dont want to include the payload on every tx we only want to include it if its changing so consensus code can catch it and update.. if you pass in data and it matches database it will set payload to empty for that field (no-op which is what happened to you)

**Comment by bstr156** [comment]
Jag helped me understand what was going on.  Not a bug.  Closing.
