### ISSUE TITLE
masternodelist activeseconds returns 0 for nodes in grace period

### ISSUE THREAD

**Issue by einalex** [syscoin/syscoin#405]
`masternodelist activeseconds` returns 0 for nodes in grace period.
**Expected behavior**
`masternodelist activeseconds` returns the same value as `masternodelist json` does in the `activeseconds` field, the number of seconds since the node has been initialized.

**Actual behavior**
`masternodelist activeseconds` returns 0 for nodes in grace period.

**To reproduce**
1. initialize a masternode
2. run `masternodelist activeseconds [node_ip]`
3. run `masternodelist json [node_ip]`
4. notice the discrepancy

**System information**
running 4.1.3 binary downloaded from github releases page.

Confirmed by two people:
https://support.syscoin.org/t/masternode-started-successfully-but-activeseconds-is-0/92/4

**Comment by sidhujag** [comment]
NA on evo release
