### ISSUE TITLE
Resold offer bug "My purchases"

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#41]
When a seller has someone reselling an offer and it becomes concluded, the offer shows in "Sold" and "My purchases" as well (at the markup/down price).

This is obviously not one of the sellers purchases so should not be in "My purchases" but should also be in a separate tab as "Offers sold by your Affiliates" and not be in sold at all. In that window, it should indicate the price the offer was sold at, and the total amount that comes back to the original seller.

This is the original seller's "My Purchases" screen.
Currently when being an affiliate re-seller, 
![image](https://cloud.githubusercontent.com/assets/7034589/13907582/dc59a3b0-eec7-11e5-872b-970afafbc647.png)

**Comment by sebastien1234** [comment]
This also happens in the affiliates "My purchases" and "Sold", should be a tab that says "My Re-Sold Offers"

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
