### ISSUE TITLE
[v4.2.0rc5] Discard Blocks option in Welcome Wizard broken

### ISSUE THREAD

**Issue by beirut-boop** [syscoin/syscoin#416]
If you select this on first start wizard:
![image](https://user-images.githubusercontent.com/78885860/107592340-03db2400-6c0d-11eb-9408-63184e6d7442.png)

You get this problem:
![image](https://user-images.githubusercontent.com/78885860/107591960-130da200-6c0c-11eb-9c89-782d1d669afe.png)

Wallet exits and shows the same error + exit on every start.

**Expected result**

Any wizard toggle to not result in permanent error message.

**Solution**

The option should be removed from the wizard if it no longer works, or should be fixed in order to work with the relevant flags.

The flag could be auto-disabled in stead of wallet exiting.

**System information**

Windows 10 x64
v4.2.0rc5 tagged release

**Comment by sidhujag** [comment]
@beirut-boop are you able to rebuild from latest and give it a try

**Comment by beirut-boop** [comment]
I'm not having a good time trying to cross compile on my system. Is there a docker command installing exact correct package versions for cross compiling to Windows?

**Comment by sidhujag** [comment]
> I'm not having a good time trying to cross compile on my system. Is there a docker command installing exact correct package versions for cross compiling to Windows?

Hmm it should be straight forward, are you building your depends folder? Which part is it stuck at.

Note if you are building windows, you should build in linux not on the subsystem its easiest to setup a virtual box with ubuntu18 or 20 and build on that following the directions https://github.com/syscoin/syscoin/blob/dev-4.x/doc/build-windows.md#cross-compilation-for-ubuntu-and-windows-subsystem-for-linux

**Comment by sidhujag** [comment]
Install the mingw-w64 cross-compilation tool chain:
$ sudo apt install g++-mingw-w64-x86-64

Ubuntu Bionic 18.04 <sup>[1](#footnote1)</sup>:
$ sudo update-alternatives --config x86_64-w64-mingw32-g++ 
# Set the default mingw32 g++ compiler option to posix!

Compile the dependencies for Win64
$ cd depends
$ make HOST=x86_64-w64-mingw32  -j$(nproc) -pipe

Compile
$ cd ..
$ ./autogen.sh         # not required when building from tarball
$ CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --disable-debug --disable-tests --disable-bench
$ make clean
$ make -j$(nproc) -pipe
$ make deploy
Strips the files and deploys them into $PWD/release

**Comment by beirut-boop** [comment]
Thank you @sidhujag. I have compiled the latest version and the issue is no longer occurring.
