### ISSUE TITLE
[v4.2.0rc5] Testnet configuration is ignored.

### ISSUE THREAD

**Issue by beirut-boop** [syscoin/syscoin#417]
When the app is run in `-testnet` mode, it creates a testnet `QSettings` using `QAPP_APP_NAME_TESTNET`.

This is by design, so mainnet and testnet can exist om same computer. Options such as `strDataDirSyscoin` can be specified to use different datadirs.

**Expected behavior**

When Qt client is run with the `-testnet` command line argument, use the settings from `QAPP_APP_NAME_TESTNET`.

**Actual behavior**

The settings from `QAPP_APP_NAME_DEFAULT` are used in stead.

As a workaround, devs append hardcoded `testnet3` to the mainnet value read from `strDataDirSyscoin` setting. This is wrong, because it should use the `{QAPP_APP_NAME_TESTNET}/strDataDirSyscoin` value in stead. This value should have `testnet3` or `Syscoin-testnet3` as the default, rather than an append on the mainnet settings.

The problem probably starts here:

https://github.com/syscoin/syscoin/blob/55ed9f2011f3e7ebe2881dbd1739d551ebf0c49c/src/qt/syscoin.cpp#L522-L527

Because `QAPP_APP_NAME_DEFAULT` is hardcoded while the actual settings key name is now tucked away in `NetworkStyle`:

https://github.com/syscoin/syscoin/blob/55ed9f2011f3e7ebe2881dbd1739d551ebf0c49c/src/qt/networkstyle.cpp#L14-L24

**To reproduce**

Change testnet settings in the relevant location (on Windows it's the registry) and see how the setting is ignored.

![image](https://user-images.githubusercontent.com/78885860/107593174-08a0d780-6c0f-11eb-8ab8-d7c490d54099.png)

**System information**

Windows 10 x64
v4.2.0rc5 tagged release

**Comment by sidhujag** [comment]
check this commit @beirut-boop 
https://github.com/syscoin/syscoin/commit/0b7800527b206011a206be22e19c28628c5d192f

This look ok? We can remove that hack now

**Comment by cydg** [comment]
You know you are talking about a std btc design, right?
And noone is digging in the registry to change the data dir. What about other systems like Linux, Mac?
Data dir is a command line option. You can choose a different data dir there.
If the tree in data dir would be the same for mainnet and testnet you would run the risk to overwrite mainnet data with testnet data and your coins would be gone. So using an own subdir for testnet avoids that problem.
Configuration details are set in the conf file and it has separate sections for mainnet and testnet.

**Comment by beirut-boop** [comment]
@sidhujag commit is fine, but it doesn't seem to address the issue.

I believe the most concise summary is this:

* Running `syscoin-qt.exe -testnet` for the first time creates a QSettings (e.g. Windows Registry directory) with default settings specifically for testnet.
* These settings are ignored and mainnet settings are used in stead.

I am not sure where exactly the QSettings appName is defined, but in essence right in the beginning (when writing the defaults) the app name is `QAPP_APP_NAME_TESTNET`, yet later (when reading the settings) the app name changed to `QAPP_APP_NAME_DEFAULT`.

I _think_ this is because the AppName is stored in `NetworkStyle` which should be referenced, but in stead it is ignored and DEFAULT is used when looking for QSettings:

https://github.com/syscoin/syscoin/blob/55ed9f2011f3e7ebe2881dbd1739d551ebf0c49c/src/qt/syscoin.cpp#L522-L527

Line 527 might need something like this:

```diff
 /// 3. Application identification 
 // must be set before OptionsModel is initialized or translations are loaded, 
 // as it is used to locate QSettings 
 QApplication::setOrganizationName(QAPP_ORG_NAME); 
 QApplication::setOrganizationDomain(QAPP_ORG_DOMAIN); 
- QApplication::setApplicationName(QAPP_APP_NAME_DEFAULT); 
+ QApplication::setApplicationName(networkStyle->getAppName());
```

**Comment by sidhujag** [comment]
@beirut-boop it is consistent with Bitcoin, does the problem happen on Bitcoin?

I believe the logic you are describing happens here: https://github.com/syscoin/syscoin/blob/55ed9f2011f3e7ebe2881dbd1739d551ebf0c49c/src/qt/syscoin.cpp#L591

It will use testnet there and set app name, if its happening in Bitcoin as well we can open a PR to fix upstream. If what you are saying is true then it locates wrong QSettings and later changes the name after QSettings are already loaded with default regardless of testnet settings. Perhaps its not desired but we can ask upstream as intended behavior in that case.

My guess is params isn't available at the time of the first call and thus its working as designed and we don't have enough information to load QSettings with testnet in line 527.

Note: comments do say it will use QSettings from the new configuration after QApplication::setApplicationName(networkStyle->getAppName()); is applied on L594

**Comment by beirut-boop** [comment]
@sidhujag commented:
> @beirut-boop it is consistent with Bitcoin, does the problem happen on Bitcoin?

You are correct. I just tested this. The exact same behavior. Didn't know this. Never used Bitcoin Qt.

**Comment by sidhujag** [comment]
> @sidhujag commented:
> 
> > @beirut-boop it is consistent with Bitcoin, does the problem happen on Bitcoin?
> 
> You are correct. I just tested this. The exact same behavior. Didn't know this. Never used Bitcoin Qt.

Why don't you open one upstream and ask them the intended behaviour and perhaps if it is a real bug or not

**Comment by beirut-boop** [comment]
I've written my observations upstream: https://github.com/bitcoin/bitcoin/issues/21154
Let's wait and see which was the intended behavior.

**Comment by sidhujag** [comment]
@beirut-boop please post your syscoin address for a tip

**Comment by Redsandro** [comment]
`sys1q96dtuwxhuka6pe9un3tchtataahr3jurcz95qs`

**Comment by beirut-boop** [comment]
`sys1q96dtuwxhuka6pe9un3tchtataahr3jurcz95qs`

**Comment by sidhujag** [comment]
@beirut-boop seems like not an issue according to upstream

**Comment by beirut-boop** [comment]
@sidhujag at least not an issue with any kind of urgency.

But definitely an issue of sorts. Confirmed in [2016](https://github.com/bitcoin/bitcoin/issues/8106)(!). You can see what went wrong when following the logic:

1. Someone made an interesting separation of configs
2. Someone broke it (or never finished it)
3. Someone monkey-patched testnet into mainnet data dir

It works and anyone working with testnet for the first time will trash their mainnet data a maximum of 1 times and never again, so it's probably not worth fixing.

I will close this issue to keep the tracker clean.
