### ISSUE TITLE
TX size warning

### ISSUE THREAD

**Issue by Keyare** [syscoin/syscoin#419]
If a user tries to send a year's worth of masternode rewards to a new address (usually over 10k sys) there is no warning that the tx will be too big and the user will have to zap wallet tx's / clear mempool. 
This is a support issue that could be mitigated with a warning "Transaction size in kilobytes [Xkb] is too large, please select fewer inputs. "

**Comment by sidhujag** [comment]
related to https://github.com/bitcoin/bitcoin/pull/20536?
