### ISSUE TITLE
Reselling offer should allow you to change the title

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#43]
Currently you can only change the description of an offer you are reselling, you should be able to change the title. Use-case, various types of advertising targeting different keywords.

![image](https://cloud.githubusercontent.com/assets/7034589/13908618/b1f4c61c-eedc-11e5-8ca2-10910634ec5d.png)

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
