### ISSUE TITLE
protx_register_prepare bug rpc/util.cpp:575

### ISSUE THREAD

**Issue by BlownAway0** [syscoin/syscoin#432]
Trying to complete the prepare tx to register masternode with V4.2.0 on Windows 8.1 yields the following:

rpc/util.cpp:575 (HandleRequest)
Internal bug detected: 'std::any_of(m_results.m_results.begin(), m_results.m_results.end(), [ret](const RPCResult& res) { return res.MatchesType(ret); })'
You may report this issue here: https://github.com/syscoin/syscoin/issues
 (code -1)

**Comment by sidhujag** [comment]
Pls try the latest

**Comment by BlownAway0** [comment]
Thanks @sidhujag, it's working now.
