### ISSUE TITLE
Bounty: Break my proposal for the first trust-less swap mechanism without liveness assumption of seller using UTXO asset model

### ISSUE THREAD

**Issue by sidhujag** [syscoin/syscoin#435]
I have a proposal on how to make a trust-less custody-less swap without liveness assumptions on the sellers part. Todays NFT market places for example like openseas leverage the allowance feature of erc20/erc721 makes it possible to sell the NFT even if the seller is offline when a buyer appears. A non-interactive custody-free mechanism for UTXO asset swaps is desired for obvious reasons to avoid custody of assets and yet does not exist yet AFAIK.

Users are **A = seller**, **B = luxy** or some NFT marketplace that is assumed to be online to facilitate trades and **C = seller**. We are removing the liveness assumption away from the seller. There is an existing liveness assumption on the platform such as luxy which remains unchanged and is assumed to be fair given that luxy or an asset exchange marketplace runs a UX that is centralized through a domain registration that is also part of the centralized namespace mechanism of the internet (until we have decentralized name spacing through IPNS or the like) we can assume the website showing the trades is centralized in the short/medium term (this might change on zkRollups on our NEVM platform with L2 based DEX's storing full orderbooks and p2p trades directly). The idea here anyway is a ternary atomic swap A->B->C where two transactions are created A->B and B->C at separate moments.

The process is as follows:

Seller A would want to sell her NFT or asset in exchange for SYS or another asset, lets use SYS in this example. She creates a transaction in Syscoin, keeping in mind that you can send multiple SPT or SYS outputs in a single transaction:
Transaction1:
A->B Output1= Send NFT to B - Signed by A
          Output2= Send SYS to A - Unsigned

A signs the transaction, knowing that the only way for it to be valid is if she gets the SYS in return for the asset.

The transaction is saved as **Transaction1** and trade is posted on luxy.

A buyer appears and creates:

Transaction2:
B->C Input Tx1.Output1, Tx1.Output2
          Output1=Send NFT to C - Signed by B

Luxy signs Output1 of Transaction2, knowing that the only way for it to be valid is if someone signs Transaction1 Output2 as Transaction2 depends upon Transaction1. Luxy would ensure that Output1 and Output2 of Transaction1 are used as inputs to Transaction2 to ensure this dependency.

C then gets Transaction2 from luxy and verifies the dependency and that high enough fee rate was used for quick confirmation, knowing that the only way for the trade to be valid is if she signs Transaction1 Output2, meaning if she doesn't sign nothing happens and if she does sign she receives the NFT in exchange for the SYS requested by the Seller(A).

For simplicity we left out fees/commission/royalties as its easy to bake those in once the protocol is confirmed to work. To enforce royalties, luxy would only sign Transaction2 if Transaction1 also sent some amount of SYS to B in a separate output.

Will offer $5000USD in SYS at the time of claim if anyone finds a fault in the above protocol which makes it not possible to do in an atomic way due to incentive issues/attack vectors.

Edit: disclosure, after thinking some more there is a reorg concern around tx2 not confirming and giving chance for luxy (B) to respent the NFT, the chances of it are remote but it is a disclosed issue we can try to see through some secret preimaging if we can solve. The double-spending luxy will have to wait for mempool inclusion of tx2 and tx1 before trying to double-spend. They would have to 51% bitcoin to do this and so it would have to be of high enough value. In cases where NFT's are high value > $1m or more you can always do a more interactive A->C direct swap.

Edit2: There is a regulatory risk as onchain luxy might look like a custodian even though the chronological action preempts them from being custodian and unscrupulous blockchain analyst at government may classify it as a custodian requiring licenses to operate. It is highly unlikely luxy would ever be able to own the NFT for its own purpose as its an atomic process, but on chain it does look like its transferred to luxy and then to buyer.

**Comment by bondcoder97** [comment]
I see possible problem with balance locking in this scheme.
Users can not guarant that balances will be constants during this scheme. 
One from members of this model can spent start sum while transactions is not broadcasted to the network and all chain of transactions will be crashed. What do you think about it? It seems that multisig for this purpose will be more reliable.

**Comment by sidhujag** [comment]
Sorry balance locking? It is UTXO based and so there is a chain of UTXO's that are created which means they have to be spent in order. I think there is a reorg issue (something that maybe is negated with chainlocks) and a regulatory risk that onchain it looks like a custody solution even though it is not.

**Comment by bondcoder97** [comment]
> Sorry balance locking? It is UTXO based and so there is a chain of UTXO's that are created which means they have to be spent in order. I think there is a reorg issue (something that maybe is negated with chainlocks) and a regulatory risk that onchain it looks like a custody solution even though it is not.

I understand that UTXO model protected from double spent. But as I understand transaction is not broadcasted to network during all process and UTXO in this time are not locking. It looks like A can do something with own assets (or SYS) while transaction chain is not sent to the network. Excuse me, if I made some blockchain work principle mistake.

**Comment by sidhujag** [comment]
> > Sorry balance locking? It is UTXO based and so there is a chain of UTXO's that are created which means they have to be spent in order. I think there is a reorg issue (something that maybe is negated with chainlocks) and a regulatory risk that onchain it looks like a custody solution even though it is not.
> 
> I understand that UTXO model protected from double spent. But as I understand transaction is not broadcasted to network during all process and UTXO in this time are not locking. It looks like A can do something with own assets (or SYS) while transaction chain is not sent to the network. Excuse me, if I made some blockchain work principle mistake.

Yes so B and C both can verify that the input is set as not replaceable, meaning at any time once its fully signed if A tries to double spend he won't be allowed and if it did double-spend then the deal is off anyway since B and C would know that the input isn't available anymore before the process completes. A will not know when B and C interact and so has no idea when the transaction will be broadcast and so when it does it will be too late as his input will be labelled as non-RBF and rejected if he were try to dbl-spend it after the fact
