### ISSUE TITLE
Bug bounty? :)

### ISSUE THREAD

**Issue by Satoshi0x** [syscoin/syscoin#456]
Basically I was running 4.3.0rc1 on the mainnet because its open source and rc get run on mainnets a lot. It worked great. I liked the new features as well. For some reson a geth.exe node came in the source code that I ran and I got this screen but only worked once in my Syscon RPC console:

![4BX7IvWU](https://user-images.githubusercontent.com/48847567/134824735-a8addb2e-78ed-4b27-a718-e516753c1315.jpg)

There's a block for certain and in integer form its a negative block. The Geth I was runing was the newest and mainnet. But it worked. It's the first ETH Mainnet data to be called into the Syscoin Core RPC console i believe. However it never worked after that. just once. So i shut my extra geth node down and I sut the RPC one down but it wouldn't let me quit i t - the one that initializes on startup of the QT SysCoin Core. I been going eep on SYS and I love it more and more. I hope you know my commits to testing great software and innovative implementations stretches all the way back to why I went over to Devcoin early on.

Blockchain isn't going to just make you fiat. You're holding assets. Onces not subject to ridiculous tax. When the L2 game ends, it'll all makesense. But I do believe SYS stands the best shot of all!

If you guys want a guinea pig to make first attempts to break thru to new opportunities for syscoin users then I done. I will report all bugs like today: 

![image](https://user-images.githubusercontent.com/48847567/134824955-ebfadae2-983f-441b-9659-72fb7f8201c3.png)

I also spent 2 hours explaining how wrong a "Syscoin iss a shit coin" r/ethereum comment. Thank you Dan for the kind words, I will be buying your ADR securities in the US OTC market tomorrow for $BLFDF because I think your compliance is leading to the first North American securities and assets exchange. I really do.

Jag, bstr156, other community people. Thank you for the kind praise on my defense against fud. Sometimes you just see how amazing devs and their management and business plans come together and how patient they are in perfecting them. I see that in Sister Syscoin. And all the devs!

I am obsessed and i will be spending much time here testing and reporting.

Tips always appreciated :) I don't plan on selling any for fiat. They just have endless possibilities and use caes!

![syscoin1 wallet (1)](https://user-images.githubusercontent.com/48847567/134824989-21ef44ea-84e6-4bf7-ac69-d594741a94da.png)

[syscoin:SYS1QZW48TZR0QLTVZPZ0MKR99F2ZRFNAR940NMSUGP](url)

**Comment by sidhujag** [comment]
It is not ready for mainnet, pls run as testnet.. also note you do not need to run geth syscoin will manage it. Also note currently win64 geth wont run yet we are working on it

**Comment by Alternating** [comment]
Join us in the discord - we have a testnet propped up and you can get additional support https://discord.gg/Zvf996m7

https://bittyjohn1954.medium.com/syscoin-4-2-testnet-setup-guide-assuming-a-clean-install-63e8b2772600 - this is an old write up for when 4.2.2 released but the same principles apply. There will be more tweaks. 

Lets go!
