### ISSUE TITLE
Syscoin Core Version v4.3.0rc2 stops syncing headers at same block

### ISSUE THREAD

**Issue by Satoshi0x** [syscoin/syscoin#457]
Hello @sidhujag - I have done a fresh install of the new v.4.3.0rc2 of syscoin-qt.exe on Windows 10 OS. I always get stuck after multiple tries of syncing the [test] chain at block 839999 which you can see in the image below:

![systest1](https://user-images.githubusercontent.com/48847567/135549815-7e5f95d7-82fc-481e-9c14-4eb2b48dae2e.png)

One thing I notice is my connections is usually all v4.3.0 peers (10 connections, all outbound), but it will fluctuate and sometimes I get a peer from an older version in there and the connections will drop to 4 and slowly work up again with that older version still in the list (to 9 last time). Then it'll drop back to 4 peers again.

Initially all my connections at v4.3.0 as described:
![connections1](https://user-images.githubusercontent.com/48847567/135550142-602a95a2-3750-4545-9446-745c0b8552f1.png)

Then it drops:
![connections2](https://user-images.githubusercontent.com/48847567/135550153-0627cea9-be76-43da-9884-3e0d1bcdc6c0.png)

Finally...

It's always the same block where the headers stop syncing... (839999) Here's a look at my debug.log file and where I think the issue could be diagnosed by a more qualified person, a professional such as yourself:

> 2021-10-01T00:54:31Z Syscoin Core version v4.3.0rc2 (release build)
> 2021-10-01T00:54:31Z Qt 5.12.11 (static), plugin=windows (static)
> 2021-10-01T00:54:31Z Static plugins:
> 2021-10-01T00:54:31Z  QWindowsIntegrationPlugin, version 330752
> 2021-10-01T00:54:31Z  QWindowsVistaStylePlugin, version 330752
> 2021-10-01T00:54:31Z Style: windowsvista / QWindowsVistaStyle
> 2021-10-01T00:54:31Z System: Windows 10 (10.0), x86_64-little_endian-llp64
> 2021-10-01T00:54:31Z Screen: \\.\DISPLAY1 1920x1080, pixel ratio=1.0
> 2021-10-01T00:54:31Z Screen: \\.\DISPLAY2 1920x1080, pixel ratio=1.0
> 2021-10-01T00:54:32Z Assuming ancestors of block 0000003243223caf052c7e5e6710fae794dbdc10949a594550f073dbf5755bd4 have valid signatures.
> 2021-10-01T00:54:32Z Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000141f25d13472
> 2021-10-01T00:54:32Z Using the 'shani(1way,2way)' SHA256 implementation
> 2021-10-01T00:54:32Z Using RdSeed as additional entropy source
> 2021-10-01T00:54:32Z Using RdRand as an additional entropy source
> 2021-10-01T00:54:32Z GUI: "registerShutdownBlockReason: Successfully registered: Syscoin Core didn't yet exit safely…"
> 2021-10-01T00:54:32Z Default data directory C:\Users\dtrec\AppData\Roaming\Syscoin
> 2021-10-01T00:54:32Z Using data directory C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3
> 2021-10-01T00:54:32Z Config file: C:\Users\dtrec\AppData\Roaming\Syscoin\syscoin.conf (not found, skipping)
> 2021-10-01T00:54:32Z Setting file arg: wallet = ["Test Syscoin"]
> 2021-10-01T00:54:32Z Command-line arg: testnet=""
> 2021-10-01T00:54:32Z Using at most 125 automatic connections (2048 file descriptors available)
> 2021-10-01T00:54:32Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
> 2021-10-01T00:54:32Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
> 2021-10-01T00:54:32Z Script verification uses 11 additional threads
> 2021-10-01T00:54:32Z scheduler thread start
> 2021-10-01T00:54:32Z HTTP: creating work queue of depth 16
> 2021-10-01T00:54:32Z Using random cookie authentication.
> 2021-10-01T00:54:32Z Generated RPC authentication cookie C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\.cookie
> 2021-10-01T00:54:32Z HTTP: starting 4 worker threads
> 2021-10-01T00:54:32Z Using wallet directory C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\wallets
> 2021-10-01T00:54:32Z init message: Verifying wallet(s)…
> 2021-10-01T00:54:32Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
> 2021-10-01T00:54:32Z Using wallet C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\wallets\Test Syscoin\wallet.dat
> 2021-10-01T00:54:32Z BerkeleyEnvironment::Open: LogDir=C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\wallets\Test Syscoin\database ErrorFile=C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\wallets\Test Syscoin\db.log
> 2021-10-01T00:54:32Z Using /16 prefix for IP bucketing
> 2021-10-01T00:54:32Z init message: Loading P2P addresses…
> 2021-10-01T00:54:32Z Loaded 240 addresses from peers.dat  2ms
> 2021-10-01T00:54:32Z init message: Loading banlist…
> 2021-10-01T00:54:32Z SetNetworkActive: true
> 2021-10-01T00:54:32Z CBlockPolicyEstimator::Read(): unable to read policy estimator data (non-fatal): up-version (149900) fee estimate file
> 2021-10-01T00:54:32Z Failed to read fee estimates from C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\fee_estimates.dat. Continue anyway.
> 2021-10-01T00:54:32Z init message: Loading sporks cache...
> 2021-10-01T00:54:32Z Reading info from sporks.dat...
> 2021-10-01T00:54:32Z Loaded info from sporks.dat  1ms
> 2021-10-01T00:54:32Z      Sporks: 4
> 2021-10-01T00:54:32Z Read: Cleaning....
> 2021-10-01T00:54:32Z      Sporks: 4
> 2021-10-01T00:54:32Z Cache configuration:
> 2021-10-01T00:54:32Z * Using 2.0 MiB for block index database
> 2021-10-01T00:54:32Z * Using 8.0 MiB for chain state database
> 2021-10-01T00:54:32Z * Using 440.0 MiB for in-memory UTXO set (plus up to 2861.0 MiB of unused mempool space)
> 2021-10-01T00:54:32Z init message: Loading block index…
> 2021-10-01T00:54:32Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
> 2021-10-01T00:54:32Z Creating LLMQ and asset databases...
> 2021-10-01T00:54:32Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\evodb
> 2021-10-01T00:54:32Z DoGethMaintenance: Stopping Geth
> 2021-10-01T00:54:32Z DoGethMaintenance: Starting Geth because PID's were uninitialized
> 2021-10-01T00:54:32Z StartGethNode: Downloading Geth descriptor from https://raw.githubusercontent.com/syscoin/descriptors/master/gethdescriptor.json
> 2021-10-01T00:54:32Z Opened LevelDB successfully
> 2021-10-01T00:54:32Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\evodb: 0000000000000000
> 2021-10-01T00:54:32Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\llmq/dkgdb
> 2021-10-01T00:54:32Z Opened LevelDB successfully
> 2021-10-01T00:54:32Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\llmq/dkgdb: 0000000000000000
> 2021-10-01T00:54:32Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\llmq
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\llmq: 0000000000000000
> 2021-10-01T00:54:33Z DownloadBinaryFromDescriptor: Version (4.3.0rc2) is up-to-date!
> 2021-10-01T00:54:33Z StartGethNode: Starting geth with command line: C:\Users\dtrec\AppData\Roaming\Syscoin\sysgeth.exe --datadir C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\geth --tanenbaum --nevmpub tcp://127.0.0.1:1111 ...
> 2021-10-01T00:54:33Z CreateProcessW app C:\Users\dtrec\AppData\Roaming\Syscoin\sysgeth.exe C:\Users\dtrec\AppData\Roaming\Syscoin\sysgeth.exe --datadir C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\geth --tanenbaum --nevmpub tcp://127.0.0.1:1111 
> 2021-10-01T00:54:33Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\llmq/recsigdb
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\llmq/recsigdb: 0000000000000000
> 2021-10-01T00:54:33Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\llmq
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\llmq: 0000000000000000
> 2021-10-01T00:54:33Z cl-schdlr thread start
> 2021-10-01T00:54:33Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\asset
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\asset: 0000000000000000
> 2021-10-01T00:54:33Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\assetnft
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\assetnft: 0000000000000000
> 2021-10-01T00:54:33Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\nevmtxroots
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\nevmtxroots: 0000000000000000
> 2021-10-01T00:54:33Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\nevmminttx
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\nevmminttx: 0000000000000000
> 2021-10-01T00:54:33Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\dbblockindex
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\dbblockindex: 0000000000000000
> 2021-10-01T00:54:33Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\blocks\index
> 2021-10-01T00:54:33Z Opened LevelDB successfully
> 2021-10-01T00:54:33Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\blocks\index: 0000000000000000
> 2021-10-01T00:54:33Z StartGethNode: Geth Started with pid 11256
> 2021-10-01T00:54:36Z LoadBlockIndexDB: last block file = 3
> 2021-10-01T00:54:36Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=60271, size=35612345, heights=779856...840148, time=2021-08-15...2021-09-28)
> 2021-10-01T00:54:36Z Checking all blk files are present...
> 2021-10-01T00:54:36Z Opening LevelDB in C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\chainstate
> 2021-10-01T00:54:36Z Opened LevelDB successfully
> 2021-10-01T00:54:36Z Using obfuscation key for C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\chainstate: 09355b7681363f87
> 2021-10-01T00:54:37Z Loaded best chain: hashBestChain=00000038c65934be4c2506c5943f95a3f768b25b98752c89801cf51206bf128e height=839999 date=2021-09-27T03:07:52Z progress=0.993453
> 2021-10-01T00:54:37Z init message: Verifying blocks…
> 2021-10-01T00:54:37Z Verifying last 6 blocks at level 3
> 2021-10-01T00:54:37Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
> 2021-10-01T00:54:37Z No coin database inconsistencies in last 6 blocks (6 transactions)
> 2021-10-01T00:54:37Z ResetBlockFailureFlags: the best known invalid block (0000001f88e57813a8d4b184480c627c6f5e4bd40c5f66c20dd8ecc1045db171) is ahead of our tip, reconsidering
> 2021-10-01T00:54:37Z  block index            4797ms
> 2021-10-01T00:54:37Z init message: Loading Geth...
> 2021-10-01T00:54:42Z init message: Loading wallet…
> 2021-10-01T00:54:42Z BerkeleyEnvironment::Open: LogDir=C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\wallets\Test Syscoin\database ErrorFile=C:\Users\dtrec\AppData\Roaming\Syscoin\testnet3\wallets\Test Syscoin\db.log
> 2021-10-01T00:54:42Z [Test Syscoin] Wallet File Version = 169900
> 2021-10-01T00:54:42Z [Test Syscoin] Keys: 4002 plaintext, 0 encrypted, 4002 w/ metadata, 4002 total. Unknown wallet records: 0
> 2021-10-01T00:54:42Z [Test Syscoin] Wallet completed loading in              50ms
> 2021-10-01T00:54:42Z [Test Syscoin] setKeyPool.size() = 2000
> 2021-10-01T00:54:42Z [Test Syscoin] mapWallet.size() = 0
> 2021-10-01T00:54:42Z [Test Syscoin] m_address_book.size() = 0
> 2021-10-01T00:54:42Z fDisableGovernance 0
> 2021-10-01T00:54:42Z init message: Loading masternode cache...
> 2021-10-01T00:54:42Z Reading info from mncache.dat...
> 2021-10-01T00:54:42Z loadblk thread start
> 2021-10-01T00:54:42Z Filling coin cache with masternode UTXOs...
> 2021-10-01T00:54:42Z Loaded info from mncache.dat  1ms
> 2021-10-01T00:54:42Z      Masternodes: meta infos object count: 0
> 2021-10-01T00:54:42Z Read: Cleaning....
> 2021-10-01T00:54:42Z      Masternodes: meta infos object count: 0
> 2021-10-01T00:54:42Z init message: Loading governance cache...
> 2021-10-01T00:54:42Z Reading info from governance.dat...
> 2021-10-01T00:54:42Z Loaded info from governance.dat  1ms
> 2021-10-01T00:54:42Z      Governance Objects: 0 (Proposals: 0, Triggers: 0, Other: 0; Erased: 0), Votes: 0
> 2021-10-01T00:54:42Z Read: Cleaning....
> 2021-10-01T00:54:42Z      Governance Objects: 0 (Proposals: 0, Triggers: 0, Other: 0; Erased: 0), Votes: 0
> 2021-10-01T00:54:42Z init message: Loading fulfilled requests cache...
> 2021-10-01T00:54:42Z Reading info from netfulfilled.dat...
> 2021-10-01T00:54:42Z Loaded info from netfulfilled.dat  1ms
> 2021-10-01T00:54:42Z      Nodes with fulfilled requests: 3
> 2021-10-01T00:54:42Z Read: Cleaning....
> 2021-10-01T00:54:42Z      Nodes with fulfilled requests: 0
> 2021-10-01T00:54:42Z llmq-1 thread start
> 2021-10-01T00:54:42Z llmq-2 thread start
> 2021-10-01T00:54:42Z sigshares thread start
> 2021-10-01T00:54:42Z Filling coin cache with masternode UTXOs: done in 6ms
> 2021-10-01T00:54:42Z Locking masternode collateral!
> 2021-10-01T00:54:42Z block tree size = 841058
> 2021-10-01T00:54:42Z nBestHeight = 839999
> 2021-10-01T00:54:42Z Imported mempool transactions from disk: 0 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
> 2021-10-01T00:54:42Z loadblk thread exit
> 2021-10-01T00:54:42Z AddLocal([2601:249:603:e05:4ce5:1be9:ac88:e6b7]:18369,1)
> 2021-10-01T00:54:42Z Discover: DESKTOP-KDS9TET - 2601:249:603:e05:4ce5:1be9:ac88:e6b7
> 2021-10-01T00:54:42Z AddLocal([2601:249:603:e05::2f63]:18369,1)
> 2021-10-01T00:54:42Z Discover: DESKTOP-KDS9TET - 2601:249:603:e05::2f63
> 2021-10-01T00:54:42Z AddLocal([2601:249:603:e05:f8c9:dd64:5c8b:9ce1]:18369,1)
> 2021-10-01T00:54:42Z Discover: DESKTOP-KDS9TET - 2601:249:603:e05:f8c9:dd64:5c8b:9ce1
> 2021-10-01T00:54:42Z mapport thread start
> 2021-10-01T00:54:42Z Bound to 127.0.0.1:18372
> 2021-10-01T00:54:42Z torcontrol thread start
> 2021-10-01T00:54:42Z Bound to [::]:18369
> 2021-10-01T00:54:42Z Bound to 0.0.0.0:18369
> 2021-10-01T00:54:42Z Loaded 1 addresses from "anchors.dat"
> 2021-10-01T00:54:42Z 1 block-relay-only anchors will be tried for connections.
> 2021-10-01T00:54:42Z init message: Starting network threads…
> 2021-10-01T00:54:42Z net thread start
> 2021-10-01T00:54:42Z dnsseed thread start
> 2021-10-01T00:54:42Z init message: Done loading
> 2021-10-01T00:54:42Z addcon thread start
> 2021-10-01T00:54:42Z mncon thread start
> 2021-10-01T00:54:42Z Waiting 11 seconds before querying DNS seeds.
> 2021-10-01T00:54:42Z opencon thread start
> 2021-10-01T00:54:42Z msghand thread start
> 2021-10-01T00:54:42Z GUI: Platform customization: "windows"
> 2021-10-01T00:54:43Z New outbound peer connected: version: 70016, blocks=840184, peer=0 (block-relay-only)
> 2021-10-01T00:54:43Z Synchronizing blockheaders, height: 840184 (~99.85%)
> 2021-10-01T00:54:48Z NotifyNEVMComms: nevm-response-not-found
> 2021-10-01T00:54:48Z InvalidChainFound: invalid block=0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54  height=840000  log2_work=44.335475  date=2021-09-27T20:47:55Z
> 2021-10-01T00:54:48Z InvalidChainFound:  current best=00000038c65934be4c2506c5943f95a3f768b25b98752c89801cf51206bf128e  height=839999  log2_work=44.335475  date=2021-09-27T03:07:52Z
> 2021-10-01T00:54:48Z ERROR: ConnectTip: ConnectBlock 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 failed, nevm-not-connected
> 2021-10-01T00:54:48Z InvalidChainFound: invalid block=000000365f1d37d2d75e31de1d0b5f9199edda85738a50362ff3535e25589792  height=840028  log2_work=44.335566  date=2021-09-28T17:44:36Z
> 2021-10-01T00:54:48Z InvalidChainFound:  current best=00000038c65934be4c2506c5943f95a3f768b25b98752c89801cf51206bf128e  height=839999  log2_work=44.335475  date=2021-09-27T03:07:52Z
> 2021-10-01T00:54:48Z New outbound peer connected: version: 70016, blocks=841416, peer=1 (outbound-full-relay)
> 2021-10-01T00:54:49Z New outbound peer connected: version: 70016, blocks=841416, peer=2 (outbound-full-relay)
> 2021-10-01T00:54:50Z New outbound peer connected: version: 70015, blocks=539999, peer=3 (outbound-full-relay)
> 2021-10-01T00:54:50Z No valid UPnP IGDs found
> 2021-10-01T00:54:53Z P2P peers available. Skipped DNS seeding.
> 2021-10-01T00:54:53Z dnsseed thread exit
> 2021-10-01T00:55:01Z New outbound peer connected: version: 70016, blocks=840011, peer=4 (outbound-full-relay)
> 2021-10-01T00:55:02Z New outbound peer connected: version: 70016, blocks=841416, peer=5 (outbound-full-relay)
> 2021-10-01T00:55:02Z New outbound peer connected: version: 70016, blocks=841416, peer=6 (outbound-full-relay)
> 2021-10-01T00:55:09Z New outbound peer connected: version: 70016, blocks=841416, peer=7 (outbound-full-relay)
> 2021-10-01T00:55:09Z New outbound peer connected: version: 70016, blocks=841416, peer=8 (outbound-full-relay)
> 2021-10-01T00:55:10Z New outbound peer connected: version: 70016, blocks=841416, peer=9 (block-relay-only)
> 2021-10-01T00:56:58Z natpmp: The gateway does not support NAT-PMP.
> 2021-10-01T01:00:07Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:00:07Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:00:07Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:00:07Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:00:07Z New outbound peer connected: version: 70016, blocks=841417, peer=10 (outbound-full-relay)
> 2021-10-01T01:00:07Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:00:07Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:00:07Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:00:14Z New outbound peer connected: version: 70016, blocks=841417, peer=11 (outbound-full-relay)
> 2021-10-01T01:00:20Z New outbound peer connected: version: 70016, blocks=841417, peer=12 (outbound-full-relay)
> 2021-10-01T01:00:37Z New outbound peer connected: version: 70016, blocks=841417, peer=13 (outbound-full-relay)
> 2021-10-01T01:00:49Z New outbound peer connected: version: 70015, blocks=539999, peer=14 (outbound-full-relay)
> 2021-10-01T01:01:13Z New outbound peer connected: version: 70016, blocks=841417, peer=15 (outbound-full-relay)
> 2021-10-01T01:02:06Z No valid UPnP IGDs found
> 2021-10-01T01:02:09Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:02:09Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:02:09Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:02:09Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid
> 2021-10-01T01:02:11Z ERROR: AcceptBlockHeader: block 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 is marked invalid

The above log is from where I'm stuck as I write and after my last attempt to start up the software. For comparisons sake you can see how it gets stuck when I do a fresh sync from the start and not from where I left off last night when it stalled:

> 2021-09-30T06:29:26Z UpdateTip: new best=0000001815d752438289bc766950e3c87184491df763ef44a553ed2e11a1a3a6 height=839997 version=0x20080000 log2_work=44.335467 tx=853727 date='2021-09-27T03:06:20Z' progress=0.994730 cache=238.0MiB(1606730txo)
> 2021-09-30T06:29:26Z UpdateTip: new best=00000005a30bbecd7f884aafc9db7afb8cb29753ebf53386cb48068de04453c5 height=839998 version=0x20080000 log2_work=44.335471 tx=853728 date='2021-09-27T03:06:32Z' progress=0.994730 cache=238.0MiB(1606732txo)
> 2021-09-30T06:29:26Z UpdateTip: new best=00000038c65934be4c2506c5943f95a3f768b25b98752c89801cf51206bf128e height=839999 version=0x20080000 log2_work=44.335475 tx=853729 date='2021-09-27T03:07:52Z' progress=0.994732 cache=238.0MiB(1606734txo)
> 2021-09-30T06:29:31Z NotifyNEVMComms: nevm-response-not-found
> 2021-09-30T06:29:31Z InvalidChainFound: invalid block=0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54  height=840000  log2_work=44.335475  date=2021-09-27T20:47:55Z
> 2021-09-30T06:29:31Z InvalidChainFound:  current best=00000038c65934be4c2506c5943f95a3f768b25b98752c89801cf51206bf128e  height=839999  log2_work=44.335475  date=2021-09-27T03:07:52Z
> 2021-09-30T06:29:31Z ERROR: ConnectTip: ConnectBlock 0000053d4154c4028889dd39dcff1e8a433364e5cdfb75e9e21cc3b8345e0f54 failed, nevm-not-connected
> 2021-09-30T06:29:31Z InvalidChainFound: invalid block=000000267b3c6a5cb27fc236eb0e391d5b740107842d68817b11b7ef2a78c27b  height=840005  log2_work=44.335494  date=2021-09-27T20:57:35Z
> 2021-09-30T06:29:31Z InvalidChainFound:  current best=00000038c65934be4c2506c5943f95a3f768b25b98752c89801cf51206bf128e  height=839999  log2_work=44.335475  date=2021-09-27T03:07:52Z
> 2021-09-30T06:29:54Z New outbound peer connected: version: 70015, blocks=539999, peer=16 (outbound-full-relay)
> 2021-09-30T06:30:46Z ERROR: AcceptBlockHeader: prev block invalid
> 2021-09-30T06:30:46Z ERROR: AcceptBlockHeader: prev block invalid
> 2021-09-30T06:30:46Z ERROR: AcceptBlockHeader: prev block invalid
> 2021-09-30T06:30:46Z ERROR: AcceptBlockHeader: prev block invalid
> 2021-09-30T06:30:46Z ERROR: AcceptBlockHeader: prev block invalid
> 2021-09-30T06:30:46Z ERROR: AcceptBlockHeader: prev block invalid
> 2021-09-30T06:30:46Z ERROR: AcceptBlockHeader: prev block invalid
> 2021-09-30T06:32:29Z No valid UPnP IGDs found
> 2021-09-30T06:33:02Z New outbound peer connected: version: 70016, blocks=841058, peer=17 (outbound-full-relay)

I will wait for a response and check if anyone on Discord can help.

**Comment by Satoshi0x** [comment]
The fix was putting this into my syscoin.conf file:
![image](https://user-images.githubusercontent.com/48847567/135551452-7d8dcce9-3984-44ac-b8ba-c5fb78916428.png)

Thanks to John. I am synced this can close.

**Comment by shop271** [comment]
hello，I have the same problem
ubuntu 18.04
syscoin.conf
[main]
server=1
txindex=1
rpcbind=192.168.0.154
rpcbind=127.0.0.1
rpcport=8370
rpcallowip=192.168.0.0/24
rpcuser=rpcuser
rpcpassword=rpcpassword
gethwebsocketport=8646
zmqpubnevm=

**Comment by sidhujag** [comment]
if you reindex you should not see this problem, please show your debug.log, by the way for windows you do not need to do zmqpubnevm= any more it should work with geth now but doing zmqpubnevm= will skip downloading and running geth

**Comment by suffixed** [comment]
Hi @sidhujag , unfortunately happens the same with me. Just installed 4.3.0 in the same directory where 4.2 was installed. Syncing headers gest stuck at 1323787 (99.14%). (In advance perhaps), where is the debug.log file located?

**Comment by sidhujag** [comment]
in the data directory @suffixed https://en.bitcoin.it/wiki/Data_directory
