### ISSUE TITLE
NEVM - Issue with burning SYS to SYSX

### ISSUE THREAD

**Issue by fintroll20** [syscoin/syscoin#463]
Windows 10
Chrome Version 95.0.4638.69 (Official build) (64-bits)
Pali wallet 1.0.10

In this scenario, I try to burn SYS to SYSX. I have 30 SYS in my Pali wallet:

![image](https://user-images.githubusercontent.com/56633605/141461871-f82ad1fc-2adb-4905-b236-683e262dfdfa.png)

For this test, I manually split the balance up to two UTXOs one 20 SYS and one 10 SYS on the same address in my XPUB.

![image](https://user-images.githubusercontent.com/56633605/141461986-f65a4d7c-9d3e-41c8-8ccb-503523a8cb20.png)

When I try to burn any amount of SYS that exceeds the balance of a single UTXO, the bridge gives me an error. In this case, I try to burn 21 SYS:
The signature request appears in the wallet:
![image](https://user-images.githubusercontent.com/56633605/141461708-d1f39411-6dd4-4fe8-903b-1153335ab50d.png)
and when I sign: 
![image](https://user-images.githubusercontent.com/56633605/141461825-0ef283b4-8a06-4db7-b256-2a7229092816.png)

Burning any amount less than a single UTXO works. In this example 9 SYS and 19 SYS;

![image](https://user-images.githubusercontent.com/56633605/141462176-1d616e36-505c-4810-bc79-29c1ad43f6d9.png)
![image](https://user-images.githubusercontent.com/56633605/141462820-8f25a999-62d3-4bd8-928e-145e87e2e651.png)

Now I have two addresses with < 1SYS which equals:
![image](https://user-images.githubusercontent.com/56633605/141462985-57bd6ba6-d3a5-4d42-9cb7-98fe188615f8.png)

and when I try that again with burning >=1 SYS:

![image](https://user-images.githubusercontent.com/56633605/141462949-c8da678b-6620-448e-99c3-71bc35c89a8f.png)

**Comment by sidhujag** [comment]
lets see what happens when we update the dapp as we fixed #462 this might be related

**Comment by sidhujag** [comment]
@fintroll20 what is your seed phrase

**Comment by fintroll20** [comment]
occur remember orbit prosper wisdom high body cage evidence cannon collect cluster

**Comment by fintroll20** [comment]
Can't find any more issues with burns. I tried every scenario I could think of on the SYS-SYSX as well as on the  SYSX-NEVM bridge and back.
I think you fixed them all.
