### ISSUE TITLE
make depends error 404 fetching v20210106.tar.gz from https://github.com/syscoin/bls-signatures/archive

### ISSUE THREAD

**Issue by walkjivefly** [syscoin/syscoin#465]
Attempting to build the depends for v4.2.2 from source fails with
```
mark@x230:~/src/syscoin$ NO_QT=1 make -C depends
make: Entering directory '/home/mark/src/syscoin/depends'
Checksum missing or mismatched for chia_bls source. Forcing re-download.
Fetching v20210106.tar.gz from https://github.com/syscoin/bls-signatures/archive
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   133  100   133    0     0   1023      0 --:--:-- --:--:-- --:--:--  1023
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Fetching v20210106.tar.gz from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
make: *** [funcs.mk:282: /home/mark/src/syscoin/depends/sources/download-stamps/.stamp_fetched-chia_bls-v20210106.tar.gz.hash] Error 22
make: Leaving directory '/home/mark/src/syscoin/depends'
```

**Expected behavior**

It should be possible to build the client from scratch.

**Actual behavior**

make depends fails because of missing files at the source URLs

**To reproduce**
```
git clone https://github.com/syscoin/syscoin.git
cd syscoin
git checkout v4.2.2
./autogen.sh
NO_QT=1 make -C depends
```

**System information**

MX Linux 19.3
Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz

**Comment by sidhujag** [comment]
hmm im not sure why the chia release package tag was removed there. can you try dev-4.x branch it should work

**Comment by walkjivefly** [comment]
Thanks for the quick response. I could try the dev-4.x branch but I particularly wanted to build a 4.2.2 from scratch, not the latest v4 dev branch which is dozens of commits ahead of v4.2.2 as released.

**Comment by sidhujag** [comment]
> Thanks for the quick response. I could try the dev-4.x branch but I particularly wanted to build a 4.2.2 from scratch, not the latest v4 dev branch which is dozens of commits ahead of v4.2.2 as released.

Note, we are about to upgrade from dev-4.x to master (date and block to be announced) so if you can hold off until then or use dev-4.x branch to make your build that would be great!

**Comment by walkjivefly** [comment]
Presumably the upgrade will be a mandatory one, and soon (TM)? 
If so I can wait and try with that. 
Thanks.

**Comment by sidhujag** [comment]
> Presumably the upgrade will be a mandatory one, and soon (TM)? If so I can wait and try with that. Thanks.

yes around december 6

**Comment by walkjivefly** [comment]
OK, I'll wait for that,
