### ISSUE TITLE
error on compile 4.3.0 

### ISSUE THREAD

**Issue by laakie** [syscoin/syscoin#468]
Ubuntu 14.04.5 LTS

  CXX      util/libsyscoin_util_a-syscall_sandbox.o
util/syscall_sandbox.cpp:110:6: error: ‘__NR_bpf’ was not declared in this scope
  110 |     {__NR_bpf, "bpf"},
      |      ^~~~~~~~
util/syscall_sandbox.cpp:144:6: error: ‘__NR_execveat’ was not declared in this scope
  144 |     {__NR_execveat, "execveat"},
      |      ^~~~~~~~~~~~~
util/syscall_sandbox.cpp:220:6: error: ‘__NR_kexec_file_load’ was not declared in this scope
  220 |     {__NR_kexec_file_load, "kexec_file_load"},
      |      ^~~~~~~~~~~~~~~~~~~~
util/syscall_sandbox.cpp:239:6: error: ‘__NR_memfd_create’ was not declared in this scope
  239 |     {__NR_memfd_create, "memfd_create"},
      |      ^~~~~~~~~~~~~~~~~
util/syscall_sandbox.cpp:247:6: error: ‘__NR_mlock2’ was not declared in this scope
  247 |     {__NR_mlock2, "mlock2"},
      |      ^~~~~~~~~~~
util/syscall_sandbox.cpp:431:6: error: ‘__NR_userfaultfd’ was not declared in this scope
  431 |     {__NR_userfaultfd, "userfaultfd"},
      |      ^~~~~~~~~~~~~~~~
util/syscall_sandbox.cpp:444:1: error: no matching function for call to ‘std::map<unsigned int, std::basic_string<char> >::map(<brace-enclosed initializer list>)’
  444 | };
      | ^
In file included from /usr/include/c++/9/map:61,
                 from util/syscall_sandbox.cpp:16:

**Comment by sidhujag** [comment]
does master branch of bitcoin compile?

**Comment by c-e-d-git** [comment]
Ubuntu 14 is far too old. Many libs and dependencies need more actual versions for bitcoin and syscoin to compile.
You should use at least 18.04, recommended is 20.04.

**Comment by laakie** [comment]
Yes, I know it's old and not ideal. but for various reasons we like to stick to it.
BTC v0.22 compiled without any problems, build using depends.

Also tried another server running Ubuntu 18.04.5 LTS, also got the same problem there

**Comment by laakie** [comment]
It's a kernel version issue I think ?
Is there any way around it, or can we skip buidling some parts maybe ?

**Comment by laakie** [comment]
Removed the lines in src/util/syscall_sandbox.cpp
Got it compiled without further errors, should that cause any problems ? :)

**Comment by sidhujag** [comment]
no it won't cause problems
