### ISSUE TITLE
getauxblock - TestBlockValidity failed: bad-cb-process-mn"

### ISSUE THREAD

**Issue by laakie** [syscoin/syscoin#469]
Receiving an awefull amount of errors on getauxblock since update to 4.3.0
{"code":-1,"message":"CreateNewBlock: TestBlockValidity failed: bad-cb-process-mn"}

Already redownloaded the blockchain without success.

Where does this come from, and what can be done about it ?

**Comment by sidhujag** [comment]
if you are a miner you should not be mining yet it is not backwards compatible, you should wait for further instructions on using getauxblock, we will wait for fork height, manually do some blocks test the bridge between utxo and evm chain is all functional before notifying the rest of the network

**Comment by laakie** [comment]
ok... reverting for now.

**Comment by sidhujag** [comment]
you can try it again now

**Comment by laakie** [comment]
ERROR: Could not fetch NEVM block nevm-header-not-sent
 On 4.3.0
