### ISSUE TITLE
syscoin-cli getauxblock error code: -1 error message: Could not fetch NEVM block nevm-header-not-sent

### ISSUE THREAD

**Issue by yangxiaoqiang2018** [syscoin/syscoin#470]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by laakie** [comment]
Same issue

**Comment by sidhujag** [comment]
is server in China? could it be that the descriptor is not downloading on startup? check debug.log to see on start if it is downloading gethdescriptor.json from https://raw.githubusercontent.com/syscoin/descriptors/master/gethdescriptor.json  and then downloading the binaries from the URL described for your operating system inside the json. This json should exist in the data directory you can see if it stored it or if it is empty if it could not download properly.

If it didn't download properly perhaps you can host this json in a more friendly place you can access and you can download the binary manually to put in the data directory. If the binary exists and the gethdescriptor.json is not changed (it downloads and checks the version from the json stored on disk) then it will skip binary download and use the one you have stored.

If you host the json in another place you can use -gethDescriptorURL command line parameter to override the location of where it tries to download the json file it is set to https://raw.githubusercontent.com/syscoin/descriptors/master/gethdescriptor.json by default.

**Comment by laakie** [comment]
Restarted with a clean datadir,
After syncing the binary is prescent in the datadir, 

Syncing stops at block #1317499
2021-12-08T11:54:43Z NotifyNEVMComms: nevm-connect-not-sent
2021-12-08T11:54:43Z InvalidChainFound: invalid block=47b73d70131632e8a200ea38e301427e1ac4e5fedb9fd5467df0e3c98e492fd7  height=1317500  log2_work=90.340363  date=2021-12-06T11:54:27Z
2021-12-08T11:54:43Z InvalidChainFound:  current best=311ff9683ecebd8a16362ce3187319b1c1568606fd3557ece40bd01b70f45099  height=1317499  log2_work=90.340362  date=2021-12-06T10:32:50Z
2021-12-08T11:54:43Z ERROR: ConnectTip: ConnectBlock 47b73d70131632e8a200ea38e301427e1ac4e5fedb9fd5467df0e3c98e492fd7 failed, nevm-connect-not-sent

**Comment by sidhujag** [comment]
@laakie this is the block before the fork, so maybe you do no have sysgeth process running here, do you have sysgeth.log and debug.log in your data directory you can attach here? It seems geth not running. Also if you are mining make sure you specify this in your configuration:
`gethcommandline=--miner.etherbase=0xe600696eb0555c93f2c391a1406726cee239091d (this address yours)`
so when you do get getauxblock it will go through.

But this syncing issue is because your geth node isn't running or responsive when it needs to be for block 1317500 (start of nevm)

**Comment by laakie** [comment]
Thank you, Had to close the old sysgeth process.
After that it synced up and all works perfect now.
