### ISSUE TITLE
Error: Cannot set -listen=0 together with -listenonion=1 [macOS]

### ISSUE THREAD

**Issue by cowkowsky** [syscoin/syscoin#471]
Problem: Syscoin Core does not launch anymore. When trying to, it displays the following error message: `Error: Cannot set -listen=0 together with -listenonion=1`
Reproduction: I do not know how to reproduce the error, but on my system, it is just a matter of launching the Syscoin executable.
System: macOS 11.2.3

Syscoin Core Version: Newest version (4.3.0), as published in the Github releases.

Debug.log: No information written to debug.log, seems to crash before that happens.

**Comment by sidhujag** [comment]
This is a policy in the code, it is also in BTC see the code here it is designed to now allow listen=0 and onion=1 to work together https://github.com/syscoin/syscoin/blob/master/src/init.cpp#L1016

**Comment by cowkowsky** [comment]
That may be, yet I never set those flags. Where are they stored so that I can change them?

**Comment by sidhujag** [comment]
It is undefined behaviour to use those two flags, you can update the code as I showed and compile and try it out. Not sure what you mean by "where are they stored" otherwise?

**Comment by cowkowsky** [comment]
I am running the client provided on GitHub, and it ran fine. Then I closed it, and upon reopening it, it showed that error. I thus do not think that updating anything in the code should be necessary. I thus assumed that this meant those flags are store somewhere and, somehow, got changed – why else would the behaviour of the application change in between two runs? Hence my question.

**Comment by sidhujag** [comment]
is it maybe defined in your syscoin.conf file if you have one?

**Comment by sidhujag** [comment]
looks like the issue is resolved, please open another if it persists.
