### ISSUE TITLE
Syscoin Authenticated Faucet possible bug?

### ISSUE THREAD

**Issue by Satoshi0x** [syscoin/syscoin#474]
Not sure where NEVM reports go but I used the Faucet for the mainnet NEVM and received 0.01 SYS that you see on the blockscout link. I have only used it once and only intended one use but it looks like I got 0.01 three more times and 1 SYS without even using it. I promised I wouldn't abuse the faucet and only use it that one time so I am reporting this here for you to explore further. Donations and begging at the same address always accepted :) If anyone wants to give me 10, 100, 1000 SYS just to keep the bug pattern up I won't mind. :) I am LONG SYS. $ piss me off. I don't need any $ anyway. So anything I do get, consider it out of circ.

https://explorer.syscoin.org/address/0x83C73d229084a2e226a33766aBea39f51e9a56AF/transactions

**Comment by c-e-d-git** [comment]
No faucet bug to see there.
Check the sender addresses.
1 tx in block 3905 is your faucet request I guess (lots of txs from that address).
3 txs in block 4200 are from a different address that has only made 9 txs at all.
1 tx in block 4215 is a donation from a third address that I happen to know.
