### ISSUE TITLE
Syscoin Core 4.3.0 Sync Error

### ISSUE THREAD

**Issue by bondcoder97** [syscoin/syscoin#476]
Hello! I can not sync masternode after upgrading to Syscoin Core 4.3.0.
My Syscoin Core syncs blocks to init headers count. 
After that syncing process are breaking and my blockchain are standing on old position.
It is crashing masternode work and it can not work with others network’s nodes.
I tried to reinstall / reindex Syscoin Core many times already.
I already created this topic on Syscoin support, but there are similar topics without answer there.
Please take your attention on this problem.

**Comment by Frank-GER** [comment]
Support is mainly in discord now and it is christmas / new years season.

Are you talking about the masternode itself or about the controlling wallet (like syscoin_qt)?
What is the error message in debug.log?

**Comment by johnp1954** [comment]
https://support.syscoin.org/t/qt-4-3-stuck-syncing/584

**Comment by bondcoder97** [comment]
> Support is mainly in discord now and it is christmas / new years season.
> 
> Are you talking about the masternode itself or about the controlling wallet (like syscoin_qt)? What is the error message in debug.log?


I am talking about masternode itself.
It simply does not sync with chain after first blockchain download.

**Comment by bondcoder97** [comment]
> https://support.syscoin.org/t/qt-4-3-stuck-syncing/584

As I understood this way will disable NEVM. Will masternode work after that?

**Comment by skironDotNet** [comment]
See my thread https://github.com/syscoin/syscoin/issues/475

**Comment by sidhujag** [comment]
need to see debug.log and sysgeth.log

**Comment by bondcoder97** [comment]
> need to see debug.log and sysgeth.log

**getblockchaininfo**
![2021-12-30_19-28](https://user-images.githubusercontent.com/32421572/147770614-644c939d-ab32-4602-9b5b-f12d3edfd52a.png)

**debug.log**
![2021-12-30_19-33](https://user-images.githubusercontent.com/32421572/147770710-00a64ce4-7ea2-4330-87ff-cce4a046ffe8.png)

**sysgeth.log**
![2021-12-30_19-31](https://user-images.githubusercontent.com/32421572/147770745-bc1f3e4e-3b8e-47e1-83b5-b65252a0f9ec.png)

**Comment by sidhujag** [comment]
on reindex it does this every time? this seems like its stuck on the fork block where geth is enabled.. if you reindex it should clear the geth data and let it connect as it starts with block 0.. and its clearly on some other block (https://explorer.syscoin.org/block/13345/transactions). Can you see in sysgeth.log that when you reindex it starts at block 0 again and resets everything on the geth node? it should reset the geth data directory when you reindex. The NEVM chain should start empty as you sync up and after block 1317500 it will start counting up nevm blocks

**Comment by bondcoder97** [comment]
> on reindex it does this every time? this seems like its stuck on the fork block where geth is enabled.. if you reindex it should clear the geth data and let it connect as it starts with block 0.. and its clearly on some other block (https://explorer.syscoin.org/block/13345/transactions). Can you see in sysgeth.log that when you reindex it starts at block 0 again and resets everything on the geth node? it should reset the geth data directory when you reindex. The NEVM chain should start empty as you sync up and after block 1317500 it will start counting up nevm blocks

Yeah, reindex was maked a lot of times, but it was not help to launch masternode correctly.
Every time I have sync stopping. I will try to monitore this process as you described.

**Comment by Frank-GER** [comment]
Did you install your masternode with the install script?
How did you do the reindex? I mean which commands did you use? Or did you add "reindex=1" to syscoin.conf?

**Comment by bondcoder97** [comment]
> Did you install your masternode with the install script? How did you do the reindex? I mean which commands did you use? Or did you add "reindex=1" to syscoin.conf?

Yes, I made reindex by two ways (during syscoind launch and in syscoin.conf file).
I did not find any way to resolve this problem.
I changed VPS and it works for now. Thanks for help.

**Comment by skironDotNet** [comment]
I think this https://github.com/syscoin/syscoin/issues/480 is relevant. The daemon enters a state of rejecting all incoming connections claiming our MN not synced, and MN becomes stale with continuous output
`2022-03-06T17:59:13Z AcceptConnection -- masternode is not synced yet, skipping inbound connection attempt`

**Comment by skironDotNet** [comment]
Look at this as well https://github.com/syscoin/syscoin/issues/475#issuecomment-1154171813
