### ISSUE TITLE
SYS stopped syncing, no way to get it back on the correct chain

### ISSUE THREAD

**Issue by cipig** [syscoin/syscoin#479]
my SYS daemon stopped syncing at block height 1366201, error:
```
ERROR: AcceptBlockHeader: block 2245c716fb26f12d5d288ddc50499820966bbe45374fd0724bd79b22ffcf39e6 is marked conflicting
```
but that block exists and is correct:
https://chainz.cryptoid.info/sys/block.dws?2245c716fb26f12d5d288ddc50499820966bbe45374fd0724bd79b22ffcf39e6.htm

tried to invalidate my 1366201 with
`syscoin-cli invalidateblock 9773a2e8417b92289efa68dbb547ab0765e1449a12953fe64305c6ec418cc800`
and reconsidering the correct block with
`syscoin-cli reconsiderblock 2245c716fb26f12d5d288ddc50499820966bbe45374fd0724bd79b22ffcf39e6`
but no success, the error in debug.log is still the same and i am stuck at this blockheight on a wrong chain

**Comment by sidhujag** [comment]
@cipig I believe you have to reindex, we have some commits in place that may eliminate this in the future but looks like two chainlocks were established at the same height

**Comment by cipig** [comment]
`-reindex` got me back on the correct chain
