### ISSUE TITLE
Is MN self connection check too early vs actual bind?

### ISSUE THREAD

**Issue by skironDotNet** [syscoin/syscoin#480]
![image](https://user-images.githubusercontent.com/2981715/156935275-1bffefe9-4a48-4085-a110-e7d709154ad8.png)

This is causing a problem w MN not wanting to sync

**Comment by skironDotNet** [comment]
```
masternode_status
{
  "outpoint": "0000000000000000000000000000000000000000000000000000000000000000-4294967295",
  "service": "2.71.15.38:8369",
  "state": "ERROR",
  "status": "Error. Could not connect to 2.71.15.38:8369"
}
```

**Comment by Frank-GER** [comment]
Right after the info about the config file arguments you should see msgs about worker threads getting started and network activated.
You should although see a msg about masternode blsPubKeyOperator.

The lines right above what you showed in the pic should be:
CActiveMasternodeManager::Init -- proTxHash=....
CActiveMasternodeManager::Init -- Checking inbound connection to ....

Inbound connections are refused at this point in the sync process and only opened up later. First the mn syncs with outbound connections only. This helps to protect you against "bad" nodes trying to connect to you during the sync process.

At this point you should see 
Bound to 127.0.0.1:8372
Bound to [::]:8369
Bound to 0.0.0.0:8369

After the "Bound to" msgs (greyed out IP seems too long) you should see several thread start msgs and the first outbound connections being made.

The _masternode_status_ shown indicates either an unfinished sync process or missing/faulty mn setup (see protx commands).
There is no mn for that service IP in the masternode list.

**Comment by skironDotNet** [comment]
I masked the IPs, my identity info has been stolen, I don't need to give the world my servers....

We can close this issue, It gets back to ERROR part from https://github.com/syscoin/syscoin/issues/475

My VPS has been interrupted, while chain was ok, it wasn't when MN newm... Had to restore chain from other MN to make it work...
