### ISSUE TITLE
Arbiter should be able to name his price

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#49]
Arbiter should be able to name his price, 0.5% does not make sense in many purchases. Discussed on previous issue the possibility of using alias controlled escrow fee. Ideally, the arbiter could put a minimum fee which would scale to a percentage if it goes beyond that fee (IE: 2% with a minimum of $5).

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
