### ISSUE TITLE
syscoind crashed with "Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:264)"

### ISSUE THREAD

**Issue by walkjivefly** [syscoin/syscoin#491]
syscoind 4.3.0 crashed while doing a fresh sync in a clean datadir. This node runs sysgeth too. Both chains were syncing OK, I was experimenting with sysgeth ipc at the time.

debug.log ends abruptly with 
```
2022-06-23T14:46:31Z UpdateTip: new best=c4afc09752e340270effab337e63969a12f934884a0cf14fdb04d37ad67df65a height=1370516 version=0x20100180 log2_work=90.558761 tx=2377379 date='2022-03-09T23:12:49Z' progress=0.928177 cache=475.2MiB(3206862txo)
2022-06-23T14:46:31Z NotifyNEVMComms: nevm-connect-not-sent
2022-06-23T14:46:31Z NotifyNEVMComms: nevm-connect-not-sent
```
The assertion failure was logged on the console only and I didn't get a coredump.

Last couple of lines in the sysgeth.log were
```
INFO [06-23|14:46:31.243] Imported new chain segment               blocks=1 txs=9   mgas=2.237 elapsed=31.773ms    mgasps=70.401   number=53016 hash=ee2313..a7f6e5 age=3mo2w1d   dirty=0.00B
INFO [06-23|14:46:31.294] Imported new chain segment               blocks=1 txs=8   mgas=0.682 elapsed=32.421ms    mgasps=21.041   number=53017 hash=53c2d8..5c299b age=3mo2w1d   dirty=0.00B
```

Sorry, I was in a hurry and 

**Expected behavior**

daemon should run without assertion failures

**Actual behavior**

daemon crashed

**To reproduce**

one-off event (so far), steps to reproduce unknown

**System information**

Syscoin Core version v4.3.0 (release build)

8 vcore, 32 GB RAM, SSD, Ubuntu 20.04 LTS

**Comment by Frank-GER** [comment]
That assert msg comes right out of zmq
https://github.com/zeromq/libzmq/blob/master/src/signaler.cpp#L264

At that point in sync there is a lot of communication between syscoind and sysgeth.
Do you remember what exactly you were doing with sysgeth  when the crash happened?

**Comment by walkjivefly** [comment]
I was trying a couple of calls (eth.syncing) in the geth CLI through an ipc connection while the chains were syncing. I can't say how long after I made the last call the crash happened. It could have been immediate, it could have been upto about 5 minutes since the assert appeared on a different screen.

**Comment by sidhujag** [comment]
able to repro @Frank-GER ?

**Comment by Frank-GER** [comment]
Hard to reproduce, seems very specific circumstances which we are missing the details of.
Sounds like geth was busy with the cli stuff and unable to handle the calls from zmq during sync.
That assert comes right out of the zmq lib.
From the code of the lib it looks like a timeout issue.
How to get geth too busy to return an answer to syscoind is another question.

The only other thing I can think of is  geth got killed (i.e. CTRL-C) while the zmq connection was open.
There are hints in the zmq repo this could cause that assert too.

**Comment by walkjivefly** [comment]
Yeah, sorry I have no more detailed steps to help reproduce it. 

I've synced up the SYS chains at least a dozen times since January but probably haven't used the geth CLI during the sync before now.

**Comment by sidhujag** [comment]
Let us know if you hit the issue again @walkjivefly ive never seen this before
