### ISSUE TITLE
refunding escrow issues and process should be automated

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#50]
-case: when arbiter refunds the status of the escrow shows as "escrow refunded", but when buyer accepts refund,    the status does not change between the buyer refunding, and wording should be "accept refund", it works but the status does not change, should be changed to "waiting for buyer to accept refund". But Ideally, this should all be automated, buyer should not have to accept refund and seller should not have to release escrow

Also, buyer choosing "refund escrow" in this case does not make sense, should be changed to "Accept Refund". if it's really necessary and cannot be automated.

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
