### ISSUE TITLE
Coin Control is broken in 4.4.1

### ISSUE THREAD

**Issue by beirut-boop** [syscoin/syscoin#524]
### Expected behavior

The amount calculated for "use available balance" is equal to the amount listed in "coin control features" (minus fee if checked).

### Actual behavior

The amount calculated for "use available balance" is the total address balance minus the selected inputs.

After having selected _Inputs..._[1] take a look at:

- **Amount** according to "coin control features"
- **Amount**[3] in the bottom section after clicking "use available balance"[2]

### Screenshots

![image](https://user-images.githubusercontent.com/78885860/226893360-58d411a3-74f5-4a52-bf86-fa140f219610.png)

![image](https://user-images.githubusercontent.com/78885860/226893534-991f89b9-038c-4bb8-a237-67c5cb902e57.png)

![image](https://user-images.githubusercontent.com/78885860/226893677-2ce86150-f73a-47f9-b519-91ff69cf74e3.png)

**Comment by johnp1954** [comment]
I can confirm this bug

**Comment by beirut-boop** [comment]
Issue identified: https://github.com/bitcoin/bitcoin/pull/26699

@sidhujag as far as I can tell, the issue was introduced on Oct 27, 2022 and discovered 48 days later on Dec 14, 2022 but still unresolved.

> If you consider this pull request important, please also help to review the conflicting pull requests. Ideally, start with the one that should be merged first.

**Comment by Rorrote** [comment]
d66b2ca6429adf7d9a30b6edc5b05ac79fea43ce
