### ISSUE TITLE
Bridge from Multichain

### ISSUE THREAD

**Issue by PIFLUS** [syscoin/syscoin#528]
the transaction has been paralyzed and appears in pending, without advancing in the shipment
Tx:  0xbe1c3ce1cecdbbcaca1bcead58bdc82983f359ce58fdddb907532e38258a881f

they can cancel it and return the funds ?

thanks

### Environment
* Elixir Version: 1.14.0
* Erlang Version: 25
* BlockScout Version: 

* User Agent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by EL10DAVID** [comment]
Transaction Hash
0x22a74678eee9d68fef46608c921559a9d8b9a3d25186100eee798796308cf9e0
 Result
 Error: dropped/replaced
 Status
Confirmed
 Block
Error: dropped/replaced
 From
[0xfed74046a7ecaFC8Ef6462e89471dA7A97815ad3](https://explorer.syscoin.org/address/0xfed74046a7ecaFC8Ef6462e89471dA7A97815ad3)
 To
[0x456325F2AC7067234dD71E01bebe032B0255e039](https://explorer.syscoin.org/address/0x456325F2AC7067234dD71E01bebe032B0255e039)
 Value
2.710857508881351161 SYS ($0.336087 USD)
 Transaction Fee
Max of 0.00010350000023 SYS ($0.000013 USD)
 Gas Price
4.50000001 Gwei
 Transaction Type
2 (EIP-1559)
 Gas Limit
23,000
 Max Fee per Gas
4.50000001 Gwei
 Max Priority Fee per Gas
1.5 Gwei
 Gas Used by Transaction
Pending
 NoncePosition
1853Error: dropped/replaced

**Comment by Frank-GER** [comment]
EL10DAVID:
see
Transaction Hash  0xe7e04c6d151251610ec47315af925dab1ab0418401182a22db2bdf45d85930db

**Comment by Frank-GER** [comment]
PIFLUS:

Timestamp  16 hours ago | July-02-2023 08:33:53 AM +2 UTC | Confirmed within <= 153.535 seconds 
From  0x4be516Dc7DD0156A52B600683691e9Ff755e9862)
Interacted With (To)  AnyswapV5ERC20 (0x922d64–d112e1)

Did you try to contact Multichain about it?
