### ISSUE TITLE
Buy tab should be cleared after accepting an offer

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin#55]
I think this was fixed previously, but when I accept an offer now the buy tab fields remain filled in

**Comment by sidhujag** [comment]
did it on purpose

**Comment by sysmca** [comment]
why?

**Comment by sidhujag** [comment]
if someone wanted to purchase it multiple times

**Comment by sysmca** [comment]
That's an edge case. User expectation is to have forms cleared or be taken to 'success' page, not be shown the tab they just left, with all the fields populated and a big button saying 'Purchase Offer'.. Suggests that the order didn't go through and buyer needs to resubmit.

**Comment by sidhujag** [comment]
but there is a message at the top saying you have purhcased this offer so user does not they have finished, I know what you are saying but as a user I found it annoying it was clearing

**Comment by sebastien1234** [comment]
I tend to agree with MCA, uthe message that says "you have successfully paid for this offer!" is not very evident, I'm not sure I understand why someone would want to buy multiple times that way since you can enter quantity in the first place.

**Comment by sebastien1234** [comment]
Should default to my purchase imo

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
