### ISSUE TITLE
Tabs: Send; Receive, Blockmarket; Alias, etc are fuzzy 

### ISSUE THREAD

**Issue by Seven7Sevin** [syscoin/syscoin#56]
Need better resolution of the wallet icons and various tab titles.

**Comment by sidhujag** [comment]
anti-aliased

**Comment by dwasyluk** [comment]
@Seven7Sevin can you please include a screenshot so we can verify/validate improvements?

**Comment by Seven7Sevin** [comment]
<img width="1440" alt="screen shot 2016-05-04 at 11 19 17 pm" src="https://cloud.githubusercontent.com/assets/17012847/15035362/3ce276a8-124f-11e6-9d9a-537995530c9c.png">
Dashboard/wallet icons and tab names should look razor sharp, high def, and professional. Pretty sure you guys already had that in mind for the June release product, but just in case.

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
