### ISSUE TITLE
Increase blank alias search capability beyond 100

### ISSUE THREAD

**Issue by Seven7Sevin** [syscoin/syscoin#65]
Alias search is limited to the first 100 aliases when search field is left blank. Hitting the search button again doesn't load more. Perhaps make it so user can scroll through all of them or add page numbers or whatever. At present, user must enter a letter in the field to search them. Thanks!

**Comment by sidhujag** [comment]
please test

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
