### ISSUE TITLE
wallet improvement suggestions

### ISSUE THREAD

**Issue by cryptojohn** [syscoin/syscoin#66]
Love the project development thus far. Just have a few items to humbly suggest.
1. Is there a way to incorporate an exchange into the wallet? Fully decentralized and either fee less or a minuscule fee that auto deposits into a sys development fund :-) Would also be nice to be able to buy BTC at least while it's still relevant. 
2. Can Slack be incorporated into wallet?

**Marketplace specific:**
1. Fixed drop down categories
2. Designated photo url field 
3. Pre-populated x_RATE peg field
4. number of hits/views for items
5. Different UI language "new item" vs "new offer" ect
6. posting time limit for items (help to prevent market bloat and the impossible finding of what you didn't know you needed)
7. Wallet specific help page and hover tool tips for fields when posting and buying.

**Comment by sidhujag** [comment]
Pretty much all of the specific issues have been targetted for testing in 2.1 beta 2 except 2/4/5/7 which can be done via blockmarket

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
