### ISSUE TITLE
Allow buyer message to be viewed while in escrow

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#68]
When using escrow there is currently no path to view the "buyer note" which contains the recipient's shipping information. The merchant needs to be able to view this information to complete the transaction so that the buyer will release the funds related to the purchase.

Add an option on escrow tab to view escrow info- should allow both buyer and seller to view buyer note contents in plain text. Arbiter cannot view buyer note contents plain text.

**Comment by sidhujag** [comment]
please test

**Comment by sidhujag** [comment]
I dont thint he buyer can read the note because we will have to duplicate that info but if we want that... we will have to add more data to escrow and leave this open if that is the case, otherwise test and close

**Comment by willyko** [comment]
Syscoin services have been stripped out of Syscoin-QT UI
