### ISSUE TITLE
Safer wallet browsing experience for general public (banlist)

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#70]
The Syscoin Marketplace was not developed to be a market where the filth of the world can be put on display and sold. Due its decentralized nature the team can do very little about what happens on the network and preventing sales at a network level would also run the risk of making the team liable for items that are missed.

To mitigate this without become network police as that is not our role we will make the best effort to ensure that browsing experiences within the wallet application delivered by the team are devoid of this unsavory content. To do so the following feature will be implemented:

**Marketplace:**
New SafeSearch checkbox, enabled by default will be present on the marketplace search tab, and the system will support 3 tiers of item banning:
1. Minor - items that are a nuisance that minors should most likely not be exposed to. These items will not be shown when SafeSearch is enabled.
2. Major - items that will not be shown in search, regardless of SafeSearch, but can still be direct-lookup.
3. Critical- items that cannot be search or purchased using the wallet GUI provided by the team.

**Aliases:**
1. Major - won't be shown in search

**Digital Certificates:**
1. Major - won't be shown in search

---

All items will have a "report as inappropriate" button added to them. Clicking this will prompt a new message to be send to the team's moderation alias, the team will review reports and add to the ban lists as needed. Messages for inapporiate content must include the severity and item GUID somewhere in the message. 

The filtering mechanism will operate on Syscoin's alias system. The team will operate an aliases that fetches banlists from a remote URL every time a search is performed so banlists can be updated without needed to download a new client. The banlist alias will hold a URL so that list scale doesn't become an issue. 

If there is a failure to fetch the banlist on any screen (market/alias/cert) the user will be presented with a warning - "Warning: Unable to fetch banlist from server. You may see inappopriate materials in search results, are you sure you want to continue?" Continue / Cancel buttons. 
- Cancel kills the search and doesn't display the results.
- Continue shows the search results, with banned listings

Team will draft up some guidelines for items that fall into these 3 severity categories. At the moment this issue is more about developing the architecture to support this, and testing it. Definition of tiers can happen later.

**Comment by sidhujag** [comment]
Ive actually got minor major and critical hooked up for aliases and certs... critical stops aliasinfo/certinfo from working... major stops the search even from safesearch.

**Comment by sidhujag** [comment]
need to test
