### ISSUE TITLE
Add default alias option/config

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#71]
After you've purchased a number of aliases it becomes rather annoying to have to visually search the list for your primary alias when creating an offer/message/cert. Would like to add a default alias configuration panel with the following options:
- default offer alias
- default message alias
- default cert alias
- default peg alias (SYS_RATES by default)

What these would do is preselect the default alias on the related screens rather than selecting the first alias in the list as it does today. If the alias can't be found because it was transferred or renamed then it goes back to the first alias in the list until the wallet owner updates their defaults. 

When replying to messages the default alias config shouldn't override the existing behavior, the reply should always come from the alias the original message was sent to by default.

Config panel should probably live in same area as themes panel.

**Comment by sidhujag** [comment]
plz test
