### ISSUE TITLE
Need easier way to unlock password with walletpassphrase - multiple experiences impacted

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#73]
Because so many of Syscoin's functions are predicated on an unlocked wallet we need to provide users an easier path to unlocking via an equivalent of the walletpassphrase RPC command. This is needed to view messages, send messages, buy items, and idk what else. The wallet doesn't prompt with a password dialog in these scenarios and the user needs somewhat technical crypto knowledge to go into the debug console and run the rpc commands to unlock their wallet for a period of time.

Add an item to file menu. File > Unlock Wallet. Spawns dialog w password prompt- masked, and time in seconds. 

Additional nice to have would be auto-spawning this dialog any time the user tries to run a command with a locked wallet, replacing the current message which tells them to run an RPC command (shown here when trying to accept an offer):

![screen shot 2016-05-05 at 1 48 15 am](https://cloud.githubusercontent.com/assets/987186/15036897/73d53a88-1263-11e6-9f82-cf2ee73dd76e.png)

**Comment by sidhujag** [comment]
please test, made it so that wallet will ask to unlock in the correct places and once you unlock from the dialog it will remain unlocked until you restart the wallet.

**Comment by willyko** [comment]
Syscoin functions have been removed from Syscoin-qt UI
