### ISSUE TITLE
Add a Item Wanted for Purchase feature? 

### ISSUE THREAD

**Issue by Seven7Sevin** [syscoin/syscoin#75]
For your consideration: Add a "looking for" page. E.g., I'm looking for a chainsaw, blue jeans, guitar, etc. A la Craigslist. Or is that too pawn shop-ish?

**Comment by sidhujag** [comment]
good thinking... i dunno if this is a blockchain thing or can be a GUI thing... need to triage

**Comment by sidhujag** [comment]
sloted for 2.1
