### ISSUE TITLE
search should not be case sensitive

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin#8]
Although aliases/offers/etc are case sensitive, their search should not be, please make searches not case-sensitive (alias, escrow, marketplace and certificates

Also @sidhujag for the search results, if nothing is found with the particular search, a message should pop-up that says something like "Offer not found" (and replace each one with alias, escrow, certificates.)

(moved from /Syscoin, issue #140)

**Comment by sidhujag** [comment]
retest in latest

**Comment by sebastien1234** [comment]
fixes #8
