### ISSUE TITLE
Cannot change alias safesearch setting

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#82]
When editing an existing alias its not possible to change its safe search setting, with offers it is possible to the change this (should be same for aliases, allowing user to change this is necessary in case they make a mistake in initial setting).

<img width="482" alt="screen shot 2016-06-20 at 11 47 08 pm" src="https://cloud.githubusercontent.com/assets/987186/16217427/51d3c10e-3741-11e6-91ed-a637b5e5e4d3.png">

**Comment by sidhujag** [comment]
Safe search should not be editable it's a bug if offers let you do it.

**Comment by sidhujag** [comment]
need to change safesearch as editable and change the moderation level as a seperate field

**Comment by jeroenvanwissen** [comment]
There's no indication that there's a pending operation on an alias when you change the safesearch option. When you open the alias detail screen directly after changing it, safesearch option is still on old value. When you change it again and try to save it:
> Error updating Alias: "there are pending operations on that alias"

( bonus suggestion: Add safesearch value in the overview screen table )
