### ISSUE TITLE
Safe search description cut off on all OSX screens

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#86]
The safe search description is cut off on multiple screens. Its also really long and redundant once you've read it once you get it, I suggest we change is to a "More info" link that spawns a simple alert with the info and an OK button.

Here are the places I've noticed the cutoff on OSX (also note the offer new screen is super wide, feels like its set to screen width %):

<img width="462" alt="screen shot 2016-06-21 at 12 53 37 am" src="https://cloud.githubusercontent.com/assets/987186/16218353/c0f501ac-374a-11e6-84cc-fc9e416eec50.png">

<img width="1787" alt="screen shot 2016-06-21 at 12 53 58 am" src="https://cloud.githubusercontent.com/assets/987186/16218354/c0f82576-374a-11e6-8803-b12581374199.png">

<img width="459" alt="screen shot 2016-06-21 at 12 53 22 am" src="https://cloud.githubusercontent.com/assets/987186/16218352/c0f4dbb4-374a-11e6-8876-f9de98304e57.png">

**Comment by jeroenvanwissen** [comment]
Default open size for 'New Alias' and 'New Cert' are good, but they can be resized smaller and description text cuts off.

'New Offer' screen is still (too) big, and can't be resized to smaller size. It doesn't fit on my macbook retina screen ( 1680 x 1050 )
