### ISSUE TITLE
Improved Versioning

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin#91]
As requested by exchanges, and just because its the right thing to do, we need to revise our in-app versioning system.

The proposal is tiered versioning, with the app having a version and then sys and btc having their own component versions. The app version would be what is displayed in 'getinfo.version' and getinfo would be updated to return the component versions as well.
### Examples:

**Syscoin 2.0** = app version 2.0; bitcoin 0.12.99, syscoin 2.0
**Syscoin 2.1** = app version 2.1; bitcoin 0.12.99, syscoin 2.1
**Syscoin 2.1.1** = app version 2.1.1; bitcoin 0.13, syscoin 2.1

getinfo on Syscoin 2.1.1:
`{
  "version": 211000,
  "btcversion": 129900,
  "sysversion": 211000,
  "protocolversion": 70013,
  "walletversion": 60000,
  "balance": 498.61734603,
  "blocks": 15160,
  "timeoffset": 0,
  "connections": 2,
  "proxy": "",
  "difficulty": 0.02030523381460471,
  "testnet": true,
  "keypoololdest": 1466222485,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}`

**Comment by sidhujag** [comment]
The current version scheme applies the last commit GUID to the version

for example:

Syscoin Core version v0.12.99.0-265ead5 (32-bit)

We can quickly see what version this was in our commit history and thus do not have to touch the core code.

**Comment by willyko** [comment]
we have version, btcversion, dashversion now
