### ISSUE TITLE
Purchased my own item, quantity didn't update

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin#94]
I purchased one of my own items and the quantity didn't change.

Offer ID: 9352d7d5019a6138

My seller alias expired and I recreated it using the same name before I bought the item - could be relevant?

Scenario one steps:
1 - buy your own offer, see if quantity updates

Scenario two steps (if previous steps doesn't catch bug):
1 - create alias
2 - list an offer: set quantity to 5, safe search = No, private = No, currency = USD, price = 1
3 - wait for alias to expire
4 - recreate alias using same name
5 - buy your own offer using escrow, see if quantity updates

**Comment by sidhujag** [comment]
Issue is step 5 doesn't update qty

**Comment by sidhujag** [comment]
need to retest this in release
